// ══════════════════════════════════════════════════════════════════════════════
// Batch 4A Seed Contacts — R&B/Soul, Jazz, Americana/Roots, Classical
// 237 contacts across blogs, curators, radio, and podcasters.
// All emails use organizational/role-based patterns.
// ══════════════════════════════════════════════════════════════════════════════

import { SeedContact } from "./seed-radio";

const cid = (e: string) => "seed-4a-" + e.replace(/[@.]/g, "-");

export const batch4aSeedContacts: SeedContact[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // R&B / SOUL (54 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — R&B/Soul Blogs (20) —
  { id: cid("submissions@vibe.com"), name: "Vibe Magazine Music", email: "submissions@vibe.com", outlet: "Vibe Magazine", type: "blog", genre: "R&B, Soul, Hip Hop", region: "US", beat: "R&B News, Reviews, Culture", bio: "Iconic music and entertainment magazine covering R&B, hip hop, and pop culture.", website: "https://vibe.com", verified: false, articleCount: 0 },
  { id: cid("music@bet.com"), name: "BET Music Editorial", email: "music@bet.com", outlet: "BET Music", type: "blog", genre: "R&B, Soul, Hip Hop", region: "US", beat: "R&B, Hip Hop, New Releases", bio: "BET's music vertical covering R&B and hip hop news, videos, and premieres.", website: "https://bet.com", verified: false, articleCount: 0 },
  { id: cid("submissions@revolt.tv"), name: "Revolt TV Music", email: "submissions@revolt.tv", outlet: "Revolt TV", type: "blog", genre: "R&B, Soul, Hip Hop", region: "US", beat: "R&B, Hip Hop, Music News", bio: "Multi-platform music network covering R&B, hip hop, and culture.", website: "https://revolt.tv", verified: false, articleCount: 0 },
  { id: cid("music@globalgrind.com"), name: "Global Grind Music", email: "music@globalgrind.com", outlet: "Global Grind", type: "blog", genre: "R&B, Soul, Hip Hop", region: "US", beat: "R&B, Urban Music, Culture", bio: "Urban culture and music platform covering R&B, hip hop, and entertainment.", website: "https://globalgrind.com", verified: false, articleCount: 0 },
  { id: cid("tips@balleralert.com"), name: "Baller Alert Music", email: "tips@balleralert.com", outlet: "Baller Alert", type: "blog", genre: "R&B, Soul, Hip Hop", region: "US", beat: "R&B, Hip Hop, Entertainment News", bio: "Entertainment and music blog covering R&B, hip hop, and celebrity news.", website: "https://balleralert.com", verified: false, articleCount: 0 },
  { id: cid("music@madamenoire.com"), name: "MadameNoire Music", email: "music@madamenoire.com", outlet: "MadameNoire", type: "blog", genre: "R&B, Soul", region: "US", beat: "R&B, Soul, Women in Music", bio: "Lifestyle and entertainment platform featuring R&B and soul music coverage.", website: "https://madamenoire.com", verified: false, articleCount: 0 },
  { id: cid("music@hellobeautiful.com"), name: "HelloBeautiful Music", email: "music@hellobeautiful.com", outlet: "HelloBeautiful", type: "blog", genre: "R&B, Soul", region: "US", beat: "R&B, Pop, Entertainment", bio: "Entertainment and lifestyle site with R&B and soul music features.", website: "https://hellobeautiful.com", verified: false, articleCount: 0 },
  { id: cid("editor@uptownmagazine.com"), name: "Uptown Magazine Music", email: "editor@uptownmagazine.com", outlet: "Uptown Magazine", type: "blog", genre: "R&B, Soul", region: "US", beat: "R&B, Soul, Luxury Culture", bio: "Upscale lifestyle magazine featuring R&B, soul, and culture coverage.", website: "https://uptownmagazine.com", verified: false, articleCount: 0 },
  { id: cid("submissions@urbanbridgez.com"), name: "Urban Bridgez", email: "submissions@urbanbridgez.com", outlet: "Urban Bridgez", type: "blog", genre: "R&B, Soul", region: "US", beat: "R&B, Soul, Gospel, New Music", bio: "Online urban music magazine covering R&B, soul, and gospel.", website: "https://urbanbridgez.com", verified: false, articleCount: 0 },
  { id: cid("submissions@parlourmagazine.com"), name: "Parlour Magazine Music", email: "submissions@parlourmagazine.com", outlet: "Parlour Magazine", type: "blog", genre: "R&B, Soul", region: "US", beat: "R&B, Indie Soul, Emerging Artists", bio: "Independent music and culture magazine spotlighting R&B and soul artists.", website: "https://parlourmagazine.com", verified: false, articleCount: 0 },
  { id: cid("editor@soultracks.com"), name: "SoulTracks Editorial", email: "editor@soultracks.com", outlet: "SoulTracks", type: "blog", genre: "R&B, Soul", region: "US", beat: "Soul Music Reviews, Features", bio: "Leading soul and R&B music review site with in-depth album reviews and artist interviews.", website: "https://soultracks.com", verified: false, articleCount: 0 },
  { id: cid("submissions@youknowigotsoul.com"), name: "YouKnowIGotSoul", email: "submissions@youknowigotsoul.com", outlet: "YouKnowIGotSoul", type: "blog", genre: "R&B, Soul", region: "US", beat: "R&B Interviews, New Music", bio: "R&B-focused blog known for in-depth artist interviews and exclusive premieres.", website: "https://youknowigotsoul.com", verified: false, articleCount: 0 },
  { id: cid("editor@grownfolksmusic.com"), name: "Grown Folks Music", email: "editor@grownfolksmusic.com", outlet: "Grown Folks Music", type: "blog", genre: "R&B, Soul", region: "US", beat: "Adult R&B, Classic Soul, Reviews", bio: "Blog dedicated to adult R&B, classic soul, and mature music lovers.", website: "https://grownfolksmusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@soulculture.com"), name: "Soul Culture", email: "submissions@soulculture.com", outlet: "Soul Culture", type: "blog", genre: "R&B, Soul", region: "UK", beat: "R&B, Soul, UK Urban Music", bio: "UK-based soul and R&B music blog covering new releases and culture.", website: "https://soulculture.com", verified: false, articleCount: 0 },
  { id: cid("submissions@rnbjunkie.com"), name: "RnB Junkie", email: "submissions@rnbjunkie.com", outlet: "RnB Junkie", type: "blog", genre: "R&B, Soul", region: "US", beat: "R&B New Releases, Reviews", bio: "Dedicated R&B blog covering the latest releases, reviews, and artist news.", website: "https://rnbjunkie.com", verified: false, articleCount: 0 },
  { id: cid("rnb@thefader.com"), name: "The Fader R&B", email: "rnb@thefader.com", outlet: "The Fader", type: "blog", genre: "R&B, Soul, Pop", region: "US", beat: "R&B, Alternative R&B, New Music", bio: "The Fader's R&B coverage spotlighting emerging and alternative R&B artists.", website: "https://thefader.com", verified: false, articleCount: 0 },
  { id: cid("submissions@rnbradar.com"), name: "R&B Radar", email: "submissions@rnbradar.com", outlet: "R&B Radar", type: "blog", genre: "R&B, Soul", region: "US", beat: "Emerging R&B Artists, New Music", bio: "Blog tracking emerging R&B talent and new releases.", website: "https://rnbradar.com", verified: false, articleCount: 0 },
  { id: cid("submissions@neosoulcafe.com"), name: "Neo Soul Cafe", email: "submissions@neosoulcafe.com", outlet: "Neo Soul Cafe", type: "blog", genre: "R&B, Neo-Soul", region: "US", beat: "Neo-Soul, Indie R&B, Features", bio: "Blog celebrating neo-soul and indie R&B music culture.", website: "https://neosoulcafe.com", verified: false, articleCount: 0 },
  { id: cid("submissions@soulfactorymusic.com"), name: "Soul Factory Music", email: "submissions@soulfactorymusic.com", outlet: "Soul Factory", type: "blog", genre: "R&B, Soul", region: "US", beat: "Soul Music, R&B, Gospel", bio: "Music blog covering soul, R&B, and gospel with reviews and interviews.", website: "https://soulfactorymusic.com", verified: false, articleCount: 0 },
  { id: cid("music@theurbandaily.com"), name: "The Urban Daily Music", email: "music@theurbandaily.com", outlet: "The Urban Daily", type: "blog", genre: "R&B, Soul, Hip Hop", region: "US", beat: "Urban Music, R&B, Culture", bio: "Urban music and culture blog covering R&B, hip hop, and entertainment.", website: "https://theurbandaily.com", verified: false, articleCount: 0 },

  // — R&B/Soul Curators (14) —
  { id: cid("curator@chilledrnb.com"), name: "Chilled R&B Playlist", email: "curator@chilledrnb.com", outlet: "Chilled R&B", type: "curator", genre: "R&B, Soul", region: "US", beat: "Chill R&B, Smooth R&B Playlists", bio: "Curator of chilled and smooth R&B playlists for relaxation and vibes.", website: "https://chilledrnb.com", verified: false, articleCount: 0 },
  { id: cid("curator@rnbnow.com"), name: "R&B Now", email: "curator@rnbnow.com", outlet: "R&B Now", type: "curator", genre: "R&B, Soul", region: "US", beat: "Current R&B Hits, New Releases", bio: "Playlist curator featuring the hottest current R&B tracks.", website: "https://rnbnow.com", verified: false, articleCount: 0 },
  { id: cid("curator@slowjamz.com"), name: "Slow Jamz Official", email: "curator@slowjamz.com", outlet: "Slow Jamz Official", type: "curator", genre: "R&B, Soul", region: "US", beat: "Slow Jams, Classic R&B", bio: "Curator of slow jam and classic R&B playlists.", website: "https://slowjamz.com", verified: false, articleCount: 0 },
  { id: cid("curator@neosoullounge.com"), name: "Neo Soul Lounge", email: "curator@neosoullounge.com", outlet: "Neo Soul Lounge", type: "curator", genre: "R&B, Soul", region: "US", beat: "Neo-Soul Playlists", bio: "Curator dedicated to neo-soul and alternative R&B playlists.", website: "https://neosoullounge.com", verified: false, articleCount: 0 },
  { id: cid("curator@moodringmusic.com"), name: "Mood Ring Music", email: "curator@moodringmusic.com", outlet: "Mood Ring Music", type: "curator", genre: "R&B, Soul", region: "US", beat: "Mood-Based R&B Playlists", bio: "Mood-driven R&B and soul playlist curator.", website: "https://moodringmusic.com", verified: false, articleCount: 0 },
  { id: cid("curator@latenightvibes.com"), name: "Late Night Vibes", email: "curator@latenightvibes.com", outlet: "Late Night Vibes", type: "curator", genre: "R&B, Soul", region: "US", beat: "Late Night R&B, Chill Playlists", bio: "Curator of late-night R&B and chill vibes playlists.", website: "https://latenightvibes.com", verified: false, articleCount: 0 },
  { id: cid("curator@smoothrnb.com"), name: "Smooth R&B", email: "curator@smoothrnb.com", outlet: "Smooth R&B", type: "curator", genre: "R&B, Soul", region: "US", beat: "Smooth R&B Playlists", bio: "Curator of smooth and silky R&B playlists.", website: "https://smoothrnb.com", verified: false, articleCount: 0 },
  { id: cid("curator@rnbseason.com"), name: "R&B Season", email: "curator@rnbseason.com", outlet: "R&B Season", type: "curator", genre: "R&B, Soul", region: "US", beat: "Seasonal R&B Playlists", bio: "Curator of seasonal R&B playlists featuring new and classic tracks.", website: "https://rnbseason.com", verified: false, articleCount: 0 },
  { id: cid("curator@soulcoffee.com"), name: "Soul Coffee", email: "curator@soulcoffee.com", outlet: "Soul Coffee", type: "curator", genre: "R&B, Soul", region: "US", beat: "Morning Soul, Chill R&B", bio: "Curator of soul and R&B playlists perfect for morning coffee vibes.", website: "https://soulcoffee.com", verified: false, articleCount: 0 },
  { id: cid("curator@feelingoodplaylist.com"), name: "Feelin Good Playlist", email: "curator@feelingoodplaylist.com", outlet: "Feelin Good Playlist", type: "curator", genre: "R&B, Soul", region: "US", beat: "Feel-Good R&B, Upbeat Soul", bio: "Curator of feel-good R&B and upbeat soul playlists.", website: "https://feelingoodplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@sundaysoul.com"), name: "Sunday Soul", email: "curator@sundaysoul.com", outlet: "Sunday Soul", type: "curator", genre: "R&B, Soul", region: "US", beat: "Sunday Soul, Relaxing R&B", bio: "Curator of Sunday soul and relaxing R&B playlists.", website: "https://sundaysoul.com", verified: false, articleCount: 0 },
  { id: cid("curator@goldenhourrnb.com"), name: "Golden Hour R&B", email: "curator@goldenhourrnb.com", outlet: "Golden Hour R&B", type: "curator", genre: "R&B, Soul", region: "US", beat: "Golden Hour R&B Playlists", bio: "Curator of golden hour R&B playlists for sunset and chill moments.", website: "https://goldenhourrnb.com", verified: false, articleCount: 0 },
  { id: cid("curator@rnbessentials.com"), name: "R&B Essentials", email: "curator@rnbessentials.com", outlet: "R&B Essentials", type: "curator", genre: "R&B, Soul", region: "US", beat: "Essential R&B Tracks", bio: "Curator of essential R&B playlists spanning classic and contemporary.", website: "https://rnbessentials.com", verified: false, articleCount: 0 },
  { id: cid("curator@chillrnb.com"), name: "Chill R&B", email: "curator@chillrnb.com", outlet: "Chill R&B", type: "curator", genre: "R&B, Soul", region: "US", beat: "Chill R&B, Lo-Fi R&B", bio: "Curator of chill and lo-fi R&B playlists.", website: "https://chillrnb.com", verified: false, articleCount: 0 },

  // — R&B/Soul Radio (10) —
  { id: cid("music@wbls.com"), name: "WBLS New York", email: "music@wbls.com", outlet: "WBLS 107.5", type: "radio", genre: "R&B, Soul", region: "US - New York, NY", beat: "R&B, Soul, Classic R&B Radio", bio: "New York's iconic R&B and classic soul radio station.", website: "https://wbls.com", verified: false, articleCount: 0 },
  { id: cid("music@wdasfm.com"), name: "WDAS Philadelphia", email: "music@wdasfm.com", outlet: "WDAS 105.3", type: "radio", genre: "R&B, Soul", region: "US - Philadelphia, PA", beat: "R&B, Soul, Urban Adult Contemporary", bio: "Philadelphia's premier R&B and soul radio station.", website: "https://wdasfm.com", verified: false, articleCount: 0 },
  { id: cid("music@v103.com"), name: "V-103 Atlanta", email: "music@v103.com", outlet: "V-103", type: "radio", genre: "R&B, Soul, Hip Hop", region: "US - Atlanta, GA", beat: "R&B, Hip Hop Radio", bio: "Atlanta's R&B and hip hop radio station.", website: "https://v103.com", verified: false, articleCount: 0 },
  { id: cid("music@majic102.com"), name: "Majic 102 Houston", email: "music@majic102.com", outlet: "Majic 102.1", type: "radio", genre: "R&B, Soul", region: "US - Houston, TX", beat: "R&B, Classic Soul Radio", bio: "Houston's home for R&B and classic soul.", website: "https://majic102.com", verified: false, articleCount: 0 },
  { id: cid("music@wkys.com"), name: "WKYS Washington DC", email: "music@wkys.com", outlet: "WKYS 93.9", type: "radio", genre: "R&B, Soul, Hip Hop", region: "US - Washington, DC", beat: "R&B, Hip Hop Radio", bio: "Washington DC's R&B and hip hop radio station.", website: "https://wkys.com", verified: false, articleCount: 0 },
  { id: cid("music@whur.com"), name: "WHUR Washington DC", email: "music@whur.com", outlet: "WHUR 96.3", type: "radio", genre: "R&B, Soul", region: "US - Washington, DC", beat: "Urban Adult Contemporary, R&B", bio: "Howard University's urban adult contemporary radio station.", website: "https://whur.com", verified: false, articleCount: 0 },
  { id: cid("music@wmmj.com"), name: "WMMJ Majic DC", email: "music@wmmj.com", outlet: "WMMJ Majic 102.3", type: "radio", genre: "R&B, Soul", region: "US - Washington, DC", beat: "R&B, Classic Soul Radio", bio: "DC's Majic 102.3 playing classic and current R&B.", website: "https://wmmj.com", verified: false, articleCount: 0 },
  { id: cid("music@wpgc.com"), name: "WPGC Washington DC", email: "music@wpgc.com", outlet: "WPGC 95.5", type: "radio", genre: "R&B, Hip Hop", region: "US - Washington, DC", beat: "R&B, Hip Hop Radio", bio: "DC metro area R&B and hip hop radio station.", website: "https://wpgc.com", verified: false, articleCount: 0 },
  { id: cid("music@kday.com"), name: "KDAY Los Angeles", email: "music@kday.com", outlet: "KDAY 93.5", type: "radio", genre: "R&B, Hip Hop", region: "US - Los Angeles, CA", beat: "R&B, Hip Hop, Classic Hip Hop Radio", bio: "Los Angeles hip hop and R&B radio station.", website: "https://kday.com", verified: false, articleCount: 0 },
  { id: cid("music@wjlb.com"), name: "WJLB Detroit", email: "music@wjlb.com", outlet: "WJLB 97.9", type: "radio", genre: "R&B, Soul, Hip Hop", region: "US - Detroit, MI", beat: "R&B, Hip Hop Radio", bio: "Detroit's R&B and hip hop radio station.", website: "https://wjlb.com", verified: false, articleCount: 0 },

  // — R&B/Soul Podcasters (10) —
  { id: cid("show@rnbmoney.com"), name: "R&B Money Podcast", email: "show@rnbmoney.com", outlet: "R&B Money", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "R&B Industry, Artist Interviews", bio: "Podcast exploring the business and artistry of R&B music.", website: "https://rnbmoney.com", verified: false, articleCount: 0 },
  { id: cid("radio@soulection.com"), name: "Soulection Radio", email: "radio@soulection.com", outlet: "Soulection", type: "podcaster", genre: "R&B, Soul, Electronic", region: "US", beat: "Future Soul, R&B, Electronic", bio: "Global music collective and radio show blending soul, R&B, and electronic.", website: "https://soulection.com", verified: false, articleCount: 0 },
  { id: cid("show@thereadpodcast.com"), name: "The Read Podcast", email: "show@thereadpodcast.com", outlet: "The Read", type: "podcaster", genre: "R&B, Soul, Hip Hop", region: "US", beat: "R&B, Pop Culture, Commentary", bio: "Popular podcast covering R&B, hip hop, and pop culture with sharp commentary.", website: "https://thereadpodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@rnbonly.com"), name: "R&B Only", email: "show@rnbonly.com", outlet: "R&B Only", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "R&B Events, Music Discussion", bio: "R&B-focused podcast and event series celebrating R&B culture.", website: "https://rnbonly.com", verified: false, articleCount: 0 },
  { id: cid("show@fortherecordrnb.com"), name: "For the Record R&B", email: "show@fortherecordrnb.com", outlet: "For the Record R&B", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "R&B History, Album Reviews", bio: "Podcast diving deep into R&B history and classic album reviews.", website: "https://fortherecordrnb.com", verified: false, articleCount: 0 },
  { id: cid("show@newrnb.com"), name: "New R&B Podcast", email: "show@newrnb.com", outlet: "New R&B", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "New R&B Releases, Emerging Artists", bio: "Podcast spotlighting new R&B releases and emerging artists.", website: "https://newrnb.com", verified: false, articleCount: 0 },
  { id: cid("show@soulmusicpod.com"), name: "Soul Music Podcast", email: "show@soulmusicpod.com", outlet: "Soul Music Podcast", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "Soul Music History, Features", bio: "Podcast exploring the history and evolution of soul music.", website: "https://soulmusicpod.com", verified: false, articleCount: 0 },
  { id: cid("show@smoothgroovespod.com"), name: "Smooth Grooves Pod", email: "show@smoothgroovespod.com", outlet: "Smooth Grooves", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "Smooth R&B, Jazz-Soul Fusion", bio: "Podcast featuring smooth R&B grooves and jazz-soul fusion tracks.", website: "https://smoothgroovespod.com", verified: false, articleCount: 0 },
  { id: cid("show@quietstormpod.com"), name: "The Quiet Storm Pod", email: "show@quietstormpod.com", outlet: "The Quiet Storm", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "Quiet Storm R&B, Late Night Soul", bio: "Podcast celebrating the quiet storm tradition of smooth late-night R&B.", website: "https://quietstormpod.com", verified: false, articleCount: 0 },
  { id: cid("show@babymakingmusicpod.com"), name: "Baby Making Music Pod", email: "show@babymakingmusicpod.com", outlet: "Baby Making Music", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "Slow Jams, Romantic R&B", bio: "Podcast dedicated to romantic R&B and classic slow jams.", website: "https://babymakingmusicpod.com", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // JAZZ (56 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Jazz Blogs (20) —
  { id: cid("editor@jazzwise.com"), name: "JazzWise Editorial", email: "editor@jazzwise.com", outlet: "JazzWise", type: "blog", genre: "Jazz", region: "UK", beat: "Jazz Reviews, Features, News", bio: "Leading UK jazz magazine with album reviews, features, and news.", website: "https://jazzwise.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazzjournal.co.uk"), name: "Jazz Journal", email: "editor@jazzjournal.co.uk", outlet: "Jazz Journal", type: "blog", genre: "Jazz", region: "UK", beat: "Jazz Reviews, History, Features", bio: "Long-running UK jazz publication with reviews and historical features.", website: "https://jazzjournal.co.uk", verified: false, articleCount: 0 },
  { id: cid("editor@londonjazznews.com"), name: "London Jazz News", email: "editor@londonjazznews.com", outlet: "London Jazz News", type: "blog", genre: "Jazz", region: "UK - London", beat: "London Jazz Scene, Live Reviews", bio: "Online publication covering London's jazz scene with reviews and listings.", website: "https://londonjazznews.com", verified: false, articleCount: 0 },
  { id: cid("submissions@jazzrightnow.com"), name: "Jazz Right Now", email: "submissions@jazzrightnow.com", outlet: "Jazz Right Now", type: "blog", genre: "Jazz", region: "US", beat: "Avant-Garde Jazz, Free Jazz", bio: "Blog covering avant-garde, free jazz, and experimental improvised music.", website: "https://jazzrightnow.com", verified: false, articleCount: 0 },
  { id: cid("editor@birdistheworm.com"), name: "Bird Is the Worm", email: "editor@birdistheworm.com", outlet: "Bird Is the Worm", type: "blog", genre: "Jazz", region: "US", beat: "Creative Jazz, New Releases", bio: "Jazz blog focused on creative and adventurous jazz new releases.", website: "https://birdistheworm.com", verified: false, articleCount: 0 },
  { id: cid("editor@destinationout.com"), name: "Destination Out", email: "editor@destinationout.com", outlet: "Destination Out", type: "blog", genre: "Jazz", region: "US", beat: "Free Jazz, Avant-Garde, Improvisation", bio: "Blog dedicated to free jazz, avant-garde, and improvised music.", website: "https://destinationout.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazzineurope.com"), name: "Jazz In Europe", email: "editor@jazzineurope.com", outlet: "Jazz In Europe", type: "blog", genre: "Jazz", region: "Europe", beat: "European Jazz Scene, Reviews", bio: "Online magazine covering the European jazz scene with reviews and interviews.", website: "https://jazzineurope.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazzmonthly.com"), name: "Jazz Monthly", email: "editor@jazzmonthly.com", outlet: "Jazz Monthly", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Reviews, Monthly Features", bio: "Monthly jazz publication with album reviews and artist features.", website: "https://jazzmonthly.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazzpolice.com"), name: "Jazz Police", email: "editor@jazzpolice.com", outlet: "Jazz Police", type: "blog", genre: "Jazz", region: "US - Minneapolis", beat: "Twin Cities Jazz, Reviews", bio: "Minneapolis-based jazz blog covering local and national jazz scenes.", website: "https://jazzpolice.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazzweekly.com"), name: "Jazz Weekly", email: "editor@jazzweekly.com", outlet: "Jazz Weekly", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Album Reviews, Weekly Picks", bio: "Weekly jazz review publication with concise album reviews.", website: "https://jazzweekly.com", verified: false, articleCount: 0 },
  { id: cid("editor@somethingelsereviews.com"), name: "Something Else Reviews", email: "editor@somethingelsereviews.com", outlet: "Something Else Reviews", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Reviews, Retrospectives", bio: "Music review site with strong jazz coverage and retrospective features.", website: "https://somethingelsereviews.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazzspeaks.com"), name: "Jazz Speaks", email: "editor@jazzspeaks.com", outlet: "Jazz Speaks", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Commentary, Reviews", bio: "Jazz commentary and review blog with artist perspectives.", website: "https://jazzspeaks.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazzguitartoday.com"), name: "Jazz Guitar Today", email: "editor@jazzguitartoday.com", outlet: "Jazz Guitar Today", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Guitar, Gear, Interviews", bio: "Blog dedicated to jazz guitar with gear reviews, lessons, and interviews.", website: "https://jazzguitartoday.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazziz.com"), name: "Jazziz Magazine", email: "editor@jazziz.com", outlet: "Jazziz", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Features, Reviews, Culture", bio: "Premier jazz magazine with features, reviews, and curated listening.", website: "https://jazziz.com", verified: false, articleCount: 0 },
  { id: cid("editor@natechinen.com"), name: "Nate Chinen Blog", email: "editor@natechinen.com", outlet: "Nate Chinen", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Criticism, New Releases", bio: "Acclaimed jazz critic and author covering contemporary jazz.", website: "https://natechinen.com", verified: false, articleCount: 0 },
  { id: cid("editor@thejazzpage.com"), name: "The Jazz Page", email: "editor@thejazzpage.com", outlet: "The Jazz Page", type: "blog", genre: "Jazz", region: "US", beat: "Jazz News, Reviews, Listings", bio: "Jazz news and review site with event listings and album coverage.", website: "https://thejazzpage.com", verified: false, articleCount: 0 },
  { id: cid("editor@jazztrail.net"), name: "Jazz Trail", email: "editor@jazztrail.net", outlet: "Jazz Trail", type: "blog", genre: "Jazz", region: "US", beat: "Jazz Interviews, Live Reviews", bio: "Jazz blog featuring artist interviews and live performance reviews.", website: "https://jazztrail.net", verified: false, articleCount: 0 },
  { id: cid("editor@jazzviews.net"), name: "Jazz Views", email: "editor@jazzviews.net", outlet: "Jazz Views", type: "blog", genre: "Jazz", region: "UK", beat: "Jazz Reviews, UK Jazz Scene", bio: "UK jazz blog with album reviews and scene coverage.", website: "https://jazzviews.net", verified: false, articleCount: 0 },
  { id: cid("editor@marlbank.net"), name: "Marlbank Jazz", email: "editor@marlbank.net", outlet: "Marlbank", type: "blog", genre: "Jazz", region: "UK", beat: "Jazz Reviews, Features", bio: "UK jazz blog with reviews, features, and news.", website: "https://marlbank.net", verified: false, articleCount: 0 },
  { id: cid("editor@bebopspokenhere.com"), name: "Bebop Spoken Here", email: "editor@bebopspokenhere.com", outlet: "Bebop Spoken Here", type: "blog", genre: "Jazz", region: "UK - Northeast", beat: "Jazz Reviews, Live Reviews", bio: "Northeast England jazz blog covering live reviews and album reviews.", website: "https://bebopspokenhere.com", verified: false, articleCount: 0 },

  // — Jazz Radio (12) —
  { id: cid("music@wbgo.org"), name: "WBGO Newark", email: "music@wbgo.org", outlet: "WBGO 88.3", type: "radio", genre: "Jazz", region: "US - Newark, NJ", beat: "Jazz Radio, Live Sessions", bio: "America's premier jazz public radio station based in Newark.", website: "https://wbgo.org", verified: false, articleCount: 0 },
  { id: cid("music@kcsm.org"), name: "KCSM San Mateo", email: "music@kcsm.org", outlet: "KCSM 91.1", type: "radio", genre: "Jazz", region: "US - San Mateo, CA", beat: "Jazz Radio", bio: "Bay Area jazz radio station broadcasting from San Mateo.", website: "https://kcsm.org", verified: false, articleCount: 0 },
  { id: cid("music@kkjz.org"), name: "KKJZ Long Beach", email: "music@kkjz.org", outlet: "KKJZ 88.1", type: "radio", genre: "Jazz", region: "US - Long Beach, CA", beat: "Jazz, Blues Radio", bio: "Southern California jazz and blues public radio station.", website: "https://kkjz.org", verified: false, articleCount: 0 },
  { id: cid("music@knkx.org"), name: "KNKX Tacoma", email: "music@knkx.org", outlet: "KNKX 88.5", type: "radio", genre: "Jazz, Blues", region: "US - Tacoma, WA", beat: "Jazz, Blues, NPR Radio", bio: "Pacific Northwest public radio station featuring jazz, blues, and NPR news.", website: "https://knkx.org", verified: false, articleCount: 0 },
  { id: cid("music@wdcb.org"), name: "WDCB Chicago", email: "music@wdcb.org", outlet: "WDCB 90.9", type: "radio", genre: "Jazz", region: "US - Chicago, IL", beat: "Jazz Radio", bio: "Chicago-area public radio station dedicated to jazz.", website: "https://wdcb.org", verified: false, articleCount: 0 },
  { id: cid("music@wpfw.org"), name: "WPFW Washington DC", email: "music@wpfw.org", outlet: "WPFW 89.3", type: "radio", genre: "Jazz", region: "US - Washington, DC", beat: "Jazz, Community Radio", bio: "Pacifica community radio station in DC with strong jazz programming.", website: "https://wpfw.org", verified: false, articleCount: 0 },
  { id: cid("jazz@wrti.org"), name: "WRTI Jazz Philadelphia", email: "jazz@wrti.org", outlet: "WRTI Jazz", type: "radio", genre: "Jazz", region: "US - Philadelphia, PA", beat: "Jazz Radio", bio: "Philadelphia public radio station with dedicated jazz programming.", website: "https://wrti.org", verified: false, articleCount: 0 },
  { id: cid("jazz@wgbh.org"), name: "WGBH Jazz Boston", email: "jazz@wgbh.org", outlet: "WGBH Jazz", type: "radio", genre: "Jazz", region: "US - Boston, MA", beat: "Jazz Radio", bio: "Boston public media jazz programming.", website: "https://wgbh.org", verified: false, articleCount: 0 },
  { id: cid("music@jazzfm.com"), name: "Jazz FM UK", email: "music@jazzfm.com", outlet: "Jazz FM", type: "radio", genre: "Jazz", region: "UK", beat: "Jazz Radio, UK Jazz", bio: "UK's dedicated jazz radio station.", website: "https://jazzfm.com", verified: false, articleCount: 0 },
  { id: cid("music@tsfjazz.com"), name: "TSF Jazz Paris", email: "music@tsfjazz.com", outlet: "TSF Jazz", type: "radio", genre: "Jazz", region: "France - Paris", beat: "Jazz Radio", bio: "Parisian jazz radio station broadcasting jazz 24/7.", website: "https://tsfjazz.com", verified: false, articleCount: 0 },
  { id: cid("music@wucf.org"), name: "WUCF Jazz Orlando", email: "music@wucf.org", outlet: "WUCF Jazz", type: "radio", genre: "Jazz", region: "US - Orlando, FL", beat: "Jazz Radio", bio: "Central Florida jazz radio station from University of Central Florida.", website: "https://wucf.org", verified: false, articleCount: 0 },
  { id: cid("music@wclk.com"), name: "WCLK Atlanta", email: "music@wclk.com", outlet: "WCLK 91.9", type: "radio", genre: "Jazz", region: "US - Atlanta, GA", beat: "Jazz Radio", bio: "Atlanta's jazz radio station from Clark Atlanta University.", website: "https://wclk.com", verified: false, articleCount: 0 },

  // — Jazz Curators (14) —
  { id: cid("curator@jazzvibes.co"), name: "Jazz Vibes", email: "curator@jazzvibes.co", outlet: "Jazz Vibes", type: "curator", genre: "Jazz", region: "US", beat: "Jazz Playlists, Modern Jazz", bio: "Curator of modern and contemporary jazz playlists.", website: "https://jazzvibes.co", verified: false, articleCount: 0 },
  { id: cid("curator@stateofjazz.com"), name: "State of Jazz", email: "curator@stateofjazz.com", outlet: "State of Jazz", type: "curator", genre: "Jazz", region: "US", beat: "Contemporary Jazz Playlists", bio: "Curator showcasing the current state of jazz through playlists.", website: "https://stateofjazz.com", verified: false, articleCount: 0 },
  { id: cid("curator@coffeetablejazz.com"), name: "Coffee Table Jazz", email: "curator@coffeetablejazz.com", outlet: "Coffee Table Jazz", type: "curator", genre: "Jazz", region: "US", beat: "Chill Jazz, Background Jazz", bio: "Curator of relaxing jazz playlists for home and coffee shop vibes.", website: "https://coffeetablejazz.com", verified: false, articleCount: 0 },
  { id: cid("curator@jazzclassicsplaylist.com"), name: "Jazz Classics", email: "curator@jazzclassicsplaylist.com", outlet: "Jazz Classics", type: "curator", genre: "Jazz", region: "US", beat: "Classic Jazz, Standards", bio: "Curator of classic jazz standards and timeless recordings.", website: "https://jazzclassicsplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@jazzforstudy.com"), name: "Jazz for Study", email: "curator@jazzforstudy.com", outlet: "Jazz for Study", type: "curator", genre: "Jazz", region: "US", beat: "Study Jazz, Focus Jazz", bio: "Curator of jazz playlists for studying and focus.", website: "https://jazzforstudy.com", verified: false, articleCount: 0 },
  { id: cid("curator@smoothjazzvibes.com"), name: "Smooth Jazz Vibes", email: "curator@smoothjazzvibes.com", outlet: "Smooth Jazz Vibes", type: "curator", genre: "Jazz", region: "US", beat: "Smooth Jazz Playlists", bio: "Curator of smooth jazz playlists for relaxation.", website: "https://smoothjazzvibes.com", verified: false, articleCount: 0 },
  { id: cid("curator@pianojazz.co"), name: "Piano Jazz Playlist", email: "curator@pianojazz.co", outlet: "Piano Jazz", type: "curator", genre: "Jazz", region: "US", beat: "Piano Jazz, Solo Piano", bio: "Curator of piano jazz and solo piano playlists.", website: "https://pianojazz.co", verified: false, articleCount: 0 },
  { id: cid("curator@vocaljazzplaylist.com"), name: "Vocal Jazz", email: "curator@vocaljazzplaylist.com", outlet: "Vocal Jazz", type: "curator", genre: "Jazz", region: "US", beat: "Vocal Jazz, Jazz Singers", bio: "Curator of vocal jazz playlists featuring jazz singers.", website: "https://vocaljazzplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@modernjazzplaylist.com"), name: "Modern Jazz", email: "curator@modernjazzplaylist.com", outlet: "Modern Jazz", type: "curator", genre: "Jazz", region: "US", beat: "Modern Jazz, Contemporary Jazz", bio: "Curator of modern and contemporary jazz playlists.", website: "https://modernjazzplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@jazzloungeplaylist.com"), name: "Jazz Lounge", email: "curator@jazzloungeplaylist.com", outlet: "Jazz Lounge", type: "curator", genre: "Jazz", region: "US", beat: "Lounge Jazz, Cocktail Jazz", bio: "Curator of lounge and cocktail jazz playlists.", website: "https://jazzloungeplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@latenightjazz.co"), name: "Late Night Jazz", email: "curator@latenightjazz.co", outlet: "Late Night Jazz", type: "curator", genre: "Jazz", region: "US", beat: "Late Night Jazz Playlists", bio: "Curator of late-night jazz playlists for after-hours listening.", website: "https://latenightjazz.co", verified: false, articleCount: 0 },
  { id: cid("curator@jazzbrunch.co"), name: "Jazz Brunch", email: "curator@jazzbrunch.co", outlet: "Jazz Brunch", type: "curator", genre: "Jazz", region: "US", beat: "Brunch Jazz, Sunday Jazz", bio: "Curator of jazz brunch playlists for weekend mornings.", website: "https://jazzbrunch.co", verified: false, articleCount: 0 },
  { id: cid("curator@bluenotevibes.com"), name: "Blue Note Vibes", email: "curator@bluenotevibes.com", outlet: "Blue Note Vibes", type: "curator", genre: "Jazz", region: "US", beat: "Blue Note Jazz, Hard Bop", bio: "Curator of Blue Note-inspired jazz and hard bop playlists.", website: "https://bluenotevibes.com", verified: false, articleCount: 0 },
  { id: cid("curator@instrumentaljazz.co"), name: "Instrumental Jazz", email: "curator@instrumentaljazz.co", outlet: "Instrumental Jazz", type: "curator", genre: "Jazz", region: "US", beat: "Instrumental Jazz Playlists", bio: "Curator of instrumental jazz playlists.", website: "https://instrumentaljazz.co", verified: false, articleCount: 0 },

  // — Jazz Podcasters (10) —
  { id: cid("show@jazznightinamerica.org"), name: "Jazz Night in America", email: "show@jazznightinamerica.org", outlet: "Jazz Night in America", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz Performance, NPR Jazz", bio: "NPR and WBGO collaboration showcasing jazz performances across America.", website: "https://jazznightinamerica.org", verified: false, articleCount: 0 },
  { id: cid("show@thejazzsession.com"), name: "The Jazz Session", email: "show@thejazzsession.com", outlet: "The Jazz Session", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz Interviews, Album Discussions", bio: "Podcast featuring in-depth jazz artist interviews and album discussions.", website: "https://thejazzsession.com", verified: false, articleCount: 0 },
  { id: cid("show@playingchanges.com"), name: "Playing Changes", email: "show@playingchanges.com", outlet: "Playing Changes", type: "podcaster", genre: "Jazz", region: "US", beat: "Contemporary Jazz, Criticism", bio: "Podcast exploring the evolving landscape of contemporary jazz.", website: "https://playingchanges.com", verified: false, articleCount: 0 },
  { id: cid("show@jazzhang.com"), name: "Jazz Hang Podcast", email: "show@jazzhang.com", outlet: "Jazz Hang", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz Conversations, Community", bio: "Casual podcast conversations with jazz musicians and enthusiasts.", website: "https://jazzhang.com", verified: false, articleCount: 0 },
  { id: cid("show@thisisjazzpod.com"), name: "This Is Jazz Podcast", email: "show@thisisjazzpod.com", outlet: "This Is Jazz", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz Education, History", bio: "Podcast introducing listeners to jazz history and education.", website: "https://thisisjazzpod.com", verified: false, articleCount: 0 },
  { id: cid("show@jazzinspired.com"), name: "Jazz Inspired Podcast", email: "show@jazzinspired.com", outlet: "Jazz Inspired", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz Inspiration, Artist Stories", bio: "Podcast exploring the stories and inspirations behind jazz musicians.", website: "https://jazzinspired.com", verified: false, articleCount: 0 },
  { id: cid("show@jazzhistorypod.com"), name: "Jazz History Podcast", email: "show@jazzhistorypod.com", outlet: "Jazz History Podcast", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz History, Archives", bio: "Podcast diving deep into the history of jazz music.", website: "https://jazzhistorypod.com", verified: false, articleCount: 0 },
  { id: cid("show@jazzstandardpod.com"), name: "Jazz Standard Pod", email: "show@jazzstandardpod.com", outlet: "Jazz Standard", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz Standards, Song Histories", bio: "Podcast exploring the stories behind jazz standards.", website: "https://jazzstandardpod.com", verified: false, articleCount: 0 },
  { id: cid("show@jazzlives.com"), name: "Jazz Lives Podcast", email: "show@jazzlives.com", outlet: "Jazz Lives", type: "podcaster", genre: "Jazz", region: "US", beat: "Jazz Profiles, Live Music", bio: "Podcast profiling jazz musicians and documenting live performances.", website: "https://jazzlives.com", verified: false, articleCount: 0 },
  { id: cid("show@improvisedlife.com"), name: "The Improvised Life", email: "show@improvisedlife.com", outlet: "The Improvised Life", type: "podcaster", genre: "Jazz", region: "US", beat: "Improvisation, Jazz Philosophy", bio: "Podcast exploring improvisation in jazz and creative life.", website: "https://improvisedlife.com", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // AMERICANA / ROOTS (59 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Americana/Roots Blogs (22) —
  { id: cid("submissions@americanahighways.com"), name: "Americana Highways", email: "submissions@americanahighways.com", outlet: "Americana Highways", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana Reviews, Premieres", bio: "Blog covering Americana music with album reviews, premieres, and interviews.", website: "https://americanahighways.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thealternateroot.com"), name: "The Alternate Root", email: "submissions@thealternateroot.com", outlet: "The Alternate Root", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana, Roots, Alt-Country", bio: "Online magazine covering Americana, roots, and alt-country music.", website: "https://thealternateroot.com", verified: false, articleCount: 0 },
  { id: cid("submissions@theblueindian.com"), name: "The Blue Indian", email: "submissions@theblueindian.com", outlet: "The Blue Indian", type: "blog", genre: "Americana, Indie", region: "US - Southeast", beat: "Americana, Indie, Southern Music", bio: "Southeast-focused music blog covering Americana and indie music.", website: "https://theblueindian.com", verified: false, articleCount: 0 },
  { id: cid("editor@lonesomehighway.com"), name: "Lonesome Highway", email: "editor@lonesomehighway.com", outlet: "Lonesome Highway", type: "blog", genre: "Americana, Country", region: "Ireland", beat: "Americana, Country, Roots Reviews", bio: "Irish-based Americana and country music review site.", website: "https://lonesomehighway.com", verified: false, articleCount: 0 },
  { id: cid("submissions@heartsofamericana.com"), name: "Hearts of Americana", email: "submissions@heartsofamericana.com", outlet: "Hearts of Americana", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana, Folk, Roots Features", bio: "Blog dedicated to the heart and soul of Americana music.", website: "https://heartsofamericana.com", verified: false, articleCount: 0 },
  { id: cid("submissions@turnstyled.com"), name: "Turnstyled Junkpiled", email: "submissions@turnstyled.com", outlet: "Turnstyled Junkpiled", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana, Roots Rock, Reviews", bio: "Americana and roots rock music blog with reviews and features.", website: "https://turnstyled.com", verified: false, articleCount: 0 },
  { id: cid("submissions@twangnation.com"), name: "Twang Nation", email: "submissions@twangnation.com", outlet: "Twang Nation", type: "blog", genre: "Americana, Country, Roots", region: "US", beat: "Twang, Americana, Country", bio: "Blog celebrating twang, Americana, and roots country music.", website: "https://twangnation.com", verified: false, articleCount: 0 },
  { id: cid("submissions@milesofmusic.com"), name: "Miles of Music", email: "submissions@milesofmusic.com", outlet: "Miles of Music", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana, Live Music, Touring", bio: "Blog covering Americana music with focus on live performances and touring.", website: "https://milesofmusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@redlineroots.com"), name: "Red Line Roots", email: "submissions@redlineroots.com", outlet: "Red Line Roots", type: "blog", genre: "Americana, Roots", region: "US", beat: "Roots Music, Americana Reviews", bio: "Roots and Americana music blog with reviews and artist features.", website: "https://redlineroots.com", verified: false, articleCount: 0 },
  { id: cid("submissions@muddyrootsmusic.com"), name: "Muddy Roots Music", email: "submissions@muddyrootsmusic.com", outlet: "Muddy Roots", type: "blog", genre: "Americana, Roots, Punk", region: "US", beat: "Roots, Punk, Outlaw Country", bio: "Blog and festival covering roots, punk-influenced, and outlaw country music.", website: "https://muddyrootsmusic.com", verified: false, articleCount: 0 },
  { id: cid("editor@americanarhythm.com"), name: "Americana Rhythm", email: "editor@americanarhythm.com", outlet: "Americana Rhythm", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana, Roots, Bluegrass", bio: "Magazine covering Americana, roots, and bluegrass music.", website: "https://americanarhythm.com", verified: false, articleCount: 0 },
  { id: cid("submissions@allrootsallday.com"), name: "All Roots All Day", email: "submissions@allrootsallday.com", outlet: "All Roots All Day", type: "blog", genre: "Americana, Roots", region: "US", beat: "Roots Music, Daily Features", bio: "Daily roots music blog with features and new discoveries.", website: "https://allrootsallday.com", verified: false, articleCount: 0 },
  { id: cid("submissions@rootszone.com"), name: "Roots Zone", email: "submissions@rootszone.com", outlet: "Roots Zone", type: "blog", genre: "Americana, Roots", region: "US", beat: "Roots Music, Reviews", bio: "Blog dedicated to roots music reviews and features.", website: "https://rootszone.com", verified: false, articleCount: 0 },
  { id: cid("tips@nashvillenoise.com"), name: "Nashville Noise", email: "tips@nashvillenoise.com", outlet: "Nashville Noise", type: "blog", genre: "Americana, Country, Indie", region: "US - Nashville", beat: "Nashville Music Scene, Americana", bio: "Nashville music blog covering the city's Americana and indie scenes.", website: "https://nashvillenoise.com", verified: false, articleCount: 0 },
  { id: cid("editor@cosmicamerican.com"), name: "Cosmic American", email: "editor@cosmicamerican.com", outlet: "Cosmic American", type: "blog", genre: "Americana, Roots", region: "US", beat: "Cosmic Americana, Psychedelic Country", bio: "Blog exploring cosmic Americana and psychedelic country music.", website: "https://cosmicamerican.com", verified: false, articleCount: 0 },
  { id: cid("submissions@woodshedcommunity.com"), name: "Woodshed Community", email: "submissions@woodshedcommunity.com", outlet: "Woodshed Community", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana, Community Music", bio: "Community-focused Americana music blog.", website: "https://woodshedcommunity.com", verified: false, articleCount: 0 },
  { id: cid("submissions@ninebullets.net"), name: "Nine Bullets", email: "submissions@ninebullets.net", outlet: "Nine Bullets", type: "blog", genre: "Americana, Alt-Country", region: "US", beat: "Alt-Country, Americana, Reviews", bio: "Long-running alt-country and Americana music blog.", website: "https://ninebullets.net", verified: false, articleCount: 0 },
  { id: cid("tips@savingcountrymusic.com"), name: "Saving Country Music", email: "tips@savingcountrymusic.com", outlet: "Saving Country Music", type: "blog", genre: "Americana, Country, Roots", region: "US", beat: "Independent Country, Americana", bio: "Influential blog championing independent country and Americana music.", website: "https://savingcountrymusic.com", verified: false, articleCount: 0 },
  { id: cid("music@bittersoutherner.com"), name: "The Bitter Southerner Music", email: "music@bittersoutherner.com", outlet: "The Bitter Southerner", type: "blog", genre: "Americana, Roots, Southern", region: "US - Southeast", beat: "Southern Music, Americana, Culture", bio: "Southern culture publication with strong Americana and roots music coverage.", website: "https://bittersoutherner.com", verified: false, articleCount: 0 },
  { id: cid("submissions@holler.country"), name: "Holler", email: "submissions@holler.country", outlet: "Holler", type: "blog", genre: "Americana, Country", region: "UK", beat: "Country, Americana, UK Country Scene", bio: "UK-based country and Americana music publication.", website: "https://holler.country", verified: false, articleCount: 0 },
  { id: cid("submissions@americanaround.com"), name: "The Americana Round", email: "submissions@americanaround.com", outlet: "The Americana Round", type: "blog", genre: "Americana, Roots", region: "US", beat: "Americana, Songwriter Rounds", bio: "Blog covering Americana music with focus on songwriter rounds and features.", website: "https://americanaround.com", verified: false, articleCount: 0 },
  { id: cid("submissions@roughstock.com"), name: "Roughstock", email: "submissions@roughstock.com", outlet: "Roughstock", type: "blog", genre: "Americana, Country", region: "US", beat: "Country, Americana, Charts", bio: "Country and Americana music blog with chart analysis and reviews.", website: "https://roughstock.com", verified: false, articleCount: 0 },

  // — Americana/Roots Radio (15) —
  { id: cid("music@wmot.org"), name: "WMOT Roots Nashville", email: "music@wmot.org", outlet: "WMOT Roots Radio", type: "radio", genre: "Americana, Roots", region: "US - Nashville, TN", beat: "Americana, Roots Radio", bio: "Nashville's Americana and roots radio station from Middle Tennessee State University.", website: "https://wmot.org", verified: false, articleCount: 0 },
  { id: cid("music@wxnafm.org"), name: "WXNA Nashville", email: "music@wxnafm.org", outlet: "WXNA 101.5", type: "radio", genre: "Americana, Roots, Eclectic", region: "US - Nashville, TN", beat: "Community Radio, Americana", bio: "Nashville community radio station with eclectic and Americana programming.", website: "https://wxnafm.org", verified: false, articleCount: 0 },
  { id: cid("music@kdhx.org"), name: "KDHX St. Louis", email: "music@kdhx.org", outlet: "KDHX 88.1", type: "radio", genre: "Americana, Roots, Folk", region: "US - St. Louis, MO", beat: "Community Radio, Americana, Folk", bio: "St. Louis community radio with strong Americana and roots programming.", website: "https://kdhx.org", verified: false, articleCount: 0 },
  { id: cid("music@wnrn.org"), name: "WNRN Charlottesville", email: "music@wnrn.org", outlet: "WNRN 91.9", type: "radio", genre: "Americana, Indie, Roots", region: "US - Charlottesville, VA", beat: "Americana, Indie Radio", bio: "Charlottesville independent radio featuring Americana and indie music.", website: "https://wnrn.org", verified: false, articleCount: 0 },
  { id: cid("music@wncw.org"), name: "WNCW Spindale", email: "music@wncw.org", outlet: "WNCW 88.7", type: "radio", genre: "Americana, Roots, Bluegrass", region: "US - Spindale, NC", beat: "Roots, Bluegrass, Americana Radio", bio: "Western North Carolina public radio with roots, bluegrass, and Americana.", website: "https://wncw.org", verified: false, articleCount: 0 },
  { id: cid("music@wdvx.com"), name: "WDVX Knoxville", email: "music@wdvx.com", outlet: "WDVX 89.9", type: "radio", genre: "Americana, Roots, Bluegrass", region: "US - Knoxville, TN", beat: "Americana, Bluegrass Radio", bio: "Knoxville community radio dedicated to Americana, roots, and bluegrass.", website: "https://wdvx.com", verified: false, articleCount: 0 },
  { id: cid("music@kvmr.org"), name: "KVMR Nevada City", email: "music@kvmr.org", outlet: "KVMR 89.5", type: "radio", genre: "Americana, Folk, Eclectic", region: "US - Nevada City, CA", beat: "Community Radio, Americana", bio: "Nevada City community radio with Americana and folk programming.", website: "https://kvmr.org", verified: false, articleCount: 0 },
  { id: cid("music@krcl.org"), name: "KRCL Salt Lake City", email: "music@krcl.org", outlet: "KRCL 90.9", type: "radio", genre: "Americana, Roots, Eclectic", region: "US - Salt Lake City, UT", beat: "Community Radio, Americana", bio: "Salt Lake City community radio with eclectic and Americana programming.", website: "https://krcl.org", verified: false, articleCount: 0 },
  { id: cid("music@krfc.fm"), name: "KRFC Fort Collins", email: "music@krfc.fm", outlet: "KRFC 88.9", type: "radio", genre: "Americana, Roots", region: "US - Fort Collins, CO", beat: "Community Radio, Americana", bio: "Fort Collins community radio station featuring Americana and roots.", website: "https://krfc.fm", verified: false, articleCount: 0 },
  { id: cid("music@wfpk.org"), name: "WFPK Louisville", email: "music@wfpk.org", outlet: "WFPK 91.9", type: "radio", genre: "Americana, Indie, Roots", region: "US - Louisville, KY", beat: "Americana, Indie Radio", bio: "Louisville public radio with Americana and indie music programming.", website: "https://wfpk.org", verified: false, articleCount: 0 },
  { id: cid("music@wlrn.org"), name: "WLRN Miami", email: "music@wlrn.org", outlet: "WLRN 91.3", type: "radio", genre: "Americana, Folk", region: "US - Miami, FL", beat: "Public Radio, Americana", bio: "South Florida public radio with Americana programming.", website: "https://wlrn.org", verified: false, articleCount: 0 },
  { id: cid("americana@wyep.org"), name: "WYEP Americana Pittsburgh", email: "americana@wyep.org", outlet: "WYEP 91.3", type: "radio", genre: "Americana, Indie", region: "US - Pittsburgh, PA", beat: "Americana, Indie Radio", bio: "Pittsburgh public radio with Americana and indie programming.", website: "https://wyep.org", verified: false, articleCount: 0 },
  { id: cid("americana@kutx.org"), name: "KUTX Americana Austin", email: "americana@kutx.org", outlet: "KUTX 98.9", type: "radio", genre: "Americana, Roots", region: "US - Austin, TX", beat: "Austin Music, Americana Radio", bio: "Austin public radio with strong Americana and roots programming.", website: "https://kutx.org", verified: false, articleCount: 0 },
  { id: cid("americana@kexp.org"), name: "KEXP Americana Seattle", email: "americana@kexp.org", outlet: "KEXP 90.3", type: "radio", genre: "Americana, Indie, Roots", region: "US - Seattle, WA", beat: "Americana, Indie Radio", bio: "Seattle public radio with Americana and roots music programming.", website: "https://kexp.org", verified: false, articleCount: 0 },
  { id: cid("music@siriusxm.com"), name: "Sirius Outlaw Country", email: "music@siriusxm.com", outlet: "SiriusXM Outlaw Country", type: "radio", genre: "Americana, Outlaw Country", region: "US - National", beat: "Outlaw Country, Americana Radio", bio: "SiriusXM's outlaw country and Americana satellite radio channel.", website: "https://siriusxm.com", verified: false, articleCount: 0 },

  // — Americana/Roots Curators (12) —
  { id: cid("curator@freshamericana.com"), name: "Fresh Americana", email: "curator@freshamericana.com", outlet: "Fresh Americana", type: "curator", genre: "Americana, Roots", region: "US", beat: "New Americana Releases", bio: "Curator of fresh Americana playlists featuring new releases.", website: "https://freshamericana.com", verified: false, articleCount: 0 },
  { id: cid("curator@outlawcountryplaylist.com"), name: "Outlaw Country Playlist", email: "curator@outlawcountryplaylist.com", outlet: "Outlaw Country", type: "curator", genre: "Americana, Outlaw Country", region: "US", beat: "Outlaw Country Playlists", bio: "Curator of outlaw country and Americana playlists.", website: "https://outlawcountryplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@rootsrockplaylist.com"), name: "Roots Rock Playlist", email: "curator@rootsrockplaylist.com", outlet: "Roots Rock", type: "curator", genre: "Americana, Roots Rock", region: "US", beat: "Roots Rock Playlists", bio: "Curator of roots rock playlists.", website: "https://rootsrockplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@reddirtplaylist.com"), name: "Red Dirt Playlist", email: "curator@reddirtplaylist.com", outlet: "Red Dirt", type: "curator", genre: "Americana, Red Dirt", region: "US - Oklahoma, Texas", beat: "Red Dirt Music Playlists", bio: "Curator of Red Dirt music playlists from Oklahoma and Texas.", website: "https://reddirtplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@americanaroadtrip.co"), name: "Americana Road Trip", email: "curator@americanaroadtrip.co", outlet: "Americana Road Trip", type: "curator", genre: "Americana, Roots", region: "US", beat: "Road Trip Americana Playlists", bio: "Curator of Americana road trip playlists.", website: "https://americanaroadtrip.co", verified: false, articleCount: 0 },
  { id: cid("curator@sundayamericana.com"), name: "Sunday Morning Americana", email: "curator@sundayamericana.com", outlet: "Sunday Morning Americana", type: "curator", genre: "Americana, Roots", region: "US", beat: "Sunday Morning Americana Playlists", bio: "Curator of Sunday morning Americana and roots playlists.", website: "https://sundayamericana.com", verified: false, articleCount: 0 },
  { id: cid("curator@frontporchamericana.com"), name: "Front Porch Americana", email: "curator@frontporchamericana.com", outlet: "Front Porch Americana", type: "curator", genre: "Americana, Folk", region: "US", beat: "Front Porch Americana Playlists", bio: "Curator of front porch-style Americana and folk playlists.", website: "https://frontporchamericana.com", verified: false, articleCount: 0 },
  { id: cid("curator@heartlandrockplaylist.com"), name: "Heartland Rock", email: "curator@heartlandrockplaylist.com", outlet: "Heartland Rock", type: "curator", genre: "Americana, Heartland Rock", region: "US", beat: "Heartland Rock Playlists", bio: "Curator of heartland rock playlists.", website: "https://heartlandrockplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@altcountryplaylist.com"), name: "Alt Country Playlist", email: "curator@altcountryplaylist.com", outlet: "Alt Country", type: "curator", genre: "Americana, Alt-Country", region: "US", beat: "Alt-Country Playlists", bio: "Curator of alt-country playlists.", website: "https://altcountryplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@rootsrevival.co"), name: "Roots Revival", email: "curator@rootsrevival.co", outlet: "Roots Revival", type: "curator", genre: "Americana, Roots", region: "US", beat: "Roots Revival Playlists", bio: "Curator of roots revival and classic Americana playlists.", website: "https://rootsrevival.co", verified: false, articleCount: 0 },
  { id: cid("curator@honkytonkhighway.co"), name: "Honky Tonk Highway", email: "curator@honkytonkhighway.co", outlet: "Honky Tonk Highway", type: "curator", genre: "Americana, Honky Tonk", region: "US", beat: "Honky Tonk Playlists", bio: "Curator of honky tonk and classic country playlists.", website: "https://honkytonkhighway.co", verified: false, articleCount: 0 },
  { id: cid("curator@americanagold.co"), name: "Americana Gold", email: "curator@americanagold.co", outlet: "Americana Gold", type: "curator", genre: "Americana, Roots", region: "US", beat: "Classic Americana Playlists", bio: "Curator of classic and golden-era Americana playlists.", website: "https://americanagold.co", verified: false, articleCount: 0 },

  // — Americana/Roots Podcasters (10) —
  { id: cid("show@americanapodcast.com"), name: "The Americana Podcast", email: "show@americanapodcast.com", outlet: "The Americana Podcast", type: "podcaster", genre: "Americana, Roots", region: "US", beat: "Americana Interviews, Features", bio: "Podcast featuring interviews with Americana and roots music artists.", website: "https://americanapodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@shooterjennings.com"), name: "Shootin the Breeze with Shooter", email: "show@shooterjennings.com", outlet: "Shootin the Breeze", type: "podcaster", genre: "Americana, Outlaw Country", region: "US", beat: "Outlaw Country, Americana, Music Industry", bio: "Shooter Jennings' podcast covering Americana, outlaw country, and music industry.", website: "https://shooterjennings.com", verified: false, articleCount: 0 },
  { id: cid("show@thebluegraspodcast.com"), name: "The Bluegrass Podcast", email: "show@thebluegraspodcast.com", outlet: "The Bluegrass Podcast", type: "podcaster", genre: "Americana, Bluegrass", region: "US", beat: "Bluegrass, Americana, Roots", bio: "Podcast dedicated to bluegrass and Americana roots music.", website: "https://thebluegraspodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@cocaineandrhinestones.com"), name: "Cocaine & Rhinestones", email: "show@cocaineandrhinestones.com", outlet: "Cocaine & Rhinestones", type: "podcaster", genre: "Americana, Country", region: "US", beat: "Country Music History", bio: "Podcast exploring the hidden history of country music.", website: "https://cocaineandrhinestones.com", verified: false, articleCount: 0 },
  { id: cid("show@fistfulofamericana.com"), name: "Fistful of Americana", email: "show@fistfulofamericana.com", outlet: "Fistful of Americana", type: "podcaster", genre: "Americana, Roots", region: "US", beat: "Americana Music, Artist Interviews", bio: "Podcast serving up a fistful of Americana music and artist conversations.", website: "https://fistfulofamericana.com", verified: false, articleCount: 0 },
  { id: cid("show@tylermahancoe.com"), name: "Tyler Mahan Coe Podcast", email: "show@tylermahancoe.com", outlet: "Tyler Mahan Coe", type: "podcaster", genre: "Americana, Country", region: "US", beat: "Country History, Storytelling", bio: "Podcast with deep dives into country and Americana music history.", website: "https://tylermahancoe.com", verified: false, articleCount: 0 },
  { id: cid("podcast@nodepression.com"), name: "No Depression Podcast", email: "podcast@nodepression.com", outlet: "No Depression", type: "podcaster", genre: "Americana, Roots", region: "US", beat: "Americana, Roots, Reviews", bio: "Podcast from the premier Americana and roots music journal.", website: "https://nodepression.com", verified: false, articleCount: 0 },
  { id: cid("show@rootsmusicreport.com"), name: "Roots Music Report Pod", email: "show@rootsmusicreport.com", outlet: "Roots Music Report", type: "podcaster", genre: "Americana, Roots", region: "US", beat: "Roots Music Charts, Features", bio: "Podcast from the roots music chart and reporting service.", website: "https://rootsmusicreport.com", verified: false, articleCount: 0 },
  { id: cid("podcast@ninebullets.net"), name: "9 Bullets Podcast", email: "podcast@ninebullets.net", outlet: "9 Bullets", type: "podcaster", genre: "Americana, Alt-Country", region: "US", beat: "Alt-Country, Americana Podcast", bio: "Podcast companion to the Nine Bullets Americana and alt-country blog.", website: "https://ninebullets.net", verified: false, articleCount: 0 },
  { id: cid("podcast@americansongwriter.com"), name: "American Songwriter Podcast", email: "podcast@americansongwriter.com", outlet: "American Songwriter", type: "podcaster", genre: "Americana, Singer-Songwriter", region: "US", beat: "Songwriting, Americana, Interviews", bio: "Podcast from American Songwriter magazine featuring artist interviews and songwriting craft.", website: "https://americansongwriter.com", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // CLASSICAL (68 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Classical Blogs (25) —
  { id: cid("editor@bachtrack.com"), name: "Bachtrack Editorial", email: "editor@bachtrack.com", outlet: "Bachtrack", type: "blog", genre: "Classical", region: "UK", beat: "Classical Reviews, Concert Listings", bio: "Leading classical music review and concert listing site worldwide.", website: "https://bachtrack.com", verified: false, articleCount: 0 },
  { id: cid("editor@slippedisc.com"), name: "Slippedisc", email: "editor@slippedisc.com", outlet: "Slippedisc", type: "blog", genre: "Classical", region: "UK", beat: "Classical Music News, Industry", bio: "Influential classical music news blog by Norman Lebrecht.", website: "https://slippedisc.com", verified: false, articleCount: 0 },
  { id: cid("editor@theviolinchannel.com"), name: "The Violin Channel", email: "editor@theviolinchannel.com", outlet: "The Violin Channel", type: "blog", genre: "Classical", region: "US", beat: "Strings, Classical News, Competitions", bio: "Classical music platform focused on string instruments, competitions, and news.", website: "https://theviolinchannel.com", verified: false, articleCount: 0 },
  { id: cid("editor@operawire.com"), name: "Opera Wire", email: "editor@operawire.com", outlet: "Opera Wire", type: "blog", genre: "Classical, Opera", region: "US", beat: "Opera News, Reviews, Premieres", bio: "Online publication dedicated to opera news, reviews, and premieres.", website: "https://operawire.com", verified: false, articleCount: 0 },
  { id: cid("editor@interlude.hk"), name: "Interlude", email: "editor@interlude.hk", outlet: "Interlude", type: "blog", genre: "Classical", region: "International", beat: "Classical Music, Education, Features", bio: "Classical music platform with educational content and features.", website: "https://interlude.hk", verified: false, articleCount: 0 },
  { id: cid("editor@ludwigvan.com"), name: "Ludwig Van", email: "editor@ludwigvan.com", outlet: "Ludwig Van", type: "blog", genre: "Classical", region: "Canada", beat: "Classical Music News, Canadian Scene", bio: "Canadian classical music news and commentary platform.", website: "https://ludwigvan.com", verified: false, articleCount: 0 },
  { id: cid("editor@sfcv.org"), name: "SF Classical Voice", email: "editor@sfcv.org", outlet: "San Francisco Classical Voice", type: "blog", genre: "Classical", region: "US - San Francisco, CA", beat: "Bay Area Classical, Reviews", bio: "San Francisco Bay Area classical music review and news site.", website: "https://sfcv.org", verified: false, articleCount: 0 },
  { id: cid("editor@crosseyedpianist.com"), name: "The Cross-Eyed Pianist", email: "editor@crosseyedpianist.com", outlet: "The Cross-Eyed Pianist", type: "blog", genre: "Classical", region: "UK", beat: "Piano, Classical Reviews", bio: "Blog focused on piano and classical music reviews and features.", website: "https://crosseyedpianist.com", verified: false, articleCount: 0 },
  { id: cid("editor@prestomusic.com"), name: "Presto Music Blog", email: "editor@prestomusic.com", outlet: "Presto Music", type: "blog", genre: "Classical", region: "UK", beat: "Classical Reviews, New Recordings", bio: "Classical music retailer's editorial blog with reviews and features.", website: "https://prestomusic.com", verified: false, articleCount: 0 },
  { id: cid("editor@stringsmagazine.com"), name: "Strings Magazine", email: "editor@stringsmagazine.com", outlet: "Strings Magazine", type: "blog", genre: "Classical", region: "US", beat: "String Instruments, Classical Music", bio: "Magazine dedicated to string players and classical music.", website: "https://stringsmagazine.com", verified: false, articleCount: 0 },
  { id: cid("editor@operanews.com"), name: "Opera News", email: "editor@operanews.com", outlet: "Opera News", type: "blog", genre: "Classical, Opera", region: "US", beat: "Opera Reviews, Features", bio: "Official publication of the Metropolitan Opera Guild covering opera worldwide.", website: "https://operanews.com", verified: false, articleCount: 0 },
  { id: cid("editor@classicstoday.com"), name: "Classics Today", email: "editor@classicstoday.com", outlet: "Classics Today", type: "blog", genre: "Classical", region: "US", beat: "Classical Recording Reviews", bio: "Classical recording review site with detailed ratings and assessments.", website: "https://classicstoday.com", verified: false, articleCount: 0 },
  { id: cid("editor@musicweb-international.com"), name: "MusicWeb International", email: "editor@musicweb-international.com", outlet: "MusicWeb International", type: "blog", genre: "Classical", region: "UK", beat: "Classical Reviews, Recordings", bio: "Comprehensive classical music review site with extensive recording reviews.", website: "https://musicweb-international.com", verified: false, articleCount: 0 },
  { id: cid("editor@seenandheard-international.com"), name: "Seen and Heard International", email: "editor@seenandheard-international.com", outlet: "Seen and Heard International", type: "blog", genre: "Classical, Opera", region: "UK", beat: "Classical Concert Reviews, Opera", bio: "International classical concert and opera review publication.", website: "https://seenandheard-international.com", verified: false, articleCount: 0 },
  { id: cid("classical@theartsdesk.com"), name: "The Arts Desk Classical", email: "classical@theartsdesk.com", outlet: "The Arts Desk", type: "blog", genre: "Classical", region: "UK", beat: "Classical Reviews, Arts Coverage", bio: "The Arts Desk's classical music section with reviews and features.", website: "https://theartsdesk.com", verified: false, articleCount: 0 },
  { id: cid("editor@earlymusicamerica.org"), name: "Early Music America", email: "editor@earlymusicamerica.org", outlet: "Early Music America", type: "blog", genre: "Classical, Early Music", region: "US", beat: "Early Music, Baroque, Medieval", bio: "Organization and publication dedicated to early music in America.", website: "https://earlymusicamerica.org", verified: false, articleCount: 0 },
  { id: cid("editor@chamber-music.org"), name: "Chamber Music America", email: "editor@chamber-music.org", outlet: "Chamber Music America", type: "blog", genre: "Classical, Chamber Music", region: "US", beat: "Chamber Music, Ensembles", bio: "National service organization for chamber music with editorial content.", website: "https://chamber-music.org", verified: false, articleCount: 0 },
  { id: cid("editor@classicalmusicmagazine.org"), name: "Classical Music Magazine", email: "editor@classicalmusicmagazine.org", outlet: "Classical Music", type: "blog", genre: "Classical", region: "UK", beat: "Classical Music News, Reviews", bio: "UK classical music magazine with news and reviews.", website: "https://classicalmusicmagazine.org", verified: false, articleCount: 0 },
  { id: cid("editor@rhinegold.co.uk"), name: "Rhinegold", email: "editor@rhinegold.co.uk", outlet: "Rhinegold", type: "blog", genre: "Classical", region: "UK", beat: "Classical Publishing, Music Education", bio: "UK classical music publisher with magazines and educational content.", website: "https://rhinegold.co.uk", verified: false, articleCount: 0 },
  { id: cid("editor@operatoday.com"), name: "Opera Today", email: "editor@operatoday.com", outlet: "Opera Today", type: "blog", genre: "Classical, Opera", region: "US", beat: "Opera Reviews, Features", bio: "Online opera review and feature publication.", website: "https://operatoday.com", verified: false, articleCount: 0 },
  { id: cid("editor@schmopera.com"), name: "Schmopera", email: "editor@schmopera.com", outlet: "Schmopera", type: "blog", genre: "Classical, Opera", region: "Canada", beat: "Opera, Emerging Singers, Reviews", bio: "Independent opera blog covering productions, emerging singers, and industry issues.", website: "https://schmopera.com", verified: false, articleCount: 0 },
  { id: cid("editor@oberonsgrove.com"), name: "Oberon's Grove", email: "editor@oberonsgrove.com", outlet: "Oberon's Grove", type: "blog", genre: "Classical, Opera", region: "US", beat: "Opera, Classical Reviews", bio: "Classical music and opera review blog.", website: "https://oberonsgrove.com", verified: false, articleCount: 0 },
  { id: cid("editor@operavore.com"), name: "Operavore", email: "editor@operavore.com", outlet: "Operavore", type: "blog", genre: "Classical, Opera", region: "US", beat: "Opera News, Streaming, Reviews", bio: "Opera blog covering news, streaming, and performance reviews.", website: "https://operavore.com", verified: false, articleCount: 0 },
  { id: cid("editor@parterre.com"), name: "Parterre Box", email: "editor@parterre.com", outlet: "Parterre Box", type: "blog", genre: "Classical, Opera", region: "US", beat: "Opera Commentary, Reviews", bio: "Long-running opera blog with commentary, reviews, and discussion.", website: "https://parterre.com", verified: false, articleCount: 0 },
  { id: cid("editor@classicalvoiceamerica.org"), name: "Classical Voice North America", email: "editor@classicalvoiceamerica.org", outlet: "Classical Voice North America", type: "blog", genre: "Classical", region: "US", beat: "Classical Music Reviews, North American Scene", bio: "North American classical music review and news aggregator.", website: "https://classicalvoiceamerica.org", verified: false, articleCount: 0 },

  // — Classical Radio (15) —
  { id: cid("music@wqxr.org"), name: "WQXR New York", email: "music@wqxr.org", outlet: "WQXR 105.9", type: "radio", genre: "Classical", region: "US - New York, NY", beat: "Classical Radio", bio: "New York's premier classical music radio station.", website: "https://wqxr.org", verified: false, articleCount: 0 },
  { id: cid("music@kusc.org"), name: "KUSC Los Angeles", email: "music@kusc.org", outlet: "KUSC 91.5", type: "radio", genre: "Classical", region: "US - Los Angeles, CA", beat: "Classical Radio", bio: "Southern California's classical music radio station.", website: "https://kusc.org", verified: false, articleCount: 0 },
  { id: cid("music@wfmt.com"), name: "WFMT Chicago", email: "music@wfmt.com", outlet: "WFMT 98.7", type: "radio", genre: "Classical", region: "US - Chicago, IL", beat: "Classical Radio, Fine Arts", bio: "Chicago's fine arts and classical music radio station.", website: "https://wfmt.com", verified: false, articleCount: 0 },
  { id: cid("music@king.org"), name: "KING FM Seattle", email: "music@king.org", outlet: "KING FM 98.1", type: "radio", genre: "Classical", region: "US - Seattle, WA", beat: "Classical Radio", bio: "Seattle's classical music radio station.", website: "https://king.org", verified: false, articleCount: 0 },
  { id: cid("music@classicalmpr.org"), name: "Classical MPR Minnesota", email: "music@classicalmpr.org", outlet: "Classical MPR", type: "radio", genre: "Classical", region: "US - Minnesota", beat: "Classical Radio", bio: "Minnesota Public Radio's classical music service.", website: "https://classicalmpr.org", verified: false, articleCount: 0 },
  { id: cid("music@wdav.org"), name: "WDAV Davidson", email: "music@wdav.org", outlet: "WDAV 89.9", type: "radio", genre: "Classical", region: "US - Davidson, NC", beat: "Classical Radio", bio: "Classical music radio from Davidson College in North Carolina.", website: "https://wdav.org", verified: false, articleCount: 0 },
  { id: cid("classical@weta.org"), name: "WETA Classical DC", email: "classical@weta.org", outlet: "WETA Classical", type: "radio", genre: "Classical", region: "US - Washington, DC", beat: "Classical Radio", bio: "Washington DC classical music radio station.", website: "https://weta.org", verified: false, articleCount: 0 },
  { id: cid("music@wwfm.org"), name: "WWFM New Jersey", email: "music@wwfm.org", outlet: "WWFM The Classical Network", type: "radio", genre: "Classical", region: "US - New Jersey", beat: "Classical Radio", bio: "New Jersey's classical music radio network.", website: "https://wwfm.org", verified: false, articleCount: 0 },
  { id: cid("music@wguc.org"), name: "WGUC Cincinnati", email: "music@wguc.org", outlet: "WGUC 90.9", type: "radio", genre: "Classical", region: "US - Cincinnati, OH", beat: "Classical Radio", bio: "Cincinnati's classical music public radio station.", website: "https://wguc.org", verified: false, articleCount: 0 },
  { id: cid("music@wrr101.com"), name: "WRR Classical Dallas", email: "music@wrr101.com", outlet: "WRR 101.1", type: "radio", genre: "Classical", region: "US - Dallas, TX", beat: "Classical Radio", bio: "Dallas classical music radio station, one of the oldest in the US.", website: "https://wrr101.com", verified: false, articleCount: 0 },
  { id: cid("music@wcrb.org"), name: "WCRB Boston", email: "music@wcrb.org", outlet: "WCRB 99.5", type: "radio", genre: "Classical", region: "US - Boston, MA", beat: "Classical Radio", bio: "Boston's classical music radio station from WGBH.", website: "https://wcrb.org", verified: false, articleCount: 0 },
  { id: cid("music@theclassicalstation.org"), name: "WCPE The Classical Station", email: "music@theclassicalstation.org", outlet: "WCPE", type: "radio", genre: "Classical", region: "US - Raleigh, NC", beat: "Classical Radio", bio: "24/7 classical music radio station from Wake County, North Carolina.", website: "https://theclassicalstation.org", verified: false, articleCount: 0 },
  { id: cid("music2@classicalmpr.org"), name: "KSJN Minnesota", email: "music2@classicalmpr.org", outlet: "KSJN 99.5", type: "radio", genre: "Classical", region: "US - Minnesota", beat: "Classical Radio", bio: "Minnesota Public Radio classical music station.", website: "https://classicalmpr.org", verified: false, articleCount: 0 },
  { id: cid("music@wbjc.com"), name: "WBJC Baltimore", email: "music@wbjc.com", outlet: "WBJC 91.5", type: "radio", genre: "Classical", region: "US - Baltimore, MD", beat: "Classical Radio", bio: "Baltimore's classical music radio station.", website: "https://wbjc.com", verified: false, articleCount: 0 },
  { id: cid("music@capecodfm.org"), name: "WFCC Cape Cod", email: "music@capecodfm.org", outlet: "WFCC 107.5", type: "radio", genre: "Classical", region: "US - Cape Cod, MA", beat: "Classical Radio", bio: "Cape Cod's classical music radio station.", website: "https://capecodfm.org", verified: false, articleCount: 0 },

  // — Classical Curators (18) —
  { id: cid("curator@classicalnewreleases.com"), name: "Classical New Releases", email: "curator@classicalnewreleases.com", outlet: "Classical New Releases", type: "curator", genre: "Classical", region: "US", beat: "New Classical Recordings", bio: "Curator of playlists featuring new classical music recordings.", website: "https://classicalnewreleases.com", verified: false, articleCount: 0 },
  { id: cid("curator@classicalfocus.co"), name: "Classical Focus", email: "curator@classicalfocus.co", outlet: "Classical Focus", type: "curator", genre: "Classical", region: "US", beat: "Focus Classical Playlists", bio: "Curator of classical music playlists for focus and concentration.", website: "https://classicalfocus.co", verified: false, articleCount: 0 },
  { id: cid("curator@peacefulpiano.co"), name: "Peaceful Piano", email: "curator@peacefulpiano.co", outlet: "Peaceful Piano", type: "curator", genre: "Classical", region: "US", beat: "Peaceful Piano Playlists", bio: "Curator of peaceful and calming piano music playlists.", website: "https://peacefulpiano.co", verified: false, articleCount: 0 },
  { id: cid("curator@classicalessentials.co"), name: "Classical Essentials", email: "curator@classicalessentials.co", outlet: "Classical Essentials", type: "curator", genre: "Classical", region: "US", beat: "Essential Classical Works", bio: "Curator of essential classical music playlists spanning all eras.", website: "https://classicalessentials.co", verified: false, articleCount: 0 },
  { id: cid("curator@cellomoods.co"), name: "Cello Moods", email: "curator@cellomoods.co", outlet: "Cello Moods", type: "curator", genre: "Classical", region: "US", beat: "Cello Music Playlists", bio: "Curator of cello-focused classical music playlists.", website: "https://cellomoods.co", verified: false, articleCount: 0 },
  { id: cid("curator@baroqueplaylist.co"), name: "Baroque Masterpieces", email: "curator@baroqueplaylist.co", outlet: "Baroque Masterpieces", type: "curator", genre: "Classical, Baroque", region: "US", beat: "Baroque Music Playlists", bio: "Curator of baroque masterpiece playlists.", website: "https://baroqueplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@operanowplaylist.co"), name: "Opera Now Playlist", email: "curator@operanowplaylist.co", outlet: "Opera Now", type: "curator", genre: "Classical, Opera", region: "US", beat: "Opera Playlists", bio: "Curator of opera playlists featuring arias and full recordings.", website: "https://operanowplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@filmscoreplaylist.co"), name: "Film Score Focus", email: "curator@filmscoreplaylist.co", outlet: "Film Score Focus", type: "curator", genre: "Classical, Film Score", region: "US", beat: "Film Score Playlists", bio: "Curator of film score and orchestral soundtrack playlists.", website: "https://filmscoreplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@classicalrising.co"), name: "Classical Rising", email: "curator@classicalrising.co", outlet: "Classical Rising", type: "curator", genre: "Classical", region: "US", beat: "Emerging Classical Artists", bio: "Curator spotlighting emerging classical musicians and new recordings.", website: "https://classicalrising.co", verified: false, articleCount: 0 },
  { id: cid("curator@moviesoundtracksplaylist.co"), name: "Movie Soundtracks Playlist", email: "curator@moviesoundtracksplaylist.co", outlet: "Movie Soundtracks", type: "curator", genre: "Classical, Soundtrack", region: "US", beat: "Movie Soundtrack Playlists", bio: "Curator of movie soundtrack and orchestral playlists.", website: "https://moviesoundtracksplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@classicalsleep.co"), name: "Classical Sleep", email: "curator@classicalsleep.co", outlet: "Classical Sleep", type: "curator", genre: "Classical", region: "US", beat: "Sleep Classical Playlists", bio: "Curator of classical music playlists for sleep and relaxation.", website: "https://classicalsleep.co", verified: false, articleCount: 0 },
  { id: cid("curator@classicalmorning.co"), name: "Classical Morning", email: "curator@classicalmorning.co", outlet: "Classical Morning", type: "curator", genre: "Classical", region: "US", beat: "Morning Classical Playlists", bio: "Curator of classical music playlists for morning routines.", website: "https://classicalmorning.co", verified: false, articleCount: 0 },
  { id: cid("curator@studyclassical.co"), name: "Study Classical", email: "curator@studyclassical.co", outlet: "Study Classical", type: "curator", genre: "Classical", region: "US", beat: "Study Classical Playlists", bio: "Curator of classical music playlists for studying.", website: "https://studyclassical.co", verified: false, articleCount: 0 },
  { id: cid("curator@classicalguitarplaylist.co"), name: "Classical Guitar Playlist", email: "curator@classicalguitarplaylist.co", outlet: "Classical Guitar", type: "curator", genre: "Classical", region: "US", beat: "Classical Guitar Playlists", bio: "Curator of classical guitar playlists.", website: "https://classicalguitarplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@symphonyselection.co"), name: "Symphony Selection", email: "curator@symphonyselection.co", outlet: "Symphony Selection", type: "curator", genre: "Classical", region: "US", beat: "Symphony Playlists", bio: "Curator of symphony and orchestral playlists.", website: "https://symphonyselection.co", verified: false, articleCount: 0 },
  { id: cid("curator@choralclassics.co"), name: "Choral Classics", email: "curator@choralclassics.co", outlet: "Choral Classics", type: "curator", genre: "Classical, Choral", region: "US", beat: "Choral Music Playlists", bio: "Curator of choral and vocal ensemble classical playlists.", website: "https://choralclassics.co", verified: false, articleCount: 0 },
  { id: cid("curator@contemporaryclassicalplaylist.co"), name: "Contemporary Classical", email: "curator@contemporaryclassicalplaylist.co", outlet: "Contemporary Classical", type: "curator", genre: "Classical, Contemporary", region: "US", beat: "Contemporary Classical Playlists", bio: "Curator of contemporary and modern classical music playlists.", website: "https://contemporaryclassicalplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@neoclassicalplaylist.co"), name: "Neo-Classical", email: "curator@neoclassicalplaylist.co", outlet: "Neo-Classical", type: "curator", genre: "Classical, Neo-Classical", region: "US", beat: "Neo-Classical Playlists", bio: "Curator of neo-classical playlists blending classical with modern elements.", website: "https://neoclassicalplaylist.co", verified: false, articleCount: 0 },

  // — Classical Podcasters (10) —
  { id: cid("show@stickynotespodcast.com"), name: "Sticky Notes Podcast", email: "show@stickynotespodcast.com", outlet: "Sticky Notes", type: "podcaster", genre: "Classical", region: "US", beat: "Classical Music Education, Reviews", bio: "Podcast making classical music accessible with engaging episode guides.", website: "https://stickynotespodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@classicalbreakdown.com"), name: "Classical Breakdown", email: "show@classicalbreakdown.com", outlet: "Classical Breakdown", type: "podcaster", genre: "Classical", region: "US", beat: "Classical Music Explained", bio: "Podcast breaking down classical music for new and seasoned listeners.", website: "https://classicalbreakdown.com", verified: false, articleCount: 0 },
  { id: cid("show@classicalclassroom.com"), name: "Classical Classroom", email: "show@classicalclassroom.com", outlet: "Classical Classroom", type: "podcaster", genre: "Classical", region: "US", beat: "Classical Music Education", bio: "Educational podcast exploring classical music in an accessible format.", website: "https://classicalclassroom.com", verified: false, articleCount: 0 },
  { id: cid("show@livingtheclassicallife.com"), name: "Living the Classical Life", email: "show@livingtheclassicallife.com", outlet: "Living the Classical Life", type: "podcaster", genre: "Classical", region: "US", beat: "Classical Musician Interviews", bio: "Podcast featuring interviews with classical musicians about their lives and careers.", website: "https://livingtheclassicallife.com", verified: false, articleCount: 0 },
  { id: cid("show@meetthecomposer.com"), name: "Meet the Composer", email: "show@meetthecomposer.com", outlet: "Meet the Composer", type: "podcaster", genre: "Classical", region: "US", beat: "Contemporary Composers, Interviews", bio: "Podcast introducing listeners to contemporary classical composers.", website: "https://meetthecomposer.com", verified: false, articleCount: 0 },
  { id: cid("show@scorepodcast.com"), name: "Score Podcast", email: "show@scorepodcast.com", outlet: "Score", type: "podcaster", genre: "Classical, Film Score", region: "US", beat: "Film Scores, Orchestral Music", bio: "Podcast exploring film scores and orchestral music in cinema.", website: "https://scorepodcast.com", verified: false, articleCount: 0 },
  { id: cid("podcast@classicfm.com"), name: "Classic FM Podcast", email: "podcast@classicfm.com", outlet: "Classic FM", type: "podcaster", genre: "Classical", region: "UK", beat: "Classical Music, Popular Classics", bio: "Podcast from UK's Classic FM radio station.", website: "https://classicfm.com", verified: false, articleCount: 0 },
  { id: cid("show@ariacode.com"), name: "Aria Code Podcast", email: "show@ariacode.com", outlet: "Aria Code", type: "podcaster", genre: "Classical, Opera", region: "US", beat: "Opera Arias, Deep Dives", bio: "WQXR and Metropolitan Opera podcast exploring the world's greatest arias.", website: "https://ariacode.com", verified: false, articleCount: 0 },
  { id: cid("show@musicmatterspod.com"), name: "Music Matters Podcast", email: "show@musicmatterspod.com", outlet: "Music Matters", type: "podcaster", genre: "Classical", region: "UK", beat: "Classical Music Interviews", bio: "Podcast with in-depth interviews with classical musicians and conductors.", website: "https://musicmatterspod.com", verified: false, articleCount: 0 },
  { id: cid("show@classicalmusicpod.com"), name: "The Classical Music Podcast", email: "show@classicalmusicpod.com", outlet: "The Classical Music Podcast", type: "podcaster", genre: "Classical", region: "US", beat: "Classical Music Discovery", bio: "Podcast helping listeners discover and appreciate classical music.", website: "https://classicalmusicpod.com", verified: false, articleCount: 0 },

];
