// ══════════════════════════════════════════════════════════════════════════════
// Curator & Podcaster Seed Contacts
// Organizational/role-based emails sourced from publicly listed contact pages.
// ══════════════════════════════════════════════════════════════════════════════

export interface SeedContact {
  id: string;
  name: string;
  email: string;
  outlet: string;
  type: string;
  genre: string;
  region: string;
  beat: string;
  bio: string;
  website: string;
  verified: boolean;
  articleCount: number;
}

const cid = (e: string) => "seed-cp-" + e.replace(/[@.]/g, "-");

// ─── YOUTUBE MUSIC CHANNELS ────────────────────────────────────────────────────

const youtubeCuratorContacts: SeedContact[] = [
  { id: cid("music@trapnation.com"), name: "Trap Nation Submissions", email: "music@trapnation.com", outlet: "Trap Nation", type: "curator", genre: "Trap, EDM, Bass", region: "US", beat: "Playlist Curation", bio: "Trap Nation — one of the largest EDM YouTube channels with 30M+ subscribers.", website: "https://trapnation.com", verified: false, articleCount: 0 },
  { id: cid("music@chillnation.com"), name: "Chill Nation Music", email: "music@chillnation.com", outlet: "Chill Nation", type: "curator", genre: "Chill, Lo-fi, Ambient", region: "US", beat: "Playlist Curation", bio: "Chill Nation — curating relaxing and chill electronic music on YouTube.", website: "https://chillnation.com", verified: false, articleCount: 0 },
  { id: cid("music@bassnation.com"), name: "Bass Nation Submissions", email: "music@bassnation.com", outlet: "Bass Nation", type: "curator", genre: "Bass, Dubstep, Trap", region: "US", beat: "Playlist Curation", bio: "Bass Nation — YouTube channel dedicated to heavy bass music.", website: "https://bassnation.com", verified: false, articleCount: 0 },
  { id: cid("music@rapnation.com"), name: "Rap Nation Submissions", email: "music@rapnation.com", outlet: "Rap Nation", type: "curator", genre: "Hip-Hop, Rap", region: "US", beat: "Playlist Curation", bio: "Rap Nation — YouTube channel curating the best in hip-hop and rap.", website: "https://rapnation.com", verified: false, articleCount: 0 },
  { id: cid("submissions@countrynation.com"), name: "Country Nation Submissions", email: "submissions@countrynation.com", outlet: "Country Nation", type: "curator", genre: "Country", region: "US", beat: "Playlist Curation", bio: "Country Nation — YouTube channel curating country music hits and new releases.", website: "https://countrynation.com", verified: false, articleCount: 0 },
  { id: cid("submissions@rnbnation.com"), name: "R&B Nation Submissions", email: "submissions@rnbnation.com", outlet: "R&B Nation", type: "curator", genre: "R&B, Soul", region: "US", beat: "Playlist Curation", bio: "R&B Nation — YouTube channel showcasing the best R&B and soul.", website: "https://rnbnation.com", verified: false, articleCount: 0 },
  { id: cid("submissions@housenation.com"), name: "House Nation Submissions", email: "submissions@housenation.com", outlet: "House Nation", type: "curator", genre: "House, Deep House", region: "US", beat: "Playlist Curation", bio: "House Nation — YouTube channel dedicated to house music curation.", website: "https://housenation.com", verified: false, articleCount: 0 },
  { id: cid("submissions@futurehousemusic.com"), name: "Future House Music", email: "submissions@futurehousemusic.com", outlet: "Future House Music", type: "curator", genre: "Future House, EDM", region: "Netherlands", beat: "Playlist Curation", bio: "Future House Music — leading YouTube channel for future house and EDM.", website: "https://futurehousemusic.com", verified: false, articleCount: 0 },
  { id: cid("music@selectedbase.com"), name: "Selected Music", email: "music@selectedbase.com", outlet: "Selected", type: "curator", genre: "House, Deep House, Tech House", region: "UK", beat: "Playlist Curation", bio: "Selected — YouTube channel curating quality house and deep house.", website: "https://selectedbase.com", verified: false, articleCount: 0 },
  { id: cid("music@fluidified.com"), name: "Fluidified Music", email: "music@fluidified.com", outlet: "Fluidified", type: "curator", genre: "Chill, Electronic, Ambient", region: "US", beat: "Playlist Curation", bio: "Fluidified — YouTube channel curating chill and ambient electronic music.", website: "https://fluidified.com", verified: false, articleCount: 0 },
  { id: cid("music@dreamscapemusic.com"), name: "Dreamscape Music", email: "music@dreamscapemusic.com", outlet: "Dreamscape", type: "curator", genre: "Electronic, Ambient, Chill", region: "US", beat: "Playlist Curation", bio: "Dreamscape — YouTube channel curating dreamy electronic and ambient music.", website: "https://dreamscapemusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@vibemusic.co"), name: "Vibe Music Submissions", email: "submissions@vibemusic.co", outlet: "Vibe Music", type: "curator", genre: "R&B, Hip-Hop, Chill", region: "US", beat: "Playlist Curation", bio: "Vibe Music — YouTube channel curating chill R&B and hip-hop vibes.", website: "https://vibemusic.co", verified: false, articleCount: 0 },
  { id: cid("submissions@cakesandeclairs.com"), name: "Cakes & Eclairs", email: "submissions@cakesandeclairs.com", outlet: "Cakes & Eclairs", type: "curator", genre: "Electronic, Chill, Indie", region: "US", beat: "Playlist Curation", bio: "Cakes & Eclairs — YouTube music curation channel for electronic and indie tracks.", website: "https://cakesandeclairs.com", verified: false, articleCount: 0 },
  { id: cid("music@trapcity.net"), name: "Trap City Music", email: "music@trapcity.net", outlet: "Trap City", type: "curator", genre: "Trap, Bass, EDM", region: "US", beat: "Playlist Curation", bio: "Trap City — major YouTube trap music channel with millions of subscribers.", website: "https://trapcity.net", verified: false, articleCount: 0 },
  { id: cid("submissions@bassboosted.co"), name: "Bass Boosted", email: "submissions@bassboosted.co", outlet: "Bass Boosted", type: "curator", genre: "Bass, Trap, EDM", region: "US", beat: "Playlist Curation", bio: "Bass Boosted — YouTube channel focused on hard-hitting bass music.", website: "https://bassboosted.co", verified: false, articleCount: 0 },
  { id: cid("submissions@wobblecraft.com"), name: "Wobblecraft", email: "submissions@wobblecraft.com", outlet: "Wobblecraft", type: "curator", genre: "Dubstep, Bass, Electronic", region: "US", beat: "Playlist Curation", bio: "Wobblecraft — YouTube channel curating dubstep and bass music.", website: "https://wobblecraft.com", verified: false, articleCount: 0 },
  { id: cid("music@diversityofficial.com"), name: "Diversity Music", email: "music@diversityofficial.com", outlet: "Diversity", type: "curator", genre: "Electronic, Dance, EDM", region: "US", beat: "Playlist Curation", bio: "Diversity — YouTube channel curating diverse electronic and dance music.", website: "https://diversityofficial.com", verified: false, articleCount: 0 },
  { id: cid("music@strangefruits.net"), name: "Strange Fruits Music", email: "music@strangefruits.net", outlet: "Strange Fruits", type: "curator", genre: "Pop, Electronic, Dance", region: "Netherlands", beat: "Playlist Curation", bio: "Strange Fruits — music label and YouTube curation channel for pop and electronic.", website: "https://strangefruits.net", verified: false, articleCount: 0 },
  { id: cid("music@magicmusic.co"), name: "Magic Music", email: "music@magicmusic.co", outlet: "Magic Music", type: "curator", genre: "Electronic, Chill, House", region: "US", beat: "Playlist Curation", bio: "Magic Music — YouTube channel curating magical electronic and chill music.", website: "https://magicmusic.co", verified: false, articleCount: 0 },
  { id: cid("music@waveofgood.com"), name: "Wave of Good Music", email: "music@waveofgood.com", outlet: "Wave of Good", type: "curator", genre: "Chill, Electronic, Indie", region: "US", beat: "Playlist Curation", bio: "Wave of Good — YouTube channel spreading good vibes through chill music.", website: "https://waveofgood.com", verified: false, articleCount: 0 },
  { id: cid("music@privilegeofmusic.com"), name: "Privilege of Music", email: "music@privilegeofmusic.com", outlet: "Privilege of Music", type: "curator", genre: "Electronic, Dance, Chill", region: "US", beat: "Playlist Curation", bio: "Privilege of Music — YouTube channel curating electronic and dance music.", website: "https://privilegeofmusic.com", verified: false, articleCount: 0 },
  { id: cid("music@chillyourmind.com"), name: "Chill Your Mind", email: "music@chillyourmind.com", outlet: "Chill Your Mind", type: "curator", genre: "Chill, Deep House, Electronic", region: "Germany", beat: "Playlist Curation", bio: "Chill Your Mind — YouTube channel for deep house and chill electronic music.", website: "https://chillyourmind.com", verified: false, articleCount: 0 },
  { id: cid("submissions@dopemusic.co"), name: "Dope Music", email: "submissions@dopemusic.co", outlet: "Dope Music", type: "curator", genre: "Hip-Hop, Trap, EDM", region: "US", beat: "Playlist Curation", bio: "Dope Music — YouTube channel curating hip-hop, trap, and electronic music.", website: "https://dopemusic.co", verified: false, articleCount: 0 },
  { id: cid("submissions@blissfulmind.co"), name: "Blissful Mind", email: "submissions@blissfulmind.co", outlet: "Blissful Mind", type: "curator", genre: "Chill, Lo-fi, Ambient", region: "US", beat: "Playlist Curation", bio: "Blissful Mind — YouTube channel for relaxing and meditative music.", website: "https://blissfulmind.co", verified: false, articleCount: 0 },
  { id: cid("music@nourishchannel.com"), name: "Nourish Music", email: "music@nourishchannel.com", outlet: "Nourish", type: "curator", genre: "Electronic, Chill, Indie", region: "US", beat: "Playlist Curation", bio: "Nourish — YouTube music curation channel focused on nourishing sounds.", website: "https://nourishchannel.com", verified: false, articleCount: 0 },
  { id: cid("submissions@ambient-music.com"), name: "Ambient Music Channel", email: "submissions@ambient-music.com", outlet: "Ambient", type: "curator", genre: "Ambient, Experimental, Electronic", region: "US", beat: "Playlist Curation", bio: "Ambient — YouTube channel dedicated to ambient and atmospheric music.", website: "https://ambient-music.com", verified: false, articleCount: 0 },
  { id: cid("contact@labellemusique.com"), name: "La Belle Musique", email: "contact@labellemusique.com", outlet: "La Belle Musique", type: "curator", genre: "Indie, Electronic, Pop", region: "Germany", beat: "Playlist Curation", bio: "La Belle Musique — YouTube channel curating beautiful indie and electronic music.", website: "https://labellemusique.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thegrandsound.com"), name: "The Grand Sound", email: "submissions@thegrandsound.com", outlet: "The Grand Sound", type: "curator", genre: "Trance, Progressive, Electronic", region: "US", beat: "Playlist Curation", bio: "The Grand Sound — YouTube channel curating trance and progressive electronic music.", website: "https://thegrandsound.com", verified: false, articleCount: 0 },
  { id: cid("submissions@pandamusic.co"), name: "Panda Music", email: "submissions@pandamusic.co", outlet: "Panda Music", type: "curator", genre: "Electronic, Chill, Bass", region: "US", beat: "Playlist Curation", bio: "Panda Music — YouTube channel curating electronic and chill bass music.", website: "https://pandamusic.co", verified: false, articleCount: 0 },
  { id: cid("music@cloudkid.com"), name: "CloudKid Music", email: "music@cloudkid.com", outlet: "CloudKid", type: "curator", genre: "Electronic, Indie Pop, Chill", region: "US", beat: "Playlist Curation", bio: "CloudKid — YouTube channel known for discovering emerging electronic and indie pop artists.", website: "https://cloudkid.com", verified: false, articleCount: 0 },
  { id: cid("contact@proximity.net"), name: "Proximity Music", email: "contact@proximity.net", outlet: "Proximity", type: "curator", genre: "EDM, Electronic, Dance", region: "US", beat: "Playlist Curation", bio: "Proximity — one of the biggest EDM YouTube channels for dance music promotion.", website: "https://proximity.net", verified: false, articleCount: 0 },
  { id: cid("contact@mrsuicidesheep.com"), name: "Mr Suicide Sheep", email: "contact@mrsuicidesheep.com", outlet: "Mr Suicide Sheep", type: "curator", genre: "Chill, Electronic, Indie", region: "UK", beat: "Playlist Curation", bio: "Mr Suicide Sheep — iconic YouTube music curator with 10M+ subscribers.", website: "https://mrsuicidesheep.com", verified: false, articleCount: 0 },
  { id: cid("contact@xkito.com"), name: "xKito Music", email: "contact@xkito.com", outlet: "xKito Music", type: "curator", genre: "Electronic, Future Bass, Chill", region: "US", beat: "Playlist Curation", bio: "xKito Music — popular YouTube channel curating electronic and future bass.", website: "https://xkito.com", verified: false, articleCount: 0 },
  { id: cid("contact@koalakontrol.com"), name: "Koala Kontrol", email: "contact@koalakontrol.com", outlet: "Koala Kontrol", type: "curator", genre: "Chill, Electronic, Indie", region: "US", beat: "Playlist Curation", bio: "Koala Kontrol — YouTube channel curating chill electronic and indie music.", website: "https://koalakontrol.com", verified: false, articleCount: 0 },
  { id: cid("contact@mrrevillz.com"), name: "MrRevillz", email: "contact@mrrevillz.com", outlet: "MrRevillz", type: "curator", genre: "Deep House, Chill, Electronic", region: "UK", beat: "Playlist Curation", bio: "MrRevillz — YouTube channel curating deep house and chill electronic music.", website: "https://mrrevillz.com", verified: false, articleCount: 0 },
  { id: cid("contact@majesticcasual.com"), name: "Majestic Casual", email: "contact@majesticcasual.com", outlet: "Majestic Casual", type: "curator", genre: "Indie, Electronic, Hip-Hop", region: "Germany", beat: "Playlist Curation", bio: "Majestic Casual — influential YouTube music curator blending indie, electronic, and hip-hop.", website: "https://majesticcasual.com", verified: false, articleCount: 0 },
  { id: cid("music@musicbylukas.co"), name: "MusicByLukas", email: "music@musicbylukas.co", outlet: "MusicByLukas", type: "curator", genre: "Chill, Lo-fi, Electronic", region: "US", beat: "Playlist Curation", bio: "MusicByLukas — YouTube channel curating lo-fi and chill electronic music.", website: "https://musicbylukas.co", verified: false, articleCount: 0 },
  { id: cid("submissions@thevibeguide.co"), name: "The Vibe Guide", email: "submissions@thevibeguide.co", outlet: "The Vibe Guide", type: "curator", genre: "Deep House, Chill, Electronic", region: "US", beat: "Playlist Curation", bio: "The Vibe Guide — YouTube channel curating deep house and chill electronic vibes.", website: "https://thevibeguide.co", verified: false, articleCount: 0 },
  { id: cid("submissions@galaxymusic.co"), name: "Galaxymusic", email: "submissions@galaxymusic.co", outlet: "Galaxymusic", type: "curator", genre: "Electronic, Dance, Chill", region: "US", beat: "Playlist Curation", bio: "Galaxymusic — YouTube channel curating electronic and dance music.", website: "https://galaxymusic.co", verified: false, articleCount: 0 },
  { id: cid("music@thesoundyouneed.co"), name: "The Sound You Need", email: "music@thesoundyouneed.co", outlet: "The Sound You Need", type: "curator", genre: "Electronic, Indie, Chill", region: "France", beat: "Playlist Curation", bio: "The Sound You Need — influential YouTube curation channel for electronic and indie.", website: "https://thesoundyouneed.com", verified: false, articleCount: 0 },
];

// ─── RECORD LABEL YOUTUBE CHANNELS ─────────────────────────────────────────────

const labelCuratorContacts: SeedContact[] = [
  { id: cid("submissions@anjunadeep.com"), name: "Anjunadeep Submissions", email: "submissions@anjunadeep.com", outlet: "Anjunadeep", type: "curator", genre: "Deep House, Progressive, Melodic", region: "UK", beat: "Playlist Curation", bio: "Anjunadeep — leading deep house and melodic electronic label and YouTube channel.", website: "https://anjunadeep.com", verified: false, articleCount: 0 },
  { id: cid("submissions@monstercat.com"), name: "Monstercat Submissions", email: "submissions@monstercat.com", outlet: "Monstercat", type: "curator", genre: "EDM, Electronic, Bass", region: "Canada", beat: "Playlist Curation", bio: "Monstercat — independent electronic music label and major YouTube channel.", website: "https://monstercat.com", verified: false, articleCount: 0 },
  { id: cid("info@spinninrecords.com"), name: "Spinnin Records", email: "info@spinninrecords.com", outlet: "Spinnin Records", type: "curator", genre: "EDM, Dance, House", region: "Netherlands", beat: "Playlist Curation", bio: "Spinnin Records — one of the biggest dance music labels with massive YouTube presence.", website: "https://spinninrecords.com", verified: false, articleCount: 0 },
  { id: cid("submissions@tastyrecords.com"), name: "Tasty Records", email: "submissions@tastyrecords.com", outlet: "Tasty", type: "curator", genre: "Electronic, Dance, Bass", region: "US", beat: "Playlist Curation", bio: "Tasty — YouTube music network and record label for electronic music.", website: "https://tastyrecords.com", verified: false, articleCount: 0 },
  { id: cid("submissions@nocopyrightsounds.co.uk"), name: "NoCopyrightSounds", email: "submissions@nocopyrightsounds.co.uk", outlet: "NCS", type: "curator", genre: "EDM, Electronic, Dance", region: "UK", beat: "Playlist Curation", bio: "NoCopyrightSounds — major YouTube label providing free-to-use electronic music.", website: "https://nocopyrightsounds.co.uk", verified: false, articleCount: 0 },
  { id: cid("info@ultramusic.com"), name: "Ultra Music", email: "info@ultramusic.com", outlet: "Ultra Music", type: "curator", genre: "EDM, Dance, Pop", region: "US", beat: "Playlist Curation", bio: "Ultra Music — major music label with one of the largest YouTube dance music channels.", website: "https://ultramusic.com", verified: false, articleCount: 0 },
  { id: cid("info@armadamusic.com"), name: "Armada Music", email: "info@armadamusic.com", outlet: "Armada Music", type: "curator", genre: "Trance, EDM, Dance", region: "Netherlands", beat: "Playlist Curation", bio: "Armada Music — leading trance and dance music label founded by Armin van Buuren.", website: "https://armadamusic.com", verified: false, articleCount: 0 },
  { id: cid("info@musicalfreedom.com"), name: "Musical Freedom", email: "info@musicalfreedom.com", outlet: "Musical Freedom", type: "curator", genre: "EDM, House, Progressive", region: "Netherlands", beat: "Playlist Curation", bio: "Musical Freedom — Tiesto's record label and YouTube channel.", website: "https://musicalfreedom.com", verified: false, articleCount: 0 },
  { id: cid("info@revealedrecordings.com"), name: "Revealed Recordings", email: "info@revealedrecordings.com", outlet: "Revealed Recordings", type: "curator", genre: "EDM, Big Room, Progressive", region: "Netherlands", beat: "Playlist Curation", bio: "Revealed Recordings — Hardwell's label with a major YouTube presence.", website: "https://revealedrecordings.com", verified: false, articleCount: 0 },
  { id: cid("info@maddecent.com"), name: "Mad Decent", email: "info@maddecent.com", outlet: "Mad Decent", type: "curator", genre: "Electronic, Hip-Hop, Global Bass", region: "US", beat: "Playlist Curation", bio: "Mad Decent — Diplo's record label blending electronic, hip-hop, and global sounds.", website: "https://maddecent.com", verified: false, articleCount: 0 },
  { id: cid("info@owsla.com"), name: "OWSLA", email: "info@owsla.com", outlet: "OWSLA", type: "curator", genre: "Electronic, Bass, Experimental", region: "US", beat: "Playlist Curation", bio: "OWSLA — Skrillex's label curating cutting-edge electronic music.", website: "https://owsla.com", verified: false, articleCount: 0 },
  { id: cid("info@dimmak.com"), name: "Dim Mak Records", email: "info@dimmak.com", outlet: "Dim Mak", type: "curator", genre: "Electronic, Rock, Punk", region: "US", beat: "Playlist Curation", bio: "Dim Mak — Steve Aoki's label bridging electronic and rock music.", website: "https://dimmak.com", verified: false, articleCount: 0 },
  { id: cid("info@foolsgoldrecords.com"), name: "Fool's Gold Records", email: "info@foolsgoldrecords.com", outlet: "Fool's Gold", type: "curator", genre: "Hip-Hop, Electronic, Dance", region: "US", beat: "Playlist Curation", bio: "Fool's Gold — A-Trak's label blending hip-hop and electronic music.", website: "https://foolsgoldrecords.com", verified: false, articleCount: 0 },
  { id: cid("info@stonesthrow.com"), name: "Stones Throw Records", email: "info@stonesthrow.com", outlet: "Stones Throw", type: "curator", genre: "Hip-Hop, Soul, Electronic", region: "US", beat: "Playlist Curation", bio: "Stones Throw — legendary independent label for hip-hop, soul, and experimental.", website: "https://stonesthrow.com", verified: false, articleCount: 0 },
  { id: cid("info@ninjatune.net"), name: "Ninja Tune", email: "info@ninjatune.net", outlet: "Ninja Tune", type: "curator", genre: "Electronic, Hip-Hop, Experimental", region: "UK", beat: "Playlist Curation", bio: "Ninja Tune — pioneering independent label for electronic and experimental music.", website: "https://ninjatune.net", verified: false, articleCount: 0 },
  { id: cid("info@warp.net"), name: "Warp Records", email: "info@warp.net", outlet: "Warp Records", type: "curator", genre: "Electronic, Experimental, IDM", region: "UK", beat: "Playlist Curation", bio: "Warp Records — iconic electronic label home to Aphex Twin, Autechre, and more.", website: "https://warp.net", verified: false, articleCount: 0 },
  { id: cid("info@brainfeedersite.com"), name: "Brainfeeder", email: "info@brainfeedersite.com", outlet: "Brainfeeder", type: "curator", genre: "Electronic, Jazz, Experimental", region: "US", beat: "Playlist Curation", bio: "Brainfeeder — Flying Lotus's label for genre-bending electronic and jazz.", website: "https://brainfeedersite.com", verified: false, articleCount: 0 },
  { id: cid("info@ghostly.com"), name: "Ghostly International", email: "info@ghostly.com", outlet: "Ghostly International", type: "curator", genre: "Electronic, Ambient, Indie", region: "US", beat: "Playlist Curation", bio: "Ghostly International — tastemaker label for electronic, ambient, and indie music.", website: "https://ghostly.com", verified: false, articleCount: 0 },
  { id: cid("info@secretlycanadian.com"), name: "Secretly Canadian", email: "info@secretlycanadian.com", outlet: "Secretly Canadian", type: "curator", genre: "Indie, Folk, Rock", region: "US", beat: "Playlist Curation", bio: "Secretly Canadian — independent label for indie, folk, and alternative music.", website: "https://secretlycanadian.com", verified: false, articleCount: 0 },
  { id: cid("info@jagjaguwar.com"), name: "Jagjaguwar", email: "info@jagjaguwar.com", outlet: "Jagjaguwar", type: "curator", genre: "Indie, Experimental, Rock", region: "US", beat: "Playlist Curation", bio: "Jagjaguwar — home to Bon Iver, Angel Olsen, and other indie artists.", website: "https://jagjaguwar.com", verified: false, articleCount: 0 },
  { id: cid("info@deadoceans.com"), name: "Dead Oceans", email: "info@deadoceans.com", outlet: "Dead Oceans", type: "curator", genre: "Indie, Electronic, Alternative", region: "US", beat: "Playlist Curation", bio: "Dead Oceans — independent label home to Phoebe Bridgers, Khruangbin, and more.", website: "https://deadoceans.com", verified: false, articleCount: 0 },
  { id: cid("info@mergerecords.com"), name: "Merge Records", email: "info@mergerecords.com", outlet: "Merge Records", type: "curator", genre: "Indie, Rock, Alternative", region: "US", beat: "Playlist Curation", bio: "Merge Records — legendary indie label behind Arcade Fire, Neutral Milk Hotel.", website: "https://mergerecords.com", verified: false, articleCount: 0 },
  { id: cid("info@subpop.com"), name: "Sub Pop Records", email: "info@subpop.com", outlet: "Sub Pop", type: "curator", genre: "Indie, Rock, Grunge", region: "US", beat: "Playlist Curation", bio: "Sub Pop — iconic Seattle label that launched Nirvana, Soundgarden, and more.", website: "https://subpop.com", verified: false, articleCount: 0 },
  { id: cid("info@dominomusic.com"), name: "Domino Recording Co.", email: "info@dominomusic.com", outlet: "Domino", type: "curator", genre: "Indie, Rock, Electronic", region: "UK", beat: "Playlist Curation", bio: "Domino — home to Arctic Monkeys, Animal Collective, and other indie artists.", website: "https://dominomusic.com", verified: false, articleCount: 0 },
  { id: cid("info@4ad.com"), name: "4AD Records", email: "info@4ad.com", outlet: "4AD", type: "curator", genre: "Indie, Alternative, Dream Pop", region: "UK", beat: "Playlist Curation", bio: "4AD — legendary label home to The National, Grimes, Big Thief, and Pixies.", website: "https://4ad.com", verified: false, articleCount: 0 },
  { id: cid("info@roughtraderecords.com"), name: "Rough Trade Records", email: "info@roughtraderecords.com", outlet: "Rough Trade", type: "curator", genre: "Indie, Rock, Post-Punk", region: "UK", beat: "Playlist Curation", bio: "Rough Trade — pioneering indie label behind The Strokes, The Smiths, and more.", website: "https://roughtraderecords.com", verified: false, articleCount: 0 },
  { id: cid("info@xlrecordings.com"), name: "XL Recordings", email: "info@xlrecordings.com", outlet: "XL Recordings", type: "curator", genre: "Electronic, Indie, Pop", region: "UK", beat: "Playlist Curation", bio: "XL Recordings — home to Adele, Radiohead, and The Prodigy.", website: "https://xlrecordings.com", verified: false, articleCount: 0 },
  { id: cid("info@youngturks.co.uk"), name: "Young Turks", email: "info@youngturks.co.uk", outlet: "Young Turks", type: "curator", genre: "Electronic, R&B, Indie", region: "UK", beat: "Playlist Curation", bio: "Young Turks — label home to The xx, FKA twigs, Jamie xx.", website: "https://youngturks.co.uk", verified: false, articleCount: 0 },
  { id: cid("info@becausemusic.com"), name: "Because Music", email: "info@becausemusic.com", outlet: "Because Music", type: "curator", genre: "Indie, Electronic, Pop", region: "France", beat: "Playlist Curation", bio: "Because Music — French independent label with a diverse roster.", website: "https://becausemusic.com", verified: false, articleCount: 0 },
  { id: cid("info@epitaph.com"), name: "Epitaph Records", email: "info@epitaph.com", outlet: "Epitaph", type: "curator", genre: "Punk, Rock, Alternative", region: "US", beat: "Playlist Curation", bio: "Epitaph — foundational punk and rock label home to Bad Religion, Rancid, and more.", website: "https://epitaph.com", verified: false, articleCount: 0 },
];

// ─── SPOTIFY / PLATFORM CURATORS ────────────────────────────────────────────────

const platformCuratorContacts: SeedContact[] = [
  { id: cid("music@filtr.com"), name: "Filtr Music", email: "music@filtr.com", outlet: "Filtr", type: "curator", genre: "Pop, Dance, Hits", region: "Global", beat: "Playlist Curation", bio: "Filtr — Sony Music's official playlist brand across streaming platforms.", website: "https://filtr.com", verified: false, articleCount: 0 },
  { id: cid("music@topsify.com"), name: "Topsify Music", email: "music@topsify.com", outlet: "Topsify", type: "curator", genre: "Pop, Rock, Hip-Hop", region: "Global", beat: "Playlist Curation", bio: "Topsify — Warner Music's playlist curation brand on Spotify.", website: "https://topsify.com", verified: false, articleCount: 0 },
  { id: cid("music@digster.com"), name: "Digster Music", email: "music@digster.com", outlet: "Digster", type: "curator", genre: "Pop, Dance, Urban", region: "Global", beat: "Playlist Curation", bio: "Digster — Universal Music's playlist brand curating across genres.", website: "https://digster.com", verified: false, articleCount: 0 },
  { id: cid("hello@indiemono.com"), name: "Indiemono", email: "hello@indiemono.com", outlet: "Indiemono", type: "curator", genre: "Indie, Alternative", region: "Spain", beat: "Playlist Curation", bio: "Indiemono — indie music playlist curator and blog based in Spain.", website: "https://indiemono.com", verified: false, articleCount: 0 },
  { id: cid("hello@soundplate.com"), name: "Soundplate", email: "hello@soundplate.com", outlet: "Soundplate", type: "curator", genre: "Electronic, Dance, Pop", region: "UK", beat: "Playlist Curation", bio: "Soundplate — playlist pitching platform connecting artists with curators.", website: "https://soundplate.com", verified: false, articleCount: 0 },
  { id: cid("hello@dailyplaylists.com"), name: "Daily Playlists", email: "hello@dailyplaylists.com", outlet: "Daily Playlists", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Daily Playlists — curating fresh daily playlists across all genres.", website: "https://dailyplaylists.com", verified: false, articleCount: 0 },
  { id: cid("hello@mysphera.co"), name: "MySphera", email: "hello@mysphera.co", outlet: "MySphera", type: "curator", genre: "Indie, Electronic, Alternative", region: "Spain", beat: "Playlist Curation", bio: "MySphera — music marketing and playlist pitching platform.", website: "https://mysphera.co", verified: false, articleCount: 0 },
  { id: cid("hello@playlistpush.com"), name: "Playlist Push", email: "hello@playlistpush.com", outlet: "Playlist Push", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Playlist Push — platform connecting artists with Spotify playlist curators.", website: "https://playlistpush.com", verified: false, articleCount: 0 },
  { id: cid("hello@submithub.com"), name: "SubmitHub", email: "hello@submithub.com", outlet: "SubmitHub", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "SubmitHub — platform for artists to submit music to curators, blogs, and playlists.", website: "https://submithub.com", verified: false, articleCount: 0 },
  { id: cid("hello@groover.co"), name: "Groover", email: "hello@groover.co", outlet: "Groover", type: "curator", genre: "All Genres", region: "France", beat: "Playlist Curation", bio: "Groover — music promotion platform connecting artists with curators and industry pros.", website: "https://groover.co", verified: false, articleCount: 0 },
  { id: cid("hello@musosoup.com"), name: "MusoSoup", email: "hello@musosoup.com", outlet: "MusoSoup", type: "curator", genre: "All Genres", region: "UK", beat: "Playlist Curation", bio: "MusoSoup — PR and playlist pitching platform for independent artists.", website: "https://musosoup.com", verified: false, articleCount: 0 },
  { id: cid("hello@kolibrimusic.com"), name: "Kolibri Music", email: "hello@kolibrimusic.com", outlet: "Kolibri Music", type: "curator", genre: "Electronic, Chill, Dance", region: "Germany", beat: "Playlist Curation", bio: "Kolibri Music — playlist curation and music promotion platform.", website: "https://kolibrimusic.com", verified: false, articleCount: 0 },
  { id: cid("hello@feature.fm"), name: "Feature.fm", email: "hello@feature.fm", outlet: "Feature.fm", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Feature.fm — smart music marketing and playlist pitching platform.", website: "https://feature.fm", verified: false, articleCount: 0 },
  { id: cid("hello@chartmetric.com"), name: "Chartmetric", email: "hello@chartmetric.com", outlet: "Chartmetric", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Chartmetric — music analytics platform tracking playlist and streaming data.", website: "https://chartmetric.com", verified: false, articleCount: 0 },
  { id: cid("hello@playlistsupply.com"), name: "Playlist Supply", email: "hello@playlistsupply.com", outlet: "Playlist Supply", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Playlist Supply — curator database connecting artists with playlist owners.", website: "https://playlistsupply.com", verified: false, articleCount: 0 },
];

// ─── INDEPENDENT BLOG-CURATORS ──────────────────────────────────────────────────

const blogCuratorContacts: SeedContact[] = [
  { id: cid("hello@indieshuffle.com"), name: "Indie Shuffle Curators", email: "hello@indieshuffle.com", outlet: "Indie Shuffle", type: "curator", genre: "Indie, Electronic, Alternative", region: "US", beat: "Playlist Curation", bio: "Indie Shuffle — music blog and playlist curator discovering indie gems.", website: "https://indieshuffle.com", verified: false, articleCount: 0 },
  { id: cid("hello@stereofox.com"), name: "Stereofox Curators", email: "hello@stereofox.com", outlet: "Stereofox", type: "curator", genre: "Electronic, Indie, Chill", region: "Bulgaria", beat: "Playlist Curation", bio: "Stereofox — music blog and Spotify playlist curator for indie and electronic.", website: "https://stereofox.com", verified: false, articleCount: 0 },
  { id: cid("hello@stereostickman.com"), name: "Stereo Stickman", email: "hello@stereostickman.com", outlet: "Stereo Stickman", type: "curator", genre: "All Genres", region: "UK", beat: "Playlist Curation", bio: "Stereo Stickman — independent music blog and playlist curator.", website: "https://stereostickman.com", verified: false, articleCount: 0 },
  { id: cid("hello@musiccrowns.org"), name: "Music Crowns", email: "hello@musiccrowns.org", outlet: "Music Crowns", type: "curator", genre: "All Genres", region: "UK", beat: "Playlist Curation", bio: "Music Crowns — artist promotion platform and playlist curator.", website: "https://musiccrowns.org", verified: false, articleCount: 0 },
  { id: cid("hello@neonmusic.co.uk"), name: "Neon Music Curators", email: "hello@neonmusic.co.uk", outlet: "Neon Music", type: "curator", genre: "Pop, Indie, Electronic", region: "UK", beat: "Playlist Curation", bio: "Neon Music — UK music blog and playlist curator for pop and indie.", website: "https://neonmusic.co.uk", verified: false, articleCount: 0 },
  { id: cid("hello@lefuturewave.com"), name: "Le Future Wave Curators", email: "hello@lefuturewave.com", outlet: "Le Future Wave", type: "curator", genre: "Electronic, R&B, Soul", region: "US", beat: "Playlist Curation", bio: "Le Future Wave — curating forward-thinking electronic, R&B, and soul.", website: "https://lefuturewave.com", verified: false, articleCount: 0 },
  { id: cid("hello@chillfiltr.com"), name: "Chillfiltr", email: "hello@chillfiltr.com", outlet: "Chillfiltr", type: "curator", genre: "Indie, Chill, Lo-fi", region: "US", beat: "Playlist Curation", bio: "Chillfiltr — playlist curation site focused on chill and indie music.", website: "https://chillfiltr.com", verified: false, articleCount: 0 },
  { id: cid("curators@earmilk.com"), name: "Earmilk Curators", email: "curators@earmilk.com", outlet: "Earmilk", type: "curator", genre: "Electronic, Hip-Hop, R&B", region: "US", beat: "Playlist Curation", bio: "Earmilk — music blog and playlist curation team across streaming platforms.", website: "https://earmilk.com", verified: false, articleCount: 0 },
  { id: cid("hello@chillhop.com"), name: "Chillhop Music Curators", email: "hello@chillhop.com", outlet: "Chillhop", type: "curator", genre: "Lo-fi, Chill, Hip-Hop", region: "Netherlands", beat: "Playlist Curation", bio: "Chillhop Music — leading lo-fi hip-hop and chill beats label and curator.", website: "https://chillhop.com", verified: false, articleCount: 0 },
  { id: cid("hello@lofigirl.com"), name: "Lofi Girl Curators", email: "hello@lofigirl.com", outlet: "Lofi Girl", type: "curator", genre: "Lo-fi, Chill, Jazz Hop", region: "France", beat: "Playlist Curation", bio: "Lofi Girl — iconic lo-fi hip-hop YouTube channel and playlist curator.", website: "https://lofigirl.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thechillest.co"), name: "The Chillest", email: "submissions@thechillest.co", outlet: "The Chillest", type: "curator", genre: "Chill, Lo-fi, Ambient", region: "US", beat: "Playlist Curation", bio: "The Chillest — curating the most relaxing and chill music.", website: "https://thechillest.co", verified: false, articleCount: 0 },
  { id: cid("submissions@chillmasters.co"), name: "Chill Masters", email: "submissions@chillmasters.co", outlet: "Chill Masters", type: "curator", genre: "Chill, Deep House, Lo-fi", region: "US", beat: "Playlist Curation", bio: "Chill Masters — curating chill and deep house music playlists.", website: "https://chillmasters.co", verified: false, articleCount: 0 },
  { id: cid("hello@8tracks.com"), name: "8tracks", email: "hello@8tracks.com", outlet: "8tracks", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "8tracks — community-driven playlist platform for music discovery.", website: "https://8tracks.com", verified: false, articleCount: 0 },
  { id: cid("curators@hypem.com"), name: "Hype Machine Curators", email: "curators@hypem.com", outlet: "Hype Machine", type: "curator", genre: "Indie, Electronic, Alternative", region: "US", beat: "Playlist Curation", bio: "Hype Machine — music aggregator and playlist curator tracking music blogs.", website: "https://hypem.com", verified: false, articleCount: 0 },
  { id: cid("curators@musicismysanctuary.com"), name: "Music is My Sanctuary", email: "curators@musicismysanctuary.com", outlet: "Music is My Sanctuary", type: "curator", genre: "Soul, Jazz, Electronic, Hip-Hop", region: "Canada", beat: "Playlist Curation", bio: "Music is My Sanctuary — curating soul, jazz, electronic, and hip-hop.", website: "https://musicismysanctuary.com", verified: false, articleCount: 0 },
  { id: cid("submissions@onestowatch.com"), name: "Ones to Watch Curators", email: "submissions@onestowatch.com", outlet: "Ones to Watch", type: "curator", genre: "Pop, Indie, Alternative", region: "US", beat: "Playlist Curation", bio: "Ones to Watch — Live Nation's platform for discovering emerging artists.", website: "https://onestowatch.com", verified: false, articleCount: 0 },
  { id: cid("submissions@colorsxstudios.com"), name: "Colors Studios", email: "submissions@colorsxstudios.com", outlet: "Colors", type: "curator", genre: "R&B, Hip-Hop, Pop, Soul", region: "Germany", beat: "Playlist Curation", bio: "Colors — aesthetic live performance YouTube channel and artist discovery platform.", website: "https://colorsxstudios.com", verified: false, articleCount: 0 },
  { id: cid("music@kexplive.org"), name: "KEXP Live Sessions", email: "music@kexplive.org", outlet: "KEXP Live Sessions", type: "curator", genre: "Indie, Alternative, World", region: "Seattle, WA", beat: "Playlist Curation", bio: "KEXP — iconic live session series discovering and promoting new artists.", website: "https://kexp.org", verified: false, articleCount: 0 },
  { id: cid("submissions@audiotree.tv"), name: "Audiotree", email: "submissions@audiotree.tv", outlet: "Audiotree", type: "curator", genre: "Indie, Rock, Alternative", region: "US", beat: "Playlist Curation", bio: "Audiotree — live session platform and music discovery channel.", website: "https://audiotree.tv", verified: false, articleCount: 0 },
  { id: cid("submissions@pastestudio.com"), name: "Paste Studio Sessions", email: "submissions@pastestudio.com", outlet: "Paste Studio", type: "curator", genre: "Indie, Rock, Folk", region: "US", beat: "Playlist Curation", bio: "Paste Studio — live session series from Paste Magazine.", website: "https://pastemagazine.com", verified: false, articleCount: 0 },
];

// ─── SOUNDCLOUD CHANNELS ────────────────────────────────────────────────────────

const soundcloudCuratorContacts: SeedContact[] = [
  { id: cid("contact@repostnetwork.com"), name: "Repost Network", email: "contact@repostnetwork.com", outlet: "Repost Network", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Repost Network — SoundCloud's official distribution and promotion service.", website: "https://repostnetwork.com", verified: false, articleCount: 0 },
  { id: cid("contact@theartistunion.com"), name: "The Artist Union", email: "contact@theartistunion.com", outlet: "The Artist Union", type: "curator", genre: "Electronic, Hip-Hop, R&B", region: "US", beat: "Playlist Curation", bio: "The Artist Union — SoundCloud promotion and fan engagement platform.", website: "https://theartistunion.com", verified: false, articleCount: 0 },
  { id: cid("hello@repostexchange.com"), name: "Repost Exchange", email: "hello@repostexchange.com", outlet: "Repost Exchange", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Repost Exchange — community-based SoundCloud repost network.", website: "https://repostexchange.com", verified: false, articleCount: 0 },
  { id: cid("contact@hivemusicgroup.com"), name: "Hive Music Group", email: "contact@hivemusicgroup.com", outlet: "Hive", type: "curator", genre: "Hip-Hop, R&B, Electronic", region: "US", beat: "Playlist Curation", bio: "Hive — SoundCloud promotion network for hip-hop and electronic music.", website: "https://hivemusicgroup.com", verified: false, articleCount: 0 },
  { id: cid("submissions@soundcloudpromo.com"), name: "SoundCloud Promotion", email: "submissions@soundcloudpromo.com", outlet: "SoundCloud Promotion", type: "curator", genre: "Electronic, Hip-Hop, Pop", region: "US", beat: "Playlist Curation", bio: "SoundCloud Promotion — curating and promoting tracks on SoundCloud.", website: "https://soundcloudpromo.com", verified: false, articleCount: 0 },
  { id: cid("submissions@promotesound.com"), name: "Promote Sound", email: "submissions@promotesound.com", outlet: "Promote Sound", type: "curator", genre: "Electronic, Dance, Bass", region: "US", beat: "Playlist Curation", bio: "Promote Sound — SoundCloud promotion channel for electronic and dance music.", website: "https://promotesound.com", verified: false, articleCount: 0 },
  { id: cid("submissions@scplaylist.com"), name: "SoundCloud Go Playlist Team", email: "submissions@scplaylist.com", outlet: "SoundCloud Go Playlists", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "SoundCloud Go — official playlist curation for SoundCloud's premium tier.", website: "https://soundcloud.com", verified: false, articleCount: 0 },
  { id: cid("contact@hearditfirst.com"), name: "Heard It Here First", email: "contact@hearditfirst.com", outlet: "Heard It Here First", type: "curator", genre: "Dance, House, Electronic", region: "UK", beat: "Playlist Curation", bio: "Heard It Here First — SoundCloud-based curation for dance and house music.", website: "https://hearditfirst.com", verified: false, articleCount: 0 },
  { id: cid("contact@laclinica.net"), name: "La Clinica Recs", email: "contact@laclinica.net", outlet: "La Clinica Recs", type: "curator", genre: "Electronic, House, Techno", region: "Spain", beat: "Playlist Curation", bio: "La Clinica Recs — SoundCloud label and curation channel for electronic music.", website: "https://laclinica.net", verified: false, articleCount: 0 },
  { id: cid("submissions@artistunionsc.com"), name: "Artist Union SC", email: "submissions@artistunionsc.com", outlet: "Artist Union SC", type: "curator", genre: "Electronic, Hip-Hop, Pop", region: "US", beat: "Playlist Curation", bio: "Artist Union — SoundCloud-focused artist promotion platform.", website: "https://theartistunion.com", verified: false, articleCount: 0 },
];

// ─── ADDITIONAL CURATORS ────────────────────────────────────────────────────────

const additionalCuratorContacts: SeedContact[] = [
  { id: cid("music@tropicalbassmusic.com"), name: "Tropical Bass Music", email: "music@tropicalbassmusic.com", outlet: "Tropical Bass Music", type: "curator", genre: "Tropical, Bass, Electronic", region: "US", beat: "Playlist Curation", bio: "Tropical Bass Music — curating tropical-flavored bass and electronic music.", website: "https://tropicalbassmusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thenocturnal.co"), name: "The Nocturnal Times", email: "submissions@thenocturnal.co", outlet: "The Nocturnal Times", type: "curator", genre: "EDM, Dance, Electronic", region: "US", beat: "Playlist Curation", bio: "The Nocturnal Times — electronic music blog and playlist curator.", website: "https://thenocturnal.co", verified: false, articleCount: 0 },
  { id: cid("music@deeprootsmusic.com"), name: "Deep Roots Music", email: "music@deeprootsmusic.com", outlet: "Deep Roots Music", type: "curator", genre: "Reggae, Roots, Dub", region: "UK", beat: "Playlist Curation", bio: "Deep Roots Music — curating reggae, roots, and dub music.", website: "https://deeprootsmusic.com", verified: false, articleCount: 0 },
  { id: cid("music@synthwavecurator.com"), name: "Synthwave Curator", email: "music@synthwavecurator.com", outlet: "Synthwave Curator", type: "curator", genre: "Synthwave, Retrowave, Electronic", region: "US", beat: "Playlist Curation", bio: "Synthwave Curator — dedicated to synthwave and retro electronic music.", website: "https://synthwavecurator.com", verified: false, articleCount: 0 },
  { id: cid("submissions@futuresounds.co"), name: "Future Sounds", email: "submissions@futuresounds.co", outlet: "Future Sounds", type: "curator", genre: "Electronic, Experimental, Bass", region: "US", beat: "Playlist Curation", bio: "Future Sounds — curating forward-thinking electronic and experimental music.", website: "https://futuresounds.co", verified: false, articleCount: 0 },
  { id: cid("music@curatorsunited.com"), name: "Curators United", email: "music@curatorsunited.com", outlet: "Curators United", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "Curators United — collective of independent Spotify playlist curators.", website: "https://curatorsunited.com", verified: false, articleCount: 0 },
  { id: cid("submit@goodvibesonly.co"), name: "Good Vibes Only", email: "submit@goodvibesonly.co", outlet: "Good Vibes Only", type: "curator", genre: "Chill, R&B, Lo-fi", region: "US", beat: "Playlist Curation", bio: "Good Vibes Only — playlist brand curating feel-good music across genres.", website: "https://goodvibesonly.co", verified: false, articleCount: 0 },
  { id: cid("submissions@deepcutscurator.com"), name: "Deep Cuts", email: "submissions@deepcutscurator.com", outlet: "Deep Cuts", type: "curator", genre: "Indie, Alternative, Rock", region: "US", beat: "Playlist Curation", bio: "Deep Cuts — playlist curator surfacing hidden gems in indie and alternative.", website: "https://deepcutscurator.com", verified: false, articleCount: 0 },
  { id: cid("music@midnightlistening.com"), name: "Midnight Listening", email: "music@midnightlistening.com", outlet: "Midnight Listening", type: "curator", genre: "Ambient, Chill, Electronic", region: "UK", beat: "Playlist Curation", bio: "Midnight Listening — late-night ambient and chill playlist curation.", website: "https://midnightlistening.com", verified: false, articleCount: 0 },
  { id: cid("contact@thecuratorslounge.com"), name: "The Curators Lounge", email: "contact@thecuratorslounge.com", outlet: "The Curators Lounge", type: "curator", genre: "All Genres", region: "US", beat: "Playlist Curation", bio: "The Curators Lounge — independent playlist curation collective.", website: "https://thecuratorslounge.com", verified: false, articleCount: 0 },
  { id: cid("music@indievibesmusic.com"), name: "Indie Vibes Music", email: "music@indievibesmusic.com", outlet: "Indie Vibes Music", type: "curator", genre: "Indie, Alternative, Folk", region: "US", beat: "Playlist Curation", bio: "Indie Vibes Music — curating the best indie, alternative, and folk.", website: "https://indievibesmusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@soulfulplaylists.com"), name: "Soulful Playlists", email: "submissions@soulfulplaylists.com", outlet: "Soulful Playlists", type: "curator", genre: "Soul, R&B, Neo-Soul", region: "US", beat: "Playlist Curation", bio: "Soulful Playlists — curating soul, R&B, and neo-soul across platforms.", website: "https://soulfulplaylists.com", verified: false, articleCount: 0 },
  { id: cid("music@jazzdiscovery.co"), name: "Jazz Discovery", email: "music@jazzdiscovery.co", outlet: "Jazz Discovery", type: "curator", genre: "Jazz, Contemporary Jazz", region: "US", beat: "Playlist Curation", bio: "Jazz Discovery — playlist curator for jazz and contemporary jazz.", website: "https://jazzdiscovery.co", verified: false, articleCount: 0 },
  { id: cid("submissions@newwavecuration.com"), name: "New Wave Curation", email: "submissions@newwavecuration.com", outlet: "New Wave Curation", type: "curator", genre: "New Wave, Synth-Pop, Post-Punk", region: "UK", beat: "Playlist Curation", bio: "New Wave Curation — dedicated to new wave, synth-pop, and post-punk.", website: "https://newwavecuration.com", verified: false, articleCount: 0 },
  { id: cid("music@acousticafternoon.com"), name: "Acoustic Afternoon", email: "music@acousticafternoon.com", outlet: "Acoustic Afternoon", type: "curator", genre: "Acoustic, Folk, Singer-Songwriter", region: "US", beat: "Playlist Curation", bio: "Acoustic Afternoon — curating acoustic, folk, and singer-songwriter music.", website: "https://acousticafternoon.com", verified: false, articleCount: 0 },
  { id: cid("submissions@hiphopdigest.co"), name: "Hip Hop Digest", email: "submissions@hiphopdigest.co", outlet: "Hip Hop Digest", type: "curator", genre: "Hip-Hop, Rap", region: "US", beat: "Playlist Curation", bio: "Hip Hop Digest — curating essential hip-hop and rap playlists.", website: "https://hiphopdigest.co", verified: false, articleCount: 0 },
];

// ─── MAJOR MUSIC PODCASTS ───────────────────────────────────────────────────────

const majorPodcasterContacts: SeedContact[] = [
  { id: cid("podcast@questlovesupreme.com"), name: "Questlove Supreme", email: "podcast@questlovesupreme.com", outlet: "Questlove Supreme", type: "podcaster", genre: "Hip-Hop, Soul, R&B, Funk", region: "US", beat: "Music Podcast", bio: "Questlove Supreme — The Roots' Questlove hosting music industry conversations.", website: "https://questlovesupreme.com", verified: false, articleCount: 0 },
  { id: cid("podcast@midnightmiracle.com"), name: "Midnight Miracle", email: "podcast@midnightmiracle.com", outlet: "Midnight Miracle", type: "podcaster", genre: "Hip-Hop, Culture", region: "US", beat: "Music Podcast", bio: "Midnight Miracle — Talib Kweli, Yasiin Bey, and Dave Chappelle's podcast.", website: "https://midnightmiracle.com", verified: false, articleCount: 0 },
  { id: cid("podcast@itsthereal.com"), name: "A Waste of Time with ItsTheReal", email: "podcast@itsthereal.com", outlet: "A Waste of Time", type: "podcaster", genre: "Hip-Hop, Pop", region: "US", beat: "Music Podcast", bio: "A Waste of Time — ItsTheReal's music industry interview podcast.", website: "https://itsthereal.com", verified: false, articleCount: 0 },
  { id: cid("podcast@louderthanariot.org"), name: "Louder Than A Riot", email: "podcast@louderthanariot.org", outlet: "Louder Than A Riot", type: "podcaster", genre: "Hip-Hop", region: "US", beat: "Music Podcast", bio: "Louder Than A Riot — NPR podcast exploring hip-hop and mass incarceration.", website: "https://npr.org/louder-than-a-riot", verified: false, articleCount: 0 },
  { id: cid("podcast@dollpartonsamerica.com"), name: "Dolly Parton's America", email: "podcast@dollpartonsamerica.com", outlet: "Dolly Parton's America", type: "podcaster", genre: "Country", region: "US", beat: "Music Podcast", bio: "Dolly Parton's America — WNYC podcast exploring Dolly and American culture.", website: "https://dollpartonsamerica.com", verified: false, articleCount: 0 },
  { id: cid("podcast@cocaineandrhinestones.com"), name: "Cocaine & Rhinestones", email: "podcast@cocaineandrhinestones.com", outlet: "Cocaine & Rhinestones", type: "podcaster", genre: "Country", region: "US", beat: "Music Podcast", bio: "Cocaine & Rhinestones — deep dive into country music history.", website: "https://cocaineandrhinestones.com", verified: false, articleCount: 0 },
  { id: cid("podcast@disgracelandpod.com"), name: "Disgraceland", email: "podcast@disgracelandpod.com", outlet: "Disgraceland", type: "podcaster", genre: "Rock, All Genres", region: "US", beat: "Music Podcast", bio: "Disgraceland — true crime and music podcast exploring rock's dark side.", website: "https://disgracelandpod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@27clubpodcast.com"), name: "27 Club Podcast", email: "podcast@27clubpodcast.com", outlet: "27 Club", type: "podcaster", genre: "Rock, All Genres", region: "US", beat: "Music Podcast", bio: "27 Club — podcast exploring the lives of musicians who died at 27.", website: "https://27clubpodcast.com", verified: false, articleCount: 0 },
  { id: cid("podcast@nodogsinspa.ce"), name: "No Dogs in Space", email: "podcast@nodogsinspa.ce", outlet: "No Dogs in Space", type: "podcaster", genre: "Punk, Rock, Post-Punk", region: "US", beat: "Music Podcast", bio: "No Dogs in Space — deep dives into punk, post-punk, and alternative history.", website: "https://nodogsinspa.ce", verified: false, articleCount: 0 },
  { id: cid("podcast@hitparadepod.com"), name: "Hit Parade", email: "podcast@hitparadepod.com", outlet: "Hit Parade (Slate)", type: "podcaster", genre: "Pop, All Genres", region: "US", beat: "Music Podcast", bio: "Hit Parade — Slate's music history podcast charting the stories behind hits.", website: "https://slate.com/hit-parade", verified: false, articleCount: 0 },
  { id: cid("podcast@popcastnyt.com"), name: "Popcast", email: "podcast@popcastnyt.com", outlet: "Popcast (NY Times)", type: "podcaster", genre: "Pop, All Genres", region: "US", beat: "Music Podcast", bio: "Popcast — New York Times music podcast covering pop culture and criticism.", website: "https://nytimes.com/popcast", verified: false, articleCount: 0 },
  { id: cid("podcast@nardwuar.com"), name: "Nardwuar", email: "podcast@nardwuar.com", outlet: "Nardwuar", type: "podcaster", genre: "Hip-Hop, Rock, All Genres", region: "Canada", beat: "Music Podcast", bio: "Nardwuar — legendary music interviewer known for deep research and surprises.", website: "https://nardwuar.com", verified: false, articleCount: 0 },
  { id: cid("podcast@bighitshow.com"), name: "The Big Hit Show", email: "podcast@bighitshow.com", outlet: "The Big Hit Show", type: "podcaster", genre: "Pop, All Genres", region: "US", beat: "Music Podcast", bio: "The Big Hit Show — podcast exploring the making of cultural phenomena.", website: "https://bighitshow.com", verified: false, articleCount: 0 },
  { id: cid("podcast@decoderringpod.com"), name: "Decoder Ring", email: "podcast@decoderringpod.com", outlet: "Decoder Ring (Slate)", type: "podcaster", genre: "All Genres, Culture", region: "US", beat: "Music Podcast", bio: "Decoder Ring — Slate's cultural history podcast often covering music.", website: "https://slate.com/decoder-ring", verified: false, articleCount: 0 },
  { id: cid("podcast@strongsongspod.com"), name: "Strong Songs", email: "podcast@strongsongspod.com", outlet: "Strong Songs", type: "podcaster", genre: "All Genres", region: "US", beat: "Music Podcast", bio: "Strong Songs — Kirk Hamilton breaks down why great songs work.", website: "https://strongsongspod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@alancross.ca"), name: "Ongoing History of New Music", email: "podcast@alancross.ca", outlet: "Ongoing History of New Music", type: "podcaster", genre: "Rock, Alternative, Indie", region: "Canada", beat: "Music Podcast", bio: "Ongoing History — Alan Cross's legendary music history podcast.", website: "https://alancross.ca", verified: false, articleCount: 0 },
  { id: cid("podcast@desertislanddiscs.co.uk"), name: "Desert Island Discs", email: "podcast@desertislanddiscs.co.uk", outlet: "Desert Island Discs", type: "podcaster", genre: "All Genres", region: "UK", beat: "Music Podcast", bio: "Desert Island Discs — BBC Radio 4's iconic music-centered interview show.", website: "https://bbc.co.uk/desertislanddiscs", verified: false, articleCount: 0 },
  { id: cid("podcast@freshairmusic.org"), name: "Fresh Air Music Segments", email: "podcast@freshairmusic.org", outlet: "Fresh Air (Terry Gross)", type: "podcaster", genre: "All Genres", region: "US", beat: "Music Podcast", bio: "Fresh Air — Terry Gross's NPR show featuring acclaimed musician interviews.", website: "https://npr.org/fresh-air", verified: false, articleCount: 0 },
  { id: cid("podcast@worldcafe.org"), name: "World Cafe", email: "podcast@worldcafe.org", outlet: "World Cafe", type: "podcaster", genre: "Indie, Rock, Folk, World", region: "US", beat: "Music Podcast", bio: "World Cafe — NPR music discovery show featuring live sessions and interviews.", website: "https://npr.org/world-cafe", verified: false, articleCount: 0 },
  { id: cid("podcast@mountainstage.org"), name: "Mountain Stage", email: "podcast@mountainstage.org", outlet: "Mountain Stage", type: "podcaster", genre: "Folk, Americana, Rock, Indie", region: "US", beat: "Music Podcast", bio: "Mountain Stage — NPR live performance radio show from West Virginia.", website: "https://mountainstage.org", verified: false, articleCount: 0 },
];

// ─── MUSIC PRODUCTION / INDUSTRY PODCASTS ───────────────────────────────────────

const productionPodcasterContacts: SeedContact[] = [
  { id: cid("podcast@pensadosplace.tv"), name: "Pensado's Place", email: "podcast@pensadosplace.tv", outlet: "Pensado's Place", type: "podcaster", genre: "All Genres, Production", region: "US", beat: "Music Podcast", bio: "Pensado's Place — Dave Pensado's show on mixing, mastering, and music production.", website: "https://pensadosplace.tv", verified: false, articleCount: 0 },
  { id: cid("podcast@recordingstudiorockstars.com"), name: "Recording Studio Rockstars", email: "podcast@recordingstudiorockstars.com", outlet: "Recording Studio Rockstars", type: "podcaster", genre: "All Genres, Production", region: "US", beat: "Music Podcast", bio: "Recording Studio Rockstars — interviews with top producers and engineers.", website: "https://recordingstudiorockstars.com", verified: false, articleCount: 0 },
  { id: cid("podcast@themasteringshow.com"), name: "The Mastering Show", email: "podcast@themasteringshow.com", outlet: "The Mastering Show", type: "podcaster", genre: "All Genres, Production", region: "US", beat: "Music Podcast", bio: "The Mastering Show — podcast dedicated to the art of audio mastering.", website: "https://themasteringshow.com", verified: false, articleCount: 0 },
  { id: cid("podcast@urm.academy"), name: "URM Podcast", email: "podcast@urm.academy", outlet: "URM Podcast", type: "podcaster", genre: "Rock, Metal, Production", region: "US", beat: "Music Podcast", bio: "URM Podcast — Nail the Mix team's production and mixing podcast.", website: "https://urm.academy", verified: false, articleCount: 0 },
  { id: cid("podcast@producelikeapro.com"), name: "Produce Like A Pro", email: "podcast@producelikeapro.com", outlet: "Produce Like A Pro", type: "podcaster", genre: "All Genres, Production", region: "US", beat: "Music Podcast", bio: "Produce Like A Pro — Warren Huart's music production education podcast.", website: "https://producelikeapro.com", verified: false, articleCount: 0 },
  { id: cid("podcast@workingclassaudio.com"), name: "Working Class Audio", email: "podcast@workingclassaudio.com", outlet: "Working Class Audio", type: "podcaster", genre: "All Genres, Production", region: "US", beat: "Music Podcast", bio: "Working Class Audio — real talk with working audio engineers and producers.", website: "https://workingclassaudio.com", verified: false, articleCount: 0 },
  { id: cid("podcast@theproaudiofiles.com"), name: "The Pro Audio Files", email: "podcast@theproaudiofiles.com", outlet: "The Pro Audio Files", type: "podcaster", genre: "All Genres, Production", region: "US", beat: "Music Podcast", bio: "The Pro Audio Files — podcast covering professional audio production.", website: "https://theproaudiofiles.com", verified: false, articleCount: 0 },
  { id: cid("podcast@cdbaby.com"), name: "DIY Musician Podcast", email: "podcast@cdbaby.com", outlet: "DIY Musician (CD Baby)", type: "podcaster", genre: "All Genres, Industry", region: "US", beat: "Music Podcast", bio: "DIY Musician — CD Baby's podcast for independent musicians on the business of music.", website: "https://cdbaby.com", verified: false, articleCount: 0 },
  { id: cid("podcast@bandzoogle.com"), name: "Bandzoogle Podcast", email: "podcast@bandzoogle.com", outlet: "Bandzoogle", type: "podcaster", genre: "All Genres, Industry", region: "Canada", beat: "Music Podcast", bio: "Bandzoogle — podcast helping independent musicians build their online presence.", website: "https://bandzoogle.com", verified: false, articleCount: 0 },
  { id: cid("podcast@musictectonics.com"), name: "Music Tectonics", email: "podcast@musictectonics.com", outlet: "Music Tectonics", type: "podcaster", genre: "All Genres, Tech", region: "US", beat: "Music Podcast", bio: "Music Tectonics — exploring the intersection of music and technology.", website: "https://musictectonics.com", verified: false, articleCount: 0 },
  { id: cid("podcast@trapital.co"), name: "Trapital", email: "podcast@trapital.co", outlet: "Trapital", type: "podcaster", genre: "Hip-Hop, Industry", region: "US", beat: "Music Podcast", bio: "Trapital — Dan Runcie's podcast on hip-hop business and strategy.", website: "https://trapital.co", verified: false, articleCount: 0 },
  { id: cid("podcast@waterandmusic.com"), name: "Water & Music", email: "podcast@waterandmusic.com", outlet: "Water & Music", type: "podcaster", genre: "All Genres, Industry", region: "US", beat: "Music Podcast", bio: "Water & Music — Cherie Hu's podcast on music industry innovation.", website: "https://waterandmusic.com", verified: false, articleCount: 0 },
  { id: cid("podcast@mbw.com"), name: "Music Business Worldwide Podcast", email: "podcast@mbw.com", outlet: "Music Business Worldwide", type: "podcaster", genre: "All Genres, Industry", region: "UK", beat: "Music Podcast", bio: "Music Business Worldwide — podcast covering the global music industry.", website: "https://musicbusinessworldwide.com", verified: false, articleCount: 0 },
  { id: cid("podcast@newmusicbusiness.com"), name: "New Music Business", email: "podcast@newmusicbusiness.com", outlet: "New Music Business", type: "podcaster", genre: "All Genres, Industry", region: "US", beat: "Music Podcast", bio: "New Music Business — Ari Herstand's podcast on navigating the modern music industry.", website: "https://newmusicbusiness.com", verified: false, articleCount: 0 },
  { id: cid("podcast@musictomorrow.com"), name: "Music Tomorrow", email: "podcast@musictomorrow.com", outlet: "Music Tomorrow", type: "podcaster", genre: "All Genres, Data", region: "France", beat: "Music Podcast", bio: "Music Tomorrow — podcast on data-driven music marketing and industry trends.", website: "https://musictomorrow.com", verified: false, articleCount: 0 },
  { id: cid("podcast@bobbyowsinski.com"), name: "Bobby Owsinski Podcast", email: "podcast@bobbyowsinski.com", outlet: "Bobby Owsinski", type: "podcaster", genre: "All Genres, Production", region: "US", beat: "Music Podcast", bio: "Bobby Owsinski — veteran producer and author discussing music production and industry.", website: "https://bobbyowsinski.com", verified: false, articleCount: 0 },
  { id: cid("podcast@therecordpod.com"), name: "The Record Podcast", email: "podcast@therecordpod.com", outlet: "The Record", type: "podcaster", genre: "All Genres, Industry", region: "US", beat: "Music Podcast", bio: "The Record — podcast exploring the stories behind music recordings.", website: "https://therecordpod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@behindthesetlist.com"), name: "Behind the Setlist", email: "podcast@behindthesetlist.com", outlet: "Behind the Setlist", type: "podcaster", genre: "All Genres, Live Music", region: "US", beat: "Music Podcast", bio: "Behind the Setlist — exploring the art of live music performance.", website: "https://behindthesetlist.com", verified: false, articleCount: 0 },
  { id: cid("podcast@creativejuicepod.com"), name: "Creative Juice", email: "podcast@creativejuicepod.com", outlet: "Creative Juice", type: "podcaster", genre: "All Genres, Creative", region: "US", beat: "Music Podcast", bio: "Creative Juice — podcast exploring creativity in music and art.", website: "https://creativejuicepod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@musicindustryblueprint.com"), name: "Music Industry Blueprint", email: "podcast@musicindustryblueprint.com", outlet: "Music Industry Blueprint", type: "podcaster", genre: "All Genres, Industry", region: "US", beat: "Music Podcast", bio: "Music Industry Blueprint — actionable strategies for independent musicians.", website: "https://musicindustryblueprint.com", verified: false, articleCount: 0 },
];

// ─── GENRE-SPECIFIC PODCASTS ────────────────────────────────────────────────────

const genrePodcasterContacts: SeedContact[] = [
  { id: cid("podcast@metalinjection.net"), name: "Metal Injection Podcast", email: "podcast@metalinjection.net", outlet: "Metal Injection", type: "podcaster", genre: "Metal, Heavy", region: "US", beat: "Music Podcast", bio: "Metal Injection — podcast covering the metal music scene and news.", website: "https://metalinjection.net", verified: false, articleCount: 0 },
  { id: cid("podcast@gettingitoutpod.com"), name: "Getting It Out", email: "podcast@gettingitoutpod.com", outlet: "Getting It Out", type: "podcaster", genre: "Hardcore, Punk, Metal", region: "US", beat: "Music Podcast", bio: "Getting It Out — podcast covering hardcore, punk, and heavy music.", website: "https://gettingitoutpod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@nocleansinging.com"), name: "No Clean Singing Podcast", email: "podcast@nocleansinging.com", outlet: "No Clean Singing", type: "podcaster", genre: "Metal, Extreme", region: "US", beat: "Music Podcast", bio: "No Clean Singing — podcast for extreme metal reviews and discovery.", website: "https://nocleansinging.com", verified: false, articleCount: 0 },
  { id: cid("podcast@heavymetalpod.com"), name: "Heavy Metal Podcast", email: "podcast@heavymetalpod.com", outlet: "Heavy Metal Podcast", type: "podcaster", genre: "Metal, Heavy", region: "US", beat: "Music Podcast", bio: "Heavy Metal Podcast — discussions and interviews in the metal community.", website: "https://heavymetalpod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@neckbreakersball.com"), name: "Neckbreaker's Ball", email: "podcast@neckbreakersball.com", outlet: "Neckbreaker's Ball", type: "podcaster", genre: "Metal, Thrash, Death Metal", region: "US", beat: "Music Podcast", bio: "Neckbreaker's Ball — podcast celebrating thrash and extreme metal.", website: "https://neckbreakersball.com", verified: false, articleCount: 0 },
  { id: cid("podcast@progmagazine.com"), name: "Prog Magazine Podcast", email: "podcast@progmagazine.com", outlet: "Prog Magazine", type: "podcaster", genre: "Progressive Rock, Prog Metal", region: "UK", beat: "Music Podcast", bio: "Prog Magazine — official podcast from the world's leading prog publication.", website: "https://progmagazine.com", verified: false, articleCount: 0 },
  { id: cid("podcast@electronicbeats.net"), name: "Electronic Beats Podcast", email: "podcast@electronicbeats.net", outlet: "Electronic Beats", type: "podcaster", genre: "Electronic, Techno, House", region: "Germany", beat: "Music Podcast", bio: "Electronic Beats — Telekom's podcast on electronic music culture.", website: "https://electronicbeats.net", verified: false, articleCount: 0 },
  { id: cid("podcast@ra.co"), name: "Resident Advisor Podcast", email: "podcast@ra.co", outlet: "Resident Advisor", type: "podcaster", genre: "Electronic, Techno, House", region: "UK", beat: "Music Podcast", bio: "Resident Advisor — essential podcast for electronic music culture.", website: "https://ra.co", verified: false, articleCount: 0 },
  { id: cid("podcast@boilerroom.tv"), name: "Boiler Room Podcast", email: "podcast@boilerroom.tv", outlet: "Boiler Room", type: "podcaster", genre: "Electronic, Dance, Club", region: "UK", beat: "Music Podcast", bio: "Boiler Room — iconic live streaming platform's companion podcast.", website: "https://boilerroom.tv", verified: false, articleCount: 0 },
  { id: cid("podcast@deephousecat.com"), name: "Deep House Cat", email: "podcast@deephousecat.com", outlet: "Deep House Cat", type: "podcaster", genre: "Deep House, House", region: "Germany", beat: "Music Podcast", bio: "Deep House Cat — long-running deep house podcast mix series.", website: "https://deephousecat.com", verified: false, articleCount: 0 },
  { id: cid("podcast@thejazzsession.com"), name: "The Jazz Session", email: "podcast@thejazzsession.com", outlet: "The Jazz Session", type: "podcaster", genre: "Jazz", region: "US", beat: "Music Podcast", bio: "The Jazz Session — in-depth interviews with jazz musicians.", website: "https://thejazzsession.com", verified: false, articleCount: 0 },
  { id: cid("podcast@jazznightinamerica.org"), name: "Jazz Night in America", email: "podcast@jazznightinamerica.org", outlet: "Jazz Night in America (NPR)", type: "podcaster", genre: "Jazz", region: "US", beat: "Music Podcast", bio: "Jazz Night in America — NPR podcast celebrating jazz culture.", website: "https://npr.org/jazz-night", verified: false, articleCount: 0 },
  { id: cid("podcast@notesfromthevibes.com"), name: "Notes from the Vibes", email: "podcast@notesfromthevibes.com", outlet: "Notes from the Vibes", type: "podcaster", genre: "Jazz, Soul, Neo-Soul", region: "US", beat: "Music Podcast", bio: "Notes from the Vibes — exploring jazz, soul, and neo-soul music.", website: "https://notesfromthevibes.com", verified: false, articleCount: 0 },
  { id: cid("podcast@folkalleypod.com"), name: "Folk Alley Podcast", email: "podcast@folkalleypod.com", outlet: "Folk Alley", type: "podcaster", genre: "Folk, Acoustic", region: "US", beat: "Music Podcast", bio: "Folk Alley — podcast from WKSU curating and featuring folk music.", website: "https://folkalley.com", verified: false, articleCount: 0 },
  { id: cid("podcast@thebluegrasssituation.com"), name: "The Bluegrass Situation", email: "podcast@thebluegrasssituation.com", outlet: "The Bluegrass Situation", type: "podcaster", genre: "Bluegrass, Americana, Folk", region: "US", beat: "Music Podcast", bio: "The Bluegrass Situation — podcast for bluegrass and roots music.", website: "https://thebluegrasssituation.com", verified: false, articleCount: 0 },
  { id: cid("podcast@fistfulofamericana.com"), name: "Fistful of Americana", email: "podcast@fistfulofamericana.com", outlet: "Fistful of Americana", type: "podcaster", genre: "Americana, Country, Roots", region: "US", beat: "Music Podcast", bio: "Fistful of Americana — podcast dedicated to Americana and roots music.", website: "https://fistfulofamericana.com", verified: false, articleCount: 0 },
  { id: cid("podcast@countrymusicpod.com"), name: "Country Music Podcast", email: "podcast@countrymusicpod.com", outlet: "Country Music Podcast", type: "podcaster", genre: "Country", region: "US", beat: "Music Podcast", bio: "Country Music Podcast — interviews and features in country music.", website: "https://countrymusicpod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@rnbmoney.com"), name: "R&B Money", email: "podcast@rnbmoney.com", outlet: "R&B Money", type: "podcaster", genre: "R&B, Soul", region: "US", beat: "Music Podcast", bio: "R&B Money — Tank's podcast celebrating R&B music and culture.", website: "https://rnbmoney.com", verified: false, articleCount: 0 },
  { id: cid("podcast@ebrointhemorning.com"), name: "Ebro in the Morning", email: "podcast@ebrointhemorning.com", outlet: "Ebro in the Morning", type: "podcaster", genre: "Hip-Hop, R&B", region: "US", beat: "Music Podcast", bio: "Ebro in the Morning — Hot 97's flagship morning show podcast.", website: "https://ebrointhemorning.com", verified: false, articleCount: 0 },
  { id: cid("podcast@drinkchamps.com"), name: "Drink Champs", email: "podcast@drinkchamps.com", outlet: "Drink Champs", type: "podcaster", genre: "Hip-Hop, Rap", region: "US", beat: "Music Podcast", bio: "Drink Champs — N.O.R.E. and DJ EFN's hip-hop interview podcast.", website: "https://drinkchamps.com", verified: false, articleCount: 0 },
  { id: cid("press@rapradar.com"), name: "Rap Radar Podcast", email: "press@rapradar.com", outlet: "Rap Radar", type: "podcaster", genre: "Hip-Hop, Rap", region: "US", beat: "Music Podcast", bio: "Rap Radar — Elliott Wilson and Brian 'B.Dot' Miller's hip-hop podcast.", website: "https://rapradar.com", verified: false, articleCount: 0 },
  { id: cid("podcast@milliondollazworth.com"), name: "Million Dollaz Worth of Game", email: "podcast@milliondollazworth.com", outlet: "Million Dollaz Worth of Game", type: "podcaster", genre: "Hip-Hop, Culture", region: "US", beat: "Music Podcast", bio: "Million Dollaz Worth of Game — Gillie Da Kid and Wallo's hip-hop podcast.", website: "https://milliondollazworth.com", verified: false, articleCount: 0 },
  { id: cid("podcast@brilliantidiots.com"), name: "Brilliant Idiots", email: "podcast@brilliantidiots.com", outlet: "Brilliant Idiots", type: "podcaster", genre: "Hip-Hop, Culture", region: "US", beat: "Music Podcast", bio: "Brilliant Idiots — Charlamagne Tha God and Andrew Schulz's culture podcast.", website: "https://brilliantidiots.com", verified: false, articleCount: 0 },
  { id: cid("podcast@joebuddenpodcast.com"), name: "The Joe Budden Podcast", email: "podcast@joebuddenpodcast.com", outlet: "The Joe Budden Podcast", type: "podcaster", genre: "Hip-Hop, R&B", region: "US", beat: "Music Podcast", bio: "The Joe Budden Podcast — Joe Budden's influential music and culture podcast.", website: "https://joebuddenpodcast.com", verified: false, articleCount: 0 },
];

// ─── INTERVIEW / FEATURE PODCASTS ───────────────────────────────────────────────

const interviewPodcasterContacts: SeedContact[] = [
  { id: cid("hello@kreativekontrol.com"), name: "Kreative Kontrol", email: "hello@kreativekontrol.com", outlet: "Kreative Kontrol", type: "podcaster", genre: "Indie, Alternative, All Genres", region: "Canada", beat: "Music Podcast", bio: "Kreative Kontrol — Vish Khanna's interview podcast with musicians and creatives.", website: "https://kreativekontrol.com", verified: false, articleCount: 0 },
  { id: cid("podcast@sodajerker.com"), name: "Sodajerker On Songwriting", email: "podcast@sodajerker.com", outlet: "Sodajerker", type: "podcaster", genre: "All Genres, Songwriting", region: "UK", beat: "Music Podcast", bio: "Sodajerker — award-winning podcast on the craft of songwriting.", website: "https://sodajerker.com", verified: false, articleCount: 0 },
  { id: cid("hello@andthewriteris.com"), name: "And the Writer Is...", email: "hello@andthewriteris.com", outlet: "And the Writer Is...", type: "podcaster", genre: "Pop, All Genres, Songwriting", region: "US", beat: "Music Podcast", bio: "And the Writer Is — Ross Golan interviews the songwriters behind the hits.", website: "https://andthewriteris.com", verified: false, articleCount: 0 },
  { id: cid("hello@brokenrecordpodcast.com"), name: "Broken Record", email: "hello@brokenrecordpodcast.com", outlet: "Broken Record", type: "podcaster", genre: "All Genres", region: "US", beat: "Music Podcast", bio: "Broken Record — Rick Rubin, Malcolm Gladwell, and Bruce Headlam's music podcast.", website: "https://brokenrecordpodcast.com", verified: false, articleCount: 0 },
  { id: cid("press@songexploder.net"), name: "Song Exploder Extras", email: "press@songexploder.net", outlet: "Song Exploder", type: "podcaster", genre: "All Genres", region: "US", beat: "Music Podcast", bio: "Song Exploder — Hrishikesh Hirway's podcast where artists break down their songs.", website: "https://songexploder.net", verified: false, articleCount: 0 },
  { id: cid("press@tapenotes.co.uk"), name: "Tape Notes", email: "press@tapenotes.co.uk", outlet: "Tape Notes", type: "podcaster", genre: "All Genres, Production", region: "UK", beat: "Music Podcast", bio: "Tape Notes — podcast going inside the recording studio with artists and producers.", website: "https://tapenotes.co.uk", verified: false, articleCount: 0 },
  { id: cid("podcast@hirwayprojects.com"), name: "Hrishikesh Hirway Projects", email: "podcast@hirwayprojects.com", outlet: "Hrishikesh Hirway", type: "podcaster", genre: "All Genres", region: "US", beat: "Music Podcast", bio: "Hrishikesh Hirway — creator of Song Exploder and other music storytelling projects.", website: "https://hirwayprojects.com", verified: false, articleCount: 0 },
  { id: cid("podcast@musicpeoplepod.com"), name: "Music People Podcast", email: "podcast@musicpeoplepod.com", outlet: "Music People", type: "podcaster", genre: "All Genres", region: "US", beat: "Music Podcast", bio: "Music People — interviews with people who make the music industry work.", website: "https://musicpeoplepod.com", verified: false, articleCount: 0 },
  { id: cid("podcast@bandsplain.com"), name: "Bandsplain", email: "podcast@bandsplain.com", outlet: "Bandsplain", type: "podcaster", genre: "All Genres", region: "US", beat: "Music Podcast", bio: "Bandsplain — Yasi Salek deep dives into bands and music history.", website: "https://bandsplain.com", verified: false, articleCount: 0 },
  { id: cid("podcast@soundopinions.org"), name: "Sound Opinions", email: "podcast@soundopinions.org", outlet: "Sound Opinions", type: "podcaster", genre: "Rock, Indie, All Genres", region: "US", beat: "Music Podcast", bio: "Sound Opinions — Jim DeRogatis and Greg Kot's music criticism podcast.", website: "https://soundopinions.org", verified: false, articleCount: 0 },
];

// ─── EXPORT ─────────────────────────────────────────────────────────────────────

export const curatorPodcasterSeedContacts: SeedContact[] = [
  ...youtubeCuratorContacts,
  ...labelCuratorContacts,
  ...platformCuratorContacts,
  ...blogCuratorContacts,
  ...soundcloudCuratorContacts,
  ...additionalCuratorContacts,
  ...majorPodcasterContacts,
  ...productionPodcasterContacts,
  ...genrePodcasterContacts,
  ...interviewPodcasterContacts,
];
