// ══════════════════════════════════════════════════════════════════════════════
// Batch 4B Seed Contacts — 216 contacts across Latin/Reggaeton, Folk/Singer-
// Songwriter, Country, Pop, Hip Hop, and Metal/Rock genres.
// All emails use organizational/role-based patterns.
// ══════════════════════════════════════════════════════════════════════════════

import { SeedContact } from "./seed-radio";

const cid = (e: string) => "seed-4b-" + e.replace(/[@.]/g, "-");

export const batch4bSeedContacts: SeedContact[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // LATIN / REGGAETON (74 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Latin Blogs (25) —
  { id: cid("submissions@tumusiclatina.com"), name: "Tu Musica Latina", email: "submissions@tumusiclatina.com", outlet: "Tu Musica Latina", type: "blog", genre: "Latin, Reggaeton", region: "US", beat: "Latin Music News, New Releases", bio: "Leading Latin music blog covering reggaeton, trap latino, and pop latino.", website: "https://tumusiclatina.com", verified: false, articleCount: 0 },
  { id: cid("submissions@reggaetonworld.com"), name: "Reggaeton World", email: "submissions@reggaetonworld.com", outlet: "Reggaeton World", type: "blog", genre: "Reggaeton", region: "US", beat: "Reggaeton News, Reviews", bio: "Blog dedicated to reggaeton music, culture, and artist features.", website: "https://reggaetonworld.com", verified: false, articleCount: 0 },
  { id: cid("info@elplanetaurban.com"), name: "El Planeta Urban", email: "info@elplanetaurban.com", outlet: "El Planeta Urban", type: "blog", genre: "Latin, Urban", region: "Latin America", beat: "Urban Latin Music, Trap Latino", bio: "Urban Latin music blog covering trap, reggaeton, and emerging artists.", website: "https://elplanetaurban.com", verified: false, articleCount: 0 },
  { id: cid("submissions@flowhotmusic.com"), name: "Flow Hot Music", email: "submissions@flowhotmusic.com", outlet: "Flow Hot Music", type: "blog", genre: "Latin, Reggaeton", region: "Latin America", beat: "Latin Urban Music, Hot Tracks", bio: "Latin music blog spotlighting the hottest urban tracks and new releases.", website: "https://flowhotmusic.com", verified: false, articleCount: 0 },
  { id: cid("press@trapkingzlatino.com"), name: "Trap Kingz Latino", email: "press@trapkingzlatino.com", outlet: "Trap Kingz Latino", type: "blog", genre: "Latin Trap", region: "Latin America", beat: "Latin Trap, Urban Music", bio: "Blog covering Latin trap music, artist profiles, and new drops.", website: "https://trapkingzlatino.com", verified: false, articleCount: 0 },
  { id: cid("editor@urbanlatino.com"), name: "Urban Latino Magazine", email: "editor@urbanlatino.com", outlet: "Urban Latino Magazine", type: "blog", genre: "Latin, Urban", region: "US", beat: "Urban Latino Culture, Music", bio: "Magazine covering urban Latino music, culture, and entertainment.", website: "https://urbanlatino.com", verified: false, articleCount: 0 },
  { id: cid("submissions@labotanamusical.com"), name: "La Botana Musical", email: "submissions@labotanamusical.com", outlet: "La Botana Musical", type: "blog", genre: "Latin, Regional", region: "Mexico", beat: "Latin Music News, Regional Mexican", bio: "Latin music blog covering regional Mexican and urban genres.", website: "https://labotanamusical.com", verified: false, articleCount: 0 },
  { id: cid("info@reggaetononline.com"), name: "Reggaeton Online", email: "info@reggaetononline.com", outlet: "Reggaeton Online", type: "blog", genre: "Reggaeton", region: "Latin America", beat: "Reggaeton, Perreo, Latin Urban", bio: "Online hub for reggaeton music news, videos, and downloads.", website: "https://reggaetononline.com", verified: false, articleCount: 0 },
  { id: cid("editor@latinmusictoday.com"), name: "Latin Music Today", email: "editor@latinmusictoday.com", outlet: "Latin Music Today", type: "blog", genre: "Latin", region: "US", beat: "Latin Music News, Charts", bio: "Daily coverage of Latin music charts, news, and industry updates.", website: "https://latinmusictoday.com", verified: false, articleCount: 0 },
  { id: cid("submissions@tropicalismoblog.com"), name: "Tropicalismo Blog", email: "submissions@tropicalismoblog.com", outlet: "Tropicalismo Blog", type: "blog", genre: "Latin, Tropical", region: "Latin America", beat: "Tropical Music, Latin Fusion", bio: "Blog exploring tropical music, Latin fusion, and world rhythms.", website: "https://tropicalismoblog.com", verified: false, articleCount: 0 },
  { id: cid("info@migentelatina.com"), name: "Mi Gente Latina", email: "info@migentelatina.com", outlet: "Mi Gente Latina", type: "blog", genre: "Latin", region: "US", beat: "Latin Music, Culture", bio: "Latin music and culture blog celebrating the Latino community.", website: "https://migentelatina.com", verified: false, articleCount: 0 },
  { id: cid("editor@mundourbano.com"), name: "Mundo Urbano", email: "editor@mundourbano.com", outlet: "Mundo Urbano", type: "blog", genre: "Latin, Urban", region: "Latin America", beat: "Urban Latin Music, Hip Hop Latino", bio: "Latin urban music blog covering hip hop, reggaeton, and trap.", website: "https://mundourbano.com", verified: false, articleCount: 0 },
  { id: cid("submissions@lacallemusical.com"), name: "La Calle Musical", email: "submissions@lacallemusical.com", outlet: "La Calle Musical", type: "blog", genre: "Latin, Urban", region: "Latin America", beat: "Street Latin Music, Urban Culture", bio: "Blog covering Latin street music culture and urban sounds.", website: "https://lacallemusical.com", verified: false, articleCount: 0 },
  { id: cid("info@perreointenso.com"), name: "Perreo Intenso", email: "info@perreointenso.com", outlet: "Perreo Intenso", type: "blog", genre: "Reggaeton", region: "Latin America", beat: "Reggaeton, Perreo, Club Music", bio: "Reggaeton and perreo blog with club-ready tracks and reviews.", website: "https://perreointenso.com", verified: false, articleCount: 0 },
  { id: cid("editor@ritmolatino.com"), name: "Ritmo Latino", email: "editor@ritmolatino.com", outlet: "Ritmo Latino", type: "blog", genre: "Latin", region: "US", beat: "Latin Rhythms, Dance Music", bio: "Latin music blog focused on rhythms, dance, and cultural features.", website: "https://ritmolatino.com", verified: false, articleCount: 0 },
  { id: cid("submissions@latinbeatmagazine.com"), name: "Latin Beat Magazine", email: "submissions@latinbeatmagazine.com", outlet: "Latin Beat Magazine", type: "blog", genre: "Latin, Jazz", region: "US", beat: "Latin Jazz, Salsa, World Music", bio: "Magazine covering Latin jazz, salsa, and world music.", website: "https://latinbeatmagazine.com", verified: false, articleCount: 0 },
  { id: cid("press@latinmusicwire.com"), name: "Latin Music Wire", email: "press@latinmusicwire.com", outlet: "Latin Music Wire", type: "blog", genre: "Latin", region: "US", beat: "Latin Music Industry News", bio: "Wire service for Latin music industry news and press releases.", website: "https://latinmusicwire.com", verified: false, articleCount: 0 },
  { id: cid("blog@urbano106.com"), name: "Urbano 106 Blog", email: "blog@urbano106.com", outlet: "Urbano 106", type: "blog", genre: "Latin, Urban", region: "Latin America", beat: "Urban Latin Radio Blog", bio: "Blog from Urbano 106 covering Latin urban music and playlists.", website: "https://urbano106.com", verified: false, articleCount: 0 },
  { id: cid("submissions@turumba.com"), name: "Tu Rumba", email: "submissions@turumba.com", outlet: "Tu Rumba", type: "blog", genre: "Latin", region: "Latin America", beat: "Rumba, Salsa, Latin Dance", bio: "Latin dance music blog covering rumba, salsa, and party tracks.", website: "https://turumba.com", verified: false, articleCount: 0 },
  { id: cid("info@latintrending.com"), name: "Latin Trending", email: "info@latintrending.com", outlet: "Latin Trending", type: "blog", genre: "Latin", region: "US", beat: "Trending Latin Music, Viral Hits", bio: "Blog tracking trending Latin music and viral hits.", website: "https://latintrending.com", verified: false, articleCount: 0 },
  { id: cid("editor@salsapower.com"), name: "Salsa Power", email: "editor@salsapower.com", outlet: "Salsa Power", type: "blog", genre: "Salsa", region: "US", beat: "Salsa Music, Dance", bio: "Blog dedicated to salsa music, artists, and dance culture.", website: "https://salsapower.com", verified: false, articleCount: 0 },
  { id: cid("info@cumbiaya.com"), name: "Cumbia Ya", email: "info@cumbiaya.com", outlet: "Cumbia Ya", type: "blog", genre: "Cumbia", region: "Latin America", beat: "Cumbia Music, Culture", bio: "Blog celebrating cumbia music and its cultural roots.", website: "https://cumbiaya.com", verified: false, articleCount: 0 },
  { id: cid("submissions@bachatalife.com"), name: "Bachata Life", email: "submissions@bachatalife.com", outlet: "Bachata Life", type: "blog", genre: "Bachata", region: "US", beat: "Bachata Music, Dance", bio: "Blog covering bachata music, artists, and dance events.", website: "https://bachatalife.com", verified: false, articleCount: 0 },
  { id: cid("editor@merenguemix.com"), name: "Merengue Mix", email: "editor@merenguemix.com", outlet: "Merengue Mix", type: "blog", genre: "Merengue", region: "Latin America", beat: "Merengue Music, Party Mixes", bio: "Blog dedicated to merengue music and party mixes.", website: "https://merenguemix.com", verified: false, articleCount: 0 },
  { id: cid("info@soncubano.com"), name: "Son Cubano", email: "info@soncubano.com", outlet: "Son Cubano", type: "blog", genre: "Cuban, Latin", region: "Cuba", beat: "Cuban Music, Son, Timba", bio: "Blog exploring Cuban music traditions including son, timba, and rumba.", website: "https://soncubano.com", verified: false, articleCount: 0 },

  // — Latin Radio (15) —
  { id: cid("music@lamega.com"), name: "La Mega NYC", email: "music@lamega.com", outlet: "La Mega 97.9", type: "radio", genre: "Latin, Reggaeton", region: "US - New York, NY", beat: "Latin Urban Radio", bio: "New York City's premier Latin urban radio station.", website: "https://lamega.com", verified: false, articleCount: 0 },
  { id: cid("music@mega979.com"), name: "Mega 97.9", email: "music@mega979.com", outlet: "Mega 97.9", type: "radio", genre: "Latin, Reggaeton", region: "US - New York, NY", beat: "Latin Pop, Reggaeton Radio", bio: "NYC Latin radio station playing reggaeton and Latin pop hits.", website: "https://mega979.com", verified: false, articleCount: 0 },
  { id: cid("music@lakalle.com"), name: "La Kalle", email: "music@lakalle.com", outlet: "La Kalle", type: "radio", genre: "Latin, Urban", region: "US", beat: "Latin Urban Radio", bio: "Latin urban radio station featuring reggaeton and Latin trap.", website: "https://lakalle.com", verified: false, articleCount: 0 },
  { id: cid("music@radiolatina.fr"), name: "Radio Latina Paris", email: "music@radiolatina.fr", outlet: "Radio Latina", type: "radio", genre: "Latin", region: "France", beat: "Latin Music, European Latin Radio", bio: "Paris-based Latin music radio station serving the European Latin community.", website: "https://radiolatina.fr", verified: false, articleCount: 0 },
  { id: cid("music@los40.com"), name: "Los 40", email: "music@los40.com", outlet: "Los 40", type: "radio", genre: "Latin, Pop", region: "Spain", beat: "Latin Pop Radio, Charts", bio: "Major Spanish-language radio network covering Latin pop and urban hits.", website: "https://los40.com", verified: false, articleCount: 0 },
  { id: cid("music@tropicanafm.com"), name: "Tropicana FM", email: "music@tropicanafm.com", outlet: "Tropicana FM", type: "radio", genre: "Latin, Tropical", region: "Colombia", beat: "Tropical Music Radio", bio: "Colombian radio station playing tropical, vallenato, and Latin pop.", website: "https://tropicanafm.com", verified: false, articleCount: 0 },
  { id: cid("music@oxigenofm.com"), name: "Oxigeno FM", email: "music@oxigenofm.com", outlet: "Oxigeno FM", type: "radio", genre: "Latin, Pop", region: "Latin America", beat: "Latin Pop Radio", bio: "Latin American radio station playing pop and contemporary hits.", website: "https://oxigenofm.com", verified: false, articleCount: 0 },
  { id: cid("music@wradio.com"), name: "W Radio", email: "music@wradio.com", outlet: "W Radio", type: "radio", genre: "Latin", region: "Mexico", beat: "News, Music, Entertainment", bio: "Major Mexican radio network with music and entertainment programming.", website: "https://wradio.com", verified: false, articleCount: 0 },
  { id: cid("music@lazmx.com"), name: "La Z", email: "music@lazmx.com", outlet: "La Z", type: "radio", genre: "Regional Mexican", region: "Mexico", beat: "Regional Mexican Radio", bio: "Mexican radio station specializing in regional Mexican music.", website: "https://lazmx.com", verified: false, articleCount: 0 },
  { id: cid("music@uforia.com"), name: "Uforia Music", email: "music@uforia.com", outlet: "Uforia", type: "radio", genre: "Latin", region: "US", beat: "Latin Music Platform", bio: "Univision's Latin music platform and radio network.", website: "https://uforia.com", verified: false, articleCount: 0 },
  { id: cid("music@radiodisney.com"), name: "Radio Disney Latin", email: "music@radiodisney.com", outlet: "Radio Disney Latin", type: "radio", genre: "Latin Pop", region: "Latin America", beat: "Latin Pop, Kids Music", bio: "Latin American arm of Radio Disney featuring pop and family-friendly music.", website: "https://radiodisney.com", verified: false, articleCount: 0 },
  { id: cid("music@rumbafm.com"), name: "Rumba FM", email: "music@rumbafm.com", outlet: "Rumba FM", type: "radio", genre: "Latin, Tropical", region: "Venezuela", beat: "Tropical Radio, Salsa", bio: "Venezuelan radio station playing salsa, merengue, and tropical music.", website: "https://rumbafm.com", verified: false, articleCount: 0 },
  { id: cid("music@candelafm.com"), name: "Candela FM", email: "music@candelafm.com", outlet: "Candela FM", type: "radio", genre: "Latin", region: "Latin America", beat: "Latin Hits Radio", bio: "Latin radio station broadcasting popular Latin music hits.", website: "https://candelafm.com", verified: false, articleCount: 0 },
  { id: cid("music@superestrellaradio.com"), name: "Super Estrella Radio", email: "music@superestrellaradio.com", outlet: "Super Estrella", type: "radio", genre: "Regional Mexican, Latin", region: "US", beat: "Regional Mexican Radio", bio: "US-based radio station playing regional Mexican and Latin hits.", website: "https://superestrellaradio.com", verified: false, articleCount: 0 },
  { id: cid("music@radiofiesta.com"), name: "Radio Fiesta", email: "music@radiofiesta.com", outlet: "Radio Fiesta", type: "radio", genre: "Latin", region: "Latin America", beat: "Latin Party Music Radio", bio: "Latin radio station featuring party music, salsa, and reggaeton.", website: "https://radiofiesta.com", verified: false, articleCount: 0 },

  // — Latin Curators (20) —
  { id: cid("curator@vivalatino.co"), name: "Viva Latino Curator", email: "curator@vivalatino.co", outlet: "Viva Latino", type: "curator", genre: "Latin", region: "Global", beat: "Latin Hits Playlist", bio: "Curator of the Viva Latino playlist featuring the biggest Latin tracks.", website: "https://vivalatino.co", verified: false, articleCount: 0 },
  { id: cid("curator@bailareggaeton.co"), name: "Baila Reggaeton Curator", email: "curator@bailareggaeton.co", outlet: "Baila Reggaeton", type: "curator", genre: "Reggaeton", region: "Global", beat: "Reggaeton Playlist", bio: "Playlist curator specializing in reggaeton and perreo tracks.", website: "https://bailareggaeton.co", verified: false, articleCount: 0 },
  { id: cid("curator@latinpoprising.co"), name: "Latin Pop Rising Curator", email: "curator@latinpoprising.co", outlet: "Latin Pop Rising", type: "curator", genre: "Latin Pop", region: "Global", beat: "Emerging Latin Pop", bio: "Curator discovering rising Latin pop artists and new releases.", website: "https://latinpoprising.co", verified: false, articleCount: 0 },
  { id: cid("curator@cafeconlecheplaylist.com"), name: "Cafe Con Leche Curator", email: "curator@cafeconlecheplaylist.com", outlet: "Cafe Con Leche", type: "curator", genre: "Latin", region: "Global", beat: "Chill Latin Music", bio: "Curator of laid-back Latin music playlists for mornings and chill vibes.", website: "https://cafeconlecheplaylist.com", verified: false, articleCount: 0 },
  { id: cid("curator@latinjazzvibes.co"), name: "Latin Jazz Vibes Curator", email: "curator@latinjazzvibes.co", outlet: "Latin Jazz Vibes", type: "curator", genre: "Latin Jazz", region: "Global", beat: "Latin Jazz Playlist", bio: "Curator of Latin jazz playlists blending jazz with Afro-Latin rhythms.", website: "https://latinjazzvibes.co", verified: false, articleCount: 0 },
  { id: cid("curator@bachalovers.co"), name: "Bachata Lovers Curator", email: "curator@bachalovers.co", outlet: "Bachata Lovers", type: "curator", genre: "Bachata", region: "Global", beat: "Bachata Playlist", bio: "Curator of romantic bachata playlists for lovers of the genre.", website: "https://bachalovers.co", verified: false, articleCount: 0 },
  { id: cid("curator@salsaclassics.co"), name: "Salsa Classics Curator", email: "curator@salsaclassics.co", outlet: "Salsa Classics", type: "curator", genre: "Salsa", region: "Global", beat: "Classic Salsa Playlist", bio: "Curator of classic salsa music playlists featuring timeless hits.", website: "https://salsaclassics.co", verified: false, articleCount: 0 },
  { id: cid("curator@cumbiamixplaylist.co"), name: "Cumbia Mix Curator", email: "curator@cumbiamixplaylist.co", outlet: "Cumbia Mix", type: "curator", genre: "Cumbia", region: "Global", beat: "Cumbia Playlist", bio: "Curator of cumbia playlists spanning traditional and modern styles.", website: "https://cumbiamixplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@latinalternative.co"), name: "Latin Alternative Curator", email: "curator@latinalternative.co", outlet: "Latin Alternative", type: "curator", genre: "Latin Alternative", region: "Global", beat: "Latin Alternative Playlist", bio: "Curator of Latin alternative and indie en espanol playlists.", website: "https://latinalternative.co", verified: false, articleCount: 0 },
  { id: cid("curator@corridostumbados.co"), name: "Corridos Tumbados Curator", email: "curator@corridostumbados.co", outlet: "Corridos Tumbados", type: "curator", genre: "Regional Mexican", region: "Global", beat: "Corridos Tumbados Playlist", bio: "Curator of corridos tumbados and modern regional Mexican playlists.", website: "https://corridostumbados.co", verified: false, articleCount: 0 },
  { id: cid("curator@regionalmexicano.co"), name: "Regional Mexicano Curator", email: "curator@regionalmexicano.co", outlet: "Regional Mexicano", type: "curator", genre: "Regional Mexican", region: "Global", beat: "Regional Mexican Playlist", bio: "Curator of regional Mexican music playlists including banda and norteno.", website: "https://regionalmexicano.co", verified: false, articleCount: 0 },
  { id: cid("curator@latinrockplaylist.co"), name: "Latin Rock Curator", email: "curator@latinrockplaylist.co", outlet: "Latin Rock", type: "curator", genre: "Latin Rock", region: "Global", beat: "Latin Rock Playlist", bio: "Curator of Latin rock playlists featuring rock en espanol.", website: "https://latinrockplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@musicatropical.co"), name: "Musica Tropical Curator", email: "curator@musicatropical.co", outlet: "Musica Tropical", type: "curator", genre: "Tropical", region: "Global", beat: "Tropical Music Playlist", bio: "Curator of tropical music playlists with salsa, merengue, and cumbia.", website: "https://musicatropical.co", verified: false, articleCount: 0 },
  { id: cid("curator@latinchillplaylist.co"), name: "Latin Chill Curator", email: "curator@latinchillplaylist.co", outlet: "Latin Chill", type: "curator", genre: "Latin", region: "Global", beat: "Chill Latin Playlist", bio: "Curator of chill Latin playlists for relaxation and study.", website: "https://latinchillplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@latindancecardio.co"), name: "Latin Dance Cardio Curator", email: "curator@latindancecardio.co", outlet: "Latin Dance Cardio", type: "curator", genre: "Latin", region: "Global", beat: "Latin Dance Workout Playlist", bio: "Curator of high-energy Latin dance and cardio workout playlists.", website: "https://latindancecardio.co", verified: false, articleCount: 0 },
  { id: cid("curator@reggaetonviejo.co"), name: "Reggaeton Viejo Curator", email: "curator@reggaetonviejo.co", outlet: "Reggaeton Viejo", type: "curator", genre: "Reggaeton", region: "Global", beat: "Classic Reggaeton Playlist", bio: "Curator of classic reggaeton and old-school perreo playlists.", website: "https://reggaetonviejo.co", verified: false, articleCount: 0 },
  { id: cid("curator@latinhits.co"), name: "Latin Hits Curator", email: "curator@latinhits.co", outlet: "Latin Hits", type: "curator", genre: "Latin", region: "Global", beat: "Top Latin Hits Playlist", bio: "Curator of top Latin hits playlist featuring chart-topping tracks.", website: "https://latinhits.co", verified: false, articleCount: 0 },
  { id: cid("curator@perreomix.co"), name: "Perreo Mix Curator", email: "curator@perreomix.co", outlet: "Perreo Mix", type: "curator", genre: "Reggaeton", region: "Global", beat: "Perreo Mix Playlist", bio: "Curator of perreo mix playlists for clubs and parties.", website: "https://perreomix.co", verified: false, articleCount: 0 },
  { id: cid("curator@latinworkout.co"), name: "Latin Workout Curator", email: "curator@latinworkout.co", outlet: "Latin Workout", type: "curator", genre: "Latin", region: "Global", beat: "Latin Workout Playlist", bio: "Curator of Latin workout playlists for gym and exercise.", website: "https://latinworkout.co", verified: false, articleCount: 0 },
  { id: cid("curator@bossanovaplaylist.co"), name: "Bossa Nova Curator", email: "curator@bossanovaplaylist.co", outlet: "Bossa Nova", type: "curator", genre: "Bossa Nova", region: "Global", beat: "Bossa Nova Playlist", bio: "Curator of bossa nova playlists featuring Brazilian jazz classics.", website: "https://bossanovaplaylist.co", verified: false, articleCount: 0 },

  // — Latin Podcasters (8) —
  { id: cid("podcast@altlatino.org"), name: "Alt Latino NPR", email: "podcast@altlatino.org", outlet: "Alt Latino (NPR)", type: "podcaster", genre: "Latin Alternative", region: "US", beat: "Latin Alternative, Culture", bio: "NPR podcast exploring Latin alternative music and culture.", website: "https://altlatino.org", verified: false, articleCount: 0 },
  { id: cid("show@latinmusicpod.com"), name: "Latin Music Podcast", email: "show@latinmusicpod.com", outlet: "Latin Music Podcast", type: "podcaster", genre: "Latin", region: "US", beat: "Latin Music Interviews, Reviews", bio: "Podcast covering Latin music with artist interviews and album reviews.", website: "https://latinmusicpod.com", verified: false, articleCount: 0 },
  { id: cid("show@reggaetonconperreo.com"), name: "Reggaeton con Perreo", email: "show@reggaetonconperreo.com", outlet: "Reggaeton con Perreo", type: "podcaster", genre: "Reggaeton", region: "Latin America", beat: "Reggaeton Culture, History", bio: "Podcast diving deep into reggaeton culture, history, and new releases.", website: "https://reggaetonconperreo.com", verified: false, articleCount: 0 },
  { id: cid("podcast@billboardlatin.com"), name: "Billboard Latin Podcast", email: "podcast@billboardlatin.com", outlet: "Billboard Latin", type: "podcaster", genre: "Latin", region: "US", beat: "Latin Charts, Industry News", bio: "Billboard's Latin music podcast covering charts and industry trends.", website: "https://billboardlatin.com", verified: false, articleCount: 0 },
  { id: cid("podcast@latingrammy.com"), name: "Latin Grammy Podcast", email: "podcast@latingrammy.com", outlet: "Latin Grammy", type: "podcaster", genre: "Latin", region: "Global", beat: "Latin Grammy Awards, Artist Features", bio: "Official Latin Grammy podcast with artist features and award coverage.", website: "https://latingrammy.com", verified: false, articleCount: 0 },
  { id: cid("show@tropicaliapod.com"), name: "Tropicalia Podcast", email: "show@tropicaliapod.com", outlet: "Tropicalia Podcast", type: "podcaster", genre: "Latin, Tropical", region: "US", beat: "Tropical Music, Latin Culture", bio: "Podcast exploring tropical music, Brazilian sounds, and Latin culture.", website: "https://tropicaliapod.com", verified: false, articleCount: 0 },
  { id: cid("show@musicaurbanapod.com"), name: "Musica Urbana Podcast", email: "show@musicaurbanapod.com", outlet: "Musica Urbana Podcast", type: "podcaster", genre: "Latin, Urban", region: "Latin America", beat: "Urban Latin Music", bio: "Podcast covering the urban Latin music scene and emerging artists.", website: "https://musicaurbanapod.com", verified: false, articleCount: 0 },
  { id: cid("show@ritmopodcast.com"), name: "Ritmo Podcast", email: "show@ritmopodcast.com", outlet: "Ritmo Podcast", type: "podcaster", genre: "Latin", region: "US", beat: "Latin Rhythms, Dance Music", bio: "Podcast celebrating Latin rhythms and dance music culture.", website: "https://ritmopodcast.com", verified: false, articleCount: 0 },

  // — Latin Journalists (6) —
  { id: cid("latin@billboard.com"), name: "Billboard Latin Staff", email: "latin@billboard.com", outlet: "Billboard", type: "journalist", genre: "Latin", region: "US", beat: "Latin Music Charts, Industry", bio: "Billboard's Latin music editorial team covering charts and industry news.", website: "https://billboard.com", verified: false, articleCount: 0 },
  { id: cid("latin@rollingstone.com"), name: "Rolling Stone Latin", email: "latin@rollingstone.com", outlet: "Rolling Stone", type: "journalist", genre: "Latin", region: "US", beat: "Latin Music Reviews, Features", bio: "Rolling Stone's Latin music coverage with reviews and artist features.", website: "https://rollingstone.com", verified: false, articleCount: 0 },
  { id: cid("latin@pitchfork.com"), name: "Pitchfork Latin", email: "latin@pitchfork.com", outlet: "Pitchfork", type: "journalist", genre: "Latin", region: "US", beat: "Latin Music Criticism, Reviews", bio: "Pitchfork's Latin music critics covering reviews and best-of lists.", website: "https://pitchfork.com", verified: false, articleCount: 0 },
  { id: cid("latin@thefader.com"), name: "Fader Latin", email: "latin@thefader.com", outlet: "The Fader", type: "journalist", genre: "Latin", region: "US", beat: "Latin Music, Culture", bio: "The Fader's Latin music coverage and cultural features.", website: "https://thefader.com", verified: false, articleCount: 0 },
  { id: cid("editor@remezcla.com"), name: "Remezcla Journalists", email: "editor@remezcla.com", outlet: "Remezcla", type: "journalist", genre: "Latin", region: "US", beat: "Latin Culture, Music, Film", bio: "Remezcla's editorial team covering Latin music, culture, and film.", website: "https://remezcla.com", verified: false, articleCount: 0 },
  { id: cid("editor@soundsandcolours.com"), name: "Sounds and Colours Writers", email: "editor@soundsandcolours.com", outlet: "Sounds and Colours", type: "journalist", genre: "Latin", region: "UK", beat: "Latin American Music, Arts", bio: "Writers covering Latin American music, arts, and culture.", website: "https://soundsandcolours.com", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // FOLK / SINGER-SONGWRITER (63 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Folk Blogs (22) —
  { id: cid("submissions@folkradio.co.uk"), name: "Folk Radio UK", email: "submissions@folkradio.co.uk", outlet: "Folk Radio UK", type: "blog", genre: "Folk", region: "UK", beat: "Folk Music Reviews, Features", bio: "UK folk music blog with reviews, playlists, and artist features.", website: "https://folkradio.co.uk", verified: false, articleCount: 0 },
  { id: cid("editor@makingmusic.org.uk"), name: "Making Music Magazine", email: "editor@makingmusic.org.uk", outlet: "Making Music", type: "blog", genre: "Folk, Singer-Songwriter", region: "UK", beat: "Songwriting, Music Making", bio: "UK magazine covering songwriting, music making, and folk music.", website: "https://makingmusic.org.uk", verified: false, articleCount: 0 },
  { id: cid("submissions@thesongwriterblog.com"), name: "The Songwriter Blog", email: "submissions@thesongwriterblog.com", outlet: "The Songwriter Blog", type: "blog", genre: "Singer-Songwriter", region: "US", beat: "Songwriting Tips, Artist Features", bio: "Blog dedicated to songwriting craft, tips, and artist interviews.", website: "https://thesongwriterblog.com", verified: false, articleCount: 0 },
  { id: cid("info@songsandstories.com"), name: "Songs and Stories", email: "info@songsandstories.com", outlet: "Songs and Stories", type: "blog", genre: "Folk, Singer-Songwriter", region: "US", beat: "Story-Driven Music, Folk", bio: "Blog exploring the stories behind songs and singer-songwriter craft.", website: "https://songsandstories.com", verified: false, articleCount: 0 },
  { id: cid("submissions@singeruniverse.com"), name: "Singer Universe", email: "submissions@singeruniverse.com", outlet: "Singer Universe", type: "blog", genre: "Singer-Songwriter", region: "US", beat: "Singers, Songwriting Contests", bio: "Online magazine for singers and songwriters with contests and features.", website: "https://singeruniverse.com", verified: false, articleCount: 0 },
  { id: cid("info@hitquarters.com"), name: "Hit Quarters", email: "info@hitquarters.com", outlet: "Hit Quarters", type: "blog", genre: "Singer-Songwriter, Pop", region: "Global", beat: "Music Industry, Songwriting", bio: "Music industry resource for songwriters and music professionals.", website: "https://hitquarters.com", verified: false, articleCount: 0 },
  { id: cid("blog@songtown.com"), name: "SongTown Blog", email: "blog@songtown.com", outlet: "SongTown", type: "blog", genre: "Singer-Songwriter", region: "US - Nashville", beat: "Songwriting Education, Nashville", bio: "Nashville-based songwriting community and education blog.", website: "https://songtown.com", verified: false, articleCount: 0 },
  { id: cid("blog@nashvillesongwriters.com"), name: "NSAI Blog", email: "blog@nashvillesongwriters.com", outlet: "NSAI", type: "blog", genre: "Singer-Songwriter", region: "US - Nashville", beat: "Songwriting Advocacy, Education", bio: "Nashville Songwriters Association International blog and resources.", website: "https://nashvillesongwriters.com", verified: false, articleCount: 0 },
  { id: cid("press@bmi.com"), name: "BMI Songwriter Blog", email: "press@bmi.com", outlet: "BMI", type: "blog", genre: "Singer-Songwriter", region: "US", beat: "Songwriter Features, Industry", bio: "BMI's blog featuring songwriter spotlights and industry news.", website: "https://bmi.com", verified: false, articleCount: 0 },
  { id: cid("press@ascap.com"), name: "ASCAP Blog", email: "press@ascap.com", outlet: "ASCAP", type: "blog", genre: "Singer-Songwriter", region: "US", beat: "Songwriter Features, Rights", bio: "ASCAP's blog covering songwriter features, rights, and events.", website: "https://ascap.com", verified: false, articleCount: 0 },
  { id: cid("submissions@acousticroots.com"), name: "Acoustic Roots", email: "submissions@acousticroots.com", outlet: "Acoustic Roots", type: "blog", genre: "Folk, Acoustic", region: "US", beat: "Acoustic Music, Roots", bio: "Blog covering acoustic and roots music with reviews and features.", website: "https://acousticroots.com", verified: false, articleCount: 0 },
  { id: cid("editor@folkworld.eu"), name: "Folk World", email: "editor@folkworld.eu", outlet: "Folk World", type: "blog", genre: "Folk", region: "Europe", beat: "World Folk Music, Reviews", bio: "European folk music magazine with reviews and festival coverage.", website: "https://folkworld.eu", verified: false, articleCount: 0 },
  { id: cid("submissions@rootsmusiccanada.com"), name: "Roots Music Canada", email: "submissions@rootsmusiccanada.com", outlet: "Roots Music Canada", type: "blog", genre: "Folk, Roots", region: "Canada", beat: "Canadian Roots Music, Folk", bio: "Canadian roots and folk music blog with reviews and artist features.", website: "https://rootsmusiccanada.com", verified: false, articleCount: 0 },
  { id: cid("info@thetallestman.com"), name: "The Tallest Man Blog", email: "info@thetallestman.com", outlet: "The Tallest Man", type: "blog", genre: "Folk, Indie Folk", region: "US", beat: "Indie Folk, Singer-Songwriter", bio: "Blog featuring indie folk and singer-songwriter discoveries.", website: "https://thetallestman.com", verified: false, articleCount: 0 },
  { id: cid("submissions@folkandhoney.com"), name: "Folk and Honey", email: "submissions@folkandhoney.com", outlet: "Folk and Honey", type: "blog", genre: "Folk", region: "US", beat: "Folk Music, Emerging Artists", bio: "Blog discovering folk music and emerging singer-songwriters.", website: "https://folkandhoney.com", verified: false, articleCount: 0 },
  { id: cid("submissions@indiefolkcentral.com"), name: "Indie Folk Central", email: "submissions@indiefolkcentral.com", outlet: "Indie Folk Central", type: "blog", genre: "Indie Folk", region: "US", beat: "Indie Folk Music, Playlists", bio: "Blog curating indie folk music with playlists and reviews.", website: "https://indiefolkcentral.com", verified: false, articleCount: 0 },
  { id: cid("info@acousticcoffeehouse.com"), name: "Acoustic Coffee House", email: "info@acousticcoffeehouse.com", outlet: "Acoustic Coffee House", type: "blog", genre: "Folk, Acoustic", region: "US", beat: "Acoustic Music, Coffeehouse Scene", bio: "Blog celebrating acoustic music and the coffeehouse music scene.", website: "https://acousticcoffeehouse.com", verified: false, articleCount: 0 },
  { id: cid("editor@threechordsandthetruth.com"), name: "Three Chords and the Truth", email: "editor@threechordsandthetruth.com", outlet: "Three Chords and the Truth", type: "blog", genre: "Folk, Americana", region: "US", beat: "Folk, Americana, Roots Music", bio: "Blog covering folk, Americana, and roots music with honest reviews.", website: "https://threechordsandthetruth.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thesongswesing.com"), name: "The Songs We Sing", email: "submissions@thesongswesing.com", outlet: "The Songs We Sing", type: "blog", genre: "Folk, Singer-Songwriter", region: "US", beat: "Song Features, Acoustic Music", bio: "Blog featuring songs and stories from singer-songwriters.", website: "https://thesongswesing.com", verified: false, articleCount: 0 },
  { id: cid("submissions@campfiresongsblog.com"), name: "Campfire Songs Blog", email: "submissions@campfiresongsblog.com", outlet: "Campfire Songs", type: "blog", genre: "Folk", region: "US", beat: "Folk Music, Campfire Acoustic", bio: "Blog curating folk songs perfect for campfire singalongs.", website: "https://campfiresongsblog.com", verified: false, articleCount: 0 },
  { id: cid("info@gatherroundmusic.com"), name: "Gather Round Blog", email: "info@gatherroundmusic.com", outlet: "Gather Round Music", type: "blog", genre: "Folk", region: "US", beat: "Community Folk Music", bio: "Blog bringing together folk music community with features and reviews.", website: "https://gatherroundmusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@theporchsessions.com"), name: "The Porch Sessions", email: "submissions@theporchsessions.com", outlet: "The Porch Sessions", type: "blog", genre: "Folk, Acoustic", region: "US", beat: "Acoustic Sessions, Live Music", bio: "Blog featuring intimate acoustic porch sessions and folk performances.", website: "https://theporchsessions.com", verified: false, articleCount: 0 },

  // — Folk Radio (12) —
  { id: cid("music@wumb.org"), name: "WUMB Radio", email: "music@wumb.org", outlet: "WUMB", type: "radio", genre: "Folk", region: "US - Boston, MA", beat: "Folk, Roots Radio", bio: "Boston-area folk and roots music radio station.", website: "https://wumb.org", verified: false, articleCount: 0 },
  { id: cid("music@celticmusicradio.net"), name: "Celtic Music Radio", email: "music@celticmusicradio.net", outlet: "Celtic Music Radio", type: "radio", genre: "Folk, Celtic", region: "UK - Scotland", beat: "Celtic Folk Radio", bio: "Scottish radio station dedicated to Celtic and folk music.", website: "https://celticmusicradio.net", verified: false, articleCount: 0 },
  { id: cid("music@kvmr.org"), name: "KVMR Folk", email: "music@kvmr.org", outlet: "KVMR", type: "radio", genre: "Folk", region: "US - Nevada City, CA", beat: "Folk, Community Radio", bio: "Community radio station with extensive folk music programming.", website: "https://kvmr.org", verified: false, articleCount: 0 },
  { id: cid("music@weru.org"), name: "WERU Radio", email: "music@weru.org", outlet: "WERU", type: "radio", genre: "Folk", region: "US - Maine", beat: "Community Folk Radio", bio: "Maine community radio station featuring folk and roots music.", website: "https://weru.org", verified: false, articleCount: 0 },
  { id: cid("music@wmky.org"), name: "WMKY Radio", email: "music@wmky.org", outlet: "WMKY", type: "radio", genre: "Folk, Bluegrass", region: "US - Kentucky", beat: "Folk, Bluegrass, Appalachian", bio: "Kentucky public radio with folk, bluegrass, and Appalachian music.", website: "https://wmky.org", verified: false, articleCount: 0 },
  { id: cid("music@wvpe.org"), name: "WVPE Radio", email: "music@wvpe.org", outlet: "WVPE", type: "radio", genre: "Folk", region: "US - Indiana", beat: "Public Folk Radio", bio: "Indiana public radio station with folk and acoustic programming.", website: "https://wvpe.org", verified: false, articleCount: 0 },
  { id: cid("music@wfcr.org"), name: "WFCR Radio", email: "music@wfcr.org", outlet: "WFCR", type: "radio", genre: "Folk", region: "US - Massachusetts", beat: "Public Radio, Folk Music", bio: "Massachusetts public radio with folk music programming.", website: "https://wfcr.org", verified: false, articleCount: 0 },
  { id: cid("music@folkalley.com"), name: "Folk Alley", email: "music@folkalley.com", outlet: "Folk Alley", type: "radio", genre: "Folk", region: "US", beat: "Online Folk Radio", bio: "Online folk radio station and music discovery platform.", website: "https://folkalley.com", verified: false, articleCount: 0 },
  { id: cid("music@kpig.com"), name: "KPIG Radio", email: "music@kpig.com", outlet: "KPIG", type: "radio", genre: "Folk, Americana", region: "US - California", beat: "Folk, Americana, Freeform", bio: "California freeform radio station with folk and Americana programming.", website: "https://kpig.com", verified: false, articleCount: 0 },
  { id: cid("music@krcb.org"), name: "KRCB Radio", email: "music@krcb.org", outlet: "KRCB", type: "radio", genre: "Folk", region: "US - California", beat: "Public Radio, Folk", bio: "Northern California public radio with folk music content.", website: "https://krcb.org", verified: false, articleCount: 0 },
  { id: cid("music@kalw.org"), name: "KALW Folk", email: "music@kalw.org", outlet: "KALW", type: "radio", genre: "Folk", region: "US - San Francisco, CA", beat: "Folk Radio, Community", bio: "San Francisco community radio with folk music programming.", website: "https://kalw.org", verified: false, articleCount: 0 },
  { id: cid("music@wdiy.org"), name: "WDIY Radio", email: "music@wdiy.org", outlet: "WDIY", type: "radio", genre: "Folk", region: "US - Pennsylvania", beat: "Community Radio, Folk", bio: "Pennsylvania community radio featuring folk and acoustic music.", website: "https://wdiy.org", verified: false, articleCount: 0 },

  // — Folk Curators (17) —
  { id: cid("curator@folkandacoustic.co"), name: "Folk & Acoustic Curator", email: "curator@folkandacoustic.co", outlet: "Folk & Acoustic", type: "curator", genre: "Folk, Acoustic", region: "Global", beat: "Folk & Acoustic Playlist", bio: "Curator of folk and acoustic music playlists.", website: "https://folkandacoustic.co", verified: false, articleCount: 0 },
  { id: cid("curator@coffeehouseplaylist.co"), name: "Coffeehouse Playlist Curator", email: "curator@coffeehouseplaylist.co", outlet: "Coffeehouse Playlist", type: "curator", genre: "Folk, Acoustic", region: "Global", beat: "Coffeehouse Music Playlist", bio: "Curator of coffeehouse-vibe acoustic and folk playlists.", website: "https://coffeehouseplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@singersongwriterpicks.co"), name: "Singer-Songwriter Picks Curator", email: "curator@singersongwriterpicks.co", outlet: "Singer-Songwriter Picks", type: "curator", genre: "Singer-Songwriter", region: "Global", beat: "Singer-Songwriter Playlist", bio: "Curator spotlighting the best singer-songwriter tracks.", website: "https://singersongwriterpicks.co", verified: false, articleCount: 0 },
  { id: cid("curator@acousticcovers.co"), name: "Acoustic Covers Curator", email: "curator@acousticcovers.co", outlet: "Acoustic Covers", type: "curator", genre: "Acoustic", region: "Global", beat: "Acoustic Covers Playlist", bio: "Curator of acoustic cover versions and reimagined tracks.", website: "https://acousticcovers.co", verified: false, articleCount: 0 },
  { id: cid("curator@acoustichits.co"), name: "Acoustic Hits Curator", email: "curator@acoustichits.co", outlet: "Acoustic Hits", type: "curator", genre: "Acoustic", region: "Global", beat: "Acoustic Hits Playlist", bio: "Curator of popular acoustic hits and stripped-back favorites.", website: "https://acoustichits.co", verified: false, articleCount: 0 },
  { id: cid("curator@unpluggedplaylist.co"), name: "Unplugged Curator", email: "curator@unpluggedplaylist.co", outlet: "Unplugged", type: "curator", genre: "Acoustic, Folk", region: "Global", beat: "Unplugged Music Playlist", bio: "Curator of unplugged and acoustic music playlists.", website: "https://unpluggedplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@indiefolkplaylist.co"), name: "Indie Folk Playlist Curator", email: "curator@indiefolkplaylist.co", outlet: "Indie Folk Playlist", type: "curator", genre: "Indie Folk", region: "Global", beat: "Indie Folk Playlist", bio: "Curator of indie folk playlists featuring emerging artists.", website: "https://indiefolkplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@yourfavoritecoffeehouse.co"), name: "Your Favorite Coffeehouse Curator", email: "curator@yourfavoritecoffeehouse.co", outlet: "Your Favorite Coffeehouse", type: "curator", genre: "Folk, Acoustic", region: "Global", beat: "Coffeehouse Playlist", bio: "Curator of the ultimate coffeehouse acoustic playlist.", website: "https://yourfavoritecoffeehouse.co", verified: false, articleCount: 0 },
  { id: cid("curator@acousticchill.co"), name: "Acoustic Chill Curator", email: "curator@acousticchill.co", outlet: "Acoustic Chill", type: "curator", genre: "Acoustic", region: "Global", beat: "Chill Acoustic Playlist", bio: "Curator of chill acoustic music for relaxation.", website: "https://acousticchill.co", verified: false, articleCount: 0 },
  { id: cid("curator@freshfolk.co"), name: "Fresh Folk Curator", email: "curator@freshfolk.co", outlet: "Fresh Folk", type: "curator", genre: "Folk", region: "Global", beat: "New Folk Music Playlist", bio: "Curator of fresh folk music discoveries and new releases.", website: "https://freshfolk.co", verified: false, articleCount: 0 },
  { id: cid("curator@mellowfolk.co"), name: "Mellow Folk Curator", email: "curator@mellowfolk.co", outlet: "Mellow Folk", type: "curator", genre: "Folk", region: "Global", beat: "Mellow Folk Playlist", bio: "Curator of mellow and contemplative folk playlists.", website: "https://mellowfolk.co", verified: false, articleCount: 0 },
  { id: cid("curator@campfiresongsplaylist.co"), name: "Campfire Songs Curator", email: "curator@campfiresongsplaylist.co", outlet: "Campfire Songs Playlist", type: "curator", genre: "Folk", region: "Global", beat: "Campfire Songs Playlist", bio: "Curator of campfire-worthy folk and acoustic songs.", website: "https://campfiresongsplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@openmicplaylist.co"), name: "Open Mic Night Curator", email: "curator@openmicplaylist.co", outlet: "Open Mic Night", type: "curator", genre: "Singer-Songwriter", region: "Global", beat: "Open Mic Playlist", bio: "Curator of open mic night vibes and singer-songwriter tracks.", website: "https://openmicplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@gentleacoustic.co"), name: "Gentle Acoustic Curator", email: "curator@gentleacoustic.co", outlet: "Gentle Acoustic", type: "curator", genre: "Acoustic", region: "Global", beat: "Gentle Acoustic Playlist", bio: "Curator of gentle and soothing acoustic playlists.", website: "https://gentleacoustic.co", verified: false, articleCount: 0 },
  { id: cid("curator@morningacoustic.co"), name: "Morning Acoustic Curator", email: "curator@morningacoustic.co", outlet: "Morning Acoustic", type: "curator", genre: "Acoustic, Folk", region: "Global", beat: "Morning Acoustic Playlist", bio: "Curator of morning acoustic playlists to start the day.", website: "https://morningacoustic.co", verified: false, articleCount: 0 },
  { id: cid("curator@storytellersessions.co"), name: "Storyteller Sessions Curator", email: "curator@storytellersessions.co", outlet: "Storyteller Sessions", type: "curator", genre: "Singer-Songwriter", region: "Global", beat: "Storyteller Playlist", bio: "Curator of storytelling singer-songwriter sessions and playlists.", website: "https://storytellersessions.co", verified: false, articleCount: 0 },
  { id: cid("curator@folkrevivalplaylist.co"), name: "Folk Revival Curator", email: "curator@folkrevivalplaylist.co", outlet: "Folk Revival", type: "curator", genre: "Folk", region: "Global", beat: "Folk Revival Playlist", bio: "Curator of folk revival playlists bridging classic and modern folk.", website: "https://folkrevivalplaylist.co", verified: false, articleCount: 0 },

  // — Folk Podcasters (8) —
  { id: cid("show@folkcast.co.uk"), name: "Folkcast", email: "show@folkcast.co.uk", outlet: "Folkcast", type: "podcaster", genre: "Folk", region: "UK", beat: "Folk Music Podcast", bio: "UK folk music podcast featuring new releases and live sessions.", website: "https://folkcast.co.uk", verified: false, articleCount: 0 },
  { id: cid("show@folkmusicpodcast.com"), name: "Folk Music Podcast", email: "show@folkmusicpodcast.com", outlet: "Folk Music Podcast", type: "podcaster", genre: "Folk", region: "US", beat: "Folk Music Interviews, Reviews", bio: "Podcast dedicated to folk music with artist interviews and reviews.", website: "https://folkmusicpodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@thesongwriterpodcast.com"), name: "The Songwriter Podcast", email: "show@thesongwriterpodcast.com", outlet: "The Songwriter Podcast", type: "podcaster", genre: "Singer-Songwriter", region: "US", beat: "Songwriting Craft, Interviews", bio: "Podcast exploring the craft of songwriting with artist conversations.", website: "https://thesongwriterpodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@fretboardjournal.com"), name: "Fretboard Journal Podcast", email: "show@fretboardjournal.com", outlet: "Fretboard Journal", type: "podcaster", genre: "Folk, Acoustic", region: "US", beat: "Guitar, Acoustic Music", bio: "Podcast covering acoustic guitars, luthiers, and folk musicians.", website: "https://fretboardjournal.com", verified: false, articleCount: 0 },
  { id: cid("show@acousticapodcast.com"), name: "Acoustica Podcast", email: "show@acousticapodcast.com", outlet: "Acoustica", type: "podcaster", genre: "Acoustic, Folk", region: "US", beat: "Acoustic Music Podcast", bio: "Podcast featuring acoustic music performances and artist stories.", website: "https://acousticapodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@songcraftpodcast.com"), name: "Songcraft Podcast", email: "show@songcraftpodcast.com", outlet: "Songcraft", type: "podcaster", genre: "Singer-Songwriter", region: "US", beat: "Songwriting Education, Interviews", bio: "Podcast teaching songwriting craft through expert interviews.", website: "https://songcraftpodcast.com", verified: false, articleCount: 0 },
  { id: cid("show@folkonfoot.com"), name: "Folk on Foot Podcast", email: "show@folkonfoot.com", outlet: "Folk on Foot", type: "podcaster", genre: "Folk", region: "UK", beat: "Folk Music, Walking, Nature", bio: "UK podcast combining folk music with walking and nature.", website: "https://folkonfoot.com", verified: false, articleCount: 0 },
  { id: cid("show@thesongwriterspod.com"), name: "The Song Writers Pod", email: "show@thesongwriterspod.com", outlet: "The Song Writers Pod", type: "podcaster", genre: "Singer-Songwriter", region: "US", beat: "Songwriting, Artist Interviews", bio: "Podcast interviewing songwriters about their creative process.", website: "https://thesongwriterspod.com", verified: false, articleCount: 0 },

  // — Folk Journalists (4) —
  { id: cid("reviews@acousticguitar.com"), name: "Acoustic Guitar Reviews", email: "reviews@acousticguitar.com", outlet: "Acoustic Guitar", type: "journalist", genre: "Folk, Acoustic", region: "US", beat: "Acoustic Guitar, Album Reviews", bio: "Acoustic Guitar magazine's review team covering albums and gear.", website: "https://acousticguitar.com", verified: false, articleCount: 0 },
  { id: cid("reviews@folkworld.eu"), name: "Folk World Reviews", email: "reviews@folkworld.eu", outlet: "Folk World", type: "journalist", genre: "Folk", region: "Europe", beat: "Folk Music Reviews", bio: "Folk World magazine's review team covering European and world folk.", website: "https://folkworld.eu", verified: false, articleCount: 0 },
  { id: cid("editor@dirtylinen.com"), name: "Dirty Linen Magazine", email: "editor@dirtylinen.com", outlet: "Dirty Linen", type: "journalist", genre: "Folk", region: "US", beat: "Folk, World Music Reviews", bio: "Magazine covering folk and world music with reviews and features.", website: "https://dirtylinen.com", verified: false, articleCount: 0 },
  { id: cid("editor@singout.org"), name: "Sing Out Magazine", email: "editor@singout.org", outlet: "Sing Out!", type: "journalist", genre: "Folk", region: "US", beat: "Folk Music, Traditions", bio: "Historic folk music magazine preserving and promoting folk traditions.", website: "https://singout.org", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // COUNTRY (18 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Country Blogs (6) —
  { id: cid("editor@thenashnews.com"), name: "The Nash News", email: "editor@thenashnews.com", outlet: "The Nash News", type: "blog", genre: "Country", region: "US - Nashville", beat: "Nashville Country Music News", bio: "Nashville-focused country music news and artist features.", website: "https://thenashnews.com", verified: false, articleCount: 0 },
  { id: cid("submissions@countrymusiclife.com"), name: "Country Music Life", email: "submissions@countrymusiclife.com", outlet: "Country Music Life", type: "blog", genre: "Country", region: "US", beat: "Country Music Lifestyle", bio: "Blog covering country music lifestyle, news, and concert reviews.", website: "https://countrymusiclife.com", verified: false, articleCount: 0 },
  { id: cid("info@countryvibes.com"), name: "Country Vibes Blog", email: "info@countryvibes.com", outlet: "Country Vibes", type: "blog", genre: "Country", region: "US", beat: "Country Music, Vibes", bio: "Blog celebrating the vibes and culture of country music.", website: "https://countryvibes.com", verified: false, articleCount: 0 },
  { id: cid("submissions@countryrockrpt.com"), name: "Country Rock Report", email: "submissions@countryrockrpt.com", outlet: "Country Rock Report", type: "blog", genre: "Country, Rock", region: "US", beat: "Country Rock, Southern Rock", bio: "Blog covering the intersection of country and rock music.", website: "https://countryrockrpt.com", verified: false, articleCount: 0 },
  { id: cid("blog@cmaworld.com"), name: "CMA Blog", email: "blog@cmaworld.com", outlet: "CMA", type: "blog", genre: "Country", region: "US", beat: "CMA Awards, Country Industry", bio: "Country Music Association blog with industry news and award coverage.", website: "https://cmaworld.com", verified: false, articleCount: 0 },
  { id: cid("blog@acmcountry.com"), name: "ACM Blog", email: "blog@acmcountry.com", outlet: "ACM", type: "blog", genre: "Country", region: "US", beat: "ACM Awards, Country Music", bio: "Academy of Country Music blog covering awards and artist features.", website: "https://acmcountry.com", verified: false, articleCount: 0 },

  // — Country Radio (5) —
  { id: cid("music@wkdf.com"), name: "WKDF Nashville", email: "music@wkdf.com", outlet: "WKDF Nashville", type: "radio", genre: "Country", region: "US - Nashville, TN", beat: "Country Radio", bio: "Nashville country radio station playing today's biggest hits.", website: "https://wkdf.com", verified: false, articleCount: 0 },
  { id: cid("music@nashfm.com"), name: "Nash FM", email: "music@nashfm.com", outlet: "Nash FM", type: "radio", genre: "Country", region: "US", beat: "Country Radio Network", bio: "National country radio network playing top country hits.", website: "https://nashfm.com", verified: false, articleCount: 0 },
  { id: cid("music@thebull.com"), name: "The Bull", email: "music@thebull.com", outlet: "The Bull", type: "radio", genre: "Country", region: "US", beat: "Country Radio", bio: "Country radio station known for playing new and classic country.", website: "https://thebull.com", verified: false, articleCount: 0 },
  { id: cid("show@bigdandbubba.com"), name: "Big D & Bubba", email: "show@bigdandbubba.com", outlet: "Big D & Bubba Show", type: "radio", genre: "Country", region: "US - National", beat: "Country Morning Show", bio: "Nationally syndicated country radio morning show.", website: "https://bigdandbubba.com", verified: false, articleCount: 0 },
  { id: cid("music@siriusxm.com"), name: "Highway SiriusXM", email: "music@siriusxm.com", outlet: "The Highway (SiriusXM)", type: "radio", genre: "Country", region: "US - National", beat: "New Country, Satellite Radio", bio: "SiriusXM's new country music channel.", website: "https://siriusxm.com", verified: false, articleCount: 0 },

  // — Country Curators (4) —
  { id: cid("curator@countryhits.co"), name: "Country Hits Curator", email: "curator@countryhits.co", outlet: "Country Hits", type: "curator", genre: "Country", region: "Global", beat: "Country Hits Playlist", bio: "Curator of top country hits playlist.", website: "https://countryhits.co", verified: false, articleCount: 0 },
  { id: cid("curator@countrydrive.co"), name: "Country Drive Curator", email: "curator@countrydrive.co", outlet: "Country Drive", type: "curator", genre: "Country", region: "Global", beat: "Country Driving Playlist", bio: "Curator of country music playlists for road trips and drives.", website: "https://countrydrive.co", verified: false, articleCount: 0 },
  { id: cid("curator@countrywarmth.co"), name: "Country Warmth Curator", email: "curator@countrywarmth.co", outlet: "Country Warmth", type: "curator", genre: "Country", region: "Global", beat: "Warm Country Playlist", bio: "Curator of warm and feel-good country music playlists.", website: "https://countrywarmth.co", verified: false, articleCount: 0 },
  { id: cid("curator@newcountryplaylist.co"), name: "New Country Curator", email: "curator@newcountryplaylist.co", outlet: "New Country", type: "curator", genre: "Country", region: "Global", beat: "New Country Releases Playlist", bio: "Curator of new country music releases playlist.", website: "https://newcountryplaylist.co", verified: false, articleCount: 0 },

  // — Country Podcasters (3) —
  { id: cid("show@bobbybones.com"), name: "The Bobby Bones Show", email: "show@bobbybones.com", outlet: "The Bobby Bones Show", type: "podcaster", genre: "Country", region: "US - National", beat: "Country Music, Entertainment", bio: "Nationally syndicated country music morning show and podcast.", website: "https://bobbybones.com", verified: false, articleCount: 0 },
  { id: cid("podcast@countryfaithpod.com"), name: "Country Faith Podcast", email: "podcast@countryfaithpod.com", outlet: "Country Faith", type: "podcaster", genre: "Country", region: "US", beat: "Country Music, Faith", bio: "Podcast exploring the intersection of country music and faith.", website: "https://countryfaithpod.com", verified: false, articleCount: 0 },
  { id: cid("show@tybentli.com"), name: "Ty Bentli Show", email: "show@tybentli.com", outlet: "Ty Bentli Show", type: "podcaster", genre: "Country", region: "US - National", beat: "Country Radio, Podcast", bio: "Nationally syndicated country radio show and podcast.", website: "https://tybentli.com", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // POP (28 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Pop Blogs (10) —
  { id: cid("submissions@headlineplanet.com"), name: "Headline Planet", email: "submissions@headlineplanet.com", outlet: "Headline Planet", type: "blog", genre: "Pop", region: "US", beat: "Pop Music News, Radio", bio: "Pop music news blog tracking radio airplay and chart performance.", website: "https://headlineplanet.com", verified: false, articleCount: 0 },
  { id: cid("submissions@popwrapped.com"), name: "Pop Wrapped", email: "submissions@popwrapped.com", outlet: "Pop Wrapped", type: "blog", genre: "Pop", region: "US", beat: "Pop Music, Entertainment", bio: "Pop music and entertainment blog with reviews and features.", website: "https://popwrapped.com", verified: false, articleCount: 0 },
  { id: cid("submissions@celebmix.com"), name: "CelebMix", email: "submissions@celebmix.com", outlet: "CelebMix", type: "blog", genre: "Pop", region: "UK", beat: "Pop Music, Celebrity News", bio: "UK-based pop music and celebrity news blog.", website: "https://celebmix.com", verified: false, articleCount: 0 },
  { id: cid("submissions@yourmusicradar.com"), name: "Your Music Radar", email: "submissions@yourmusicradar.com", outlet: "Your Music Radar", type: "blog", genre: "Pop", region: "US", beat: "Pop Music Discovery", bio: "Blog discovering new pop music and emerging artists.", website: "https://yourmusicradar.com", verified: false, articleCount: 0 },
  { id: cid("submissions@renownedforsound.com"), name: "Renowned for Sound", email: "submissions@renownedforsound.com", outlet: "Renowned for Sound", type: "blog", genre: "Pop", region: "Australia", beat: "Pop Music Reviews, Interviews", bio: "Australian pop music blog with reviews and artist interviews.", website: "https://renownedforsound.com", verified: false, articleCount: 0 },
  { id: cid("press@popcrave.com"), name: "Pop Crave Blog", email: "press@popcrave.com", outlet: "Pop Crave", type: "blog", genre: "Pop", region: "US", beat: "Pop Music News, Social Media", bio: "Pop music news blog covering viral moments and chart updates.", website: "https://popcrave.com", verified: false, articleCount: 0 },
  { id: cid("submissions@justrandomthings.com"), name: "Just Random Things", email: "submissions@justrandomthings.com", outlet: "Just Random Things", type: "blog", genre: "Pop", region: "US", beat: "Pop Culture, Music", bio: "Pop culture and music blog with diverse entertainment coverage.", website: "https://justrandomthings.com", verified: false, articleCount: 0 },
  { id: cid("press@axs.com"), name: "AXS Entertainment", email: "press@axs.com", outlet: "AXS", type: "blog", genre: "Pop", region: "US", beat: "Entertainment, Live Events", bio: "Entertainment news blog covering pop music and live events.", website: "https://axs.com", verified: false, articleCount: 0 },
  { id: cid("music@broadwayworld.com"), name: "Broadway World Music", email: "music@broadwayworld.com", outlet: "Broadway World", type: "blog", genre: "Pop, Musical Theater", region: "US", beat: "Pop Music, Broadway", bio: "Music section of Broadway World covering pop and crossover artists.", website: "https://broadwayworld.com", verified: false, articleCount: 0 },
  { id: cid("music@digitaljournal.com"), name: "Digital Journal Music", email: "music@digitaljournal.com", outlet: "Digital Journal", type: "blog", genre: "Pop", region: "US", beat: "Music Reviews, Digital Media", bio: "Digital Journal's music section covering pop reviews and features.", website: "https://digitaljournal.com", verified: false, articleCount: 0 },

  // — Pop Curators (12) —
  { id: cid("curator@teenbeats.co"), name: "Teen Beats Curator", email: "curator@teenbeats.co", outlet: "Teen Beats", type: "curator", genre: "Pop", region: "Global", beat: "Teen Pop Playlist", bio: "Curator of teen pop playlists featuring trending artists.", website: "https://teenbeats.co", verified: false, articleCount: 0 },
  { id: cid("curator@happyhits.co"), name: "Happy Hits Curator", email: "curator@happyhits.co", outlet: "Happy Hits", type: "curator", genre: "Pop", region: "Global", beat: "Feel-Good Pop Playlist", bio: "Curator of feel-good pop hits and upbeat playlists.", website: "https://happyhits.co", verified: false, articleCount: 0 },
  { id: cid("curator@feelinmyself.co"), name: "Feelin Myself Curator", email: "curator@feelinmyself.co", outlet: "Feelin Myself", type: "curator", genre: "Pop", region: "Global", beat: "Confidence Pop Playlist", bio: "Curator of empowering pop playlists for confidence and self-love.", website: "https://feelinmyself.co", verified: false, articleCount: 0 },
  { id: cid("curator@dancepopplaylist.co"), name: "Dance Pop Curator", email: "curator@dancepopplaylist.co", outlet: "Dance Pop", type: "curator", genre: "Pop, Dance", region: "Global", beat: "Dance Pop Playlist", bio: "Curator of dance pop playlists blending pop with dance beats.", website: "https://dancepopplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@electropopplaylist.co"), name: "Electropop Curator", email: "curator@electropopplaylist.co", outlet: "Electropop", type: "curator", genre: "Electropop", region: "Global", beat: "Electropop Playlist", bio: "Curator of electropop playlists with synth-driven pop tracks.", website: "https://electropopplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@dreampopplaylist.co"), name: "Dream Pop Curator", email: "curator@dreampopplaylist.co", outlet: "Dream Pop", type: "curator", genre: "Dream Pop", region: "Global", beat: "Dream Pop Playlist", bio: "Curator of dream pop playlists with ethereal and atmospheric tracks.", website: "https://dreampopplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@summerhits.co"), name: "Summer Hits Curator", email: "curator@summerhits.co", outlet: "Summer Hits", type: "curator", genre: "Pop", region: "Global", beat: "Summer Pop Playlist", bio: "Curator of summer pop hit playlists for sunny days.", website: "https://summerhits.co", verified: false, articleCount: 0 },
  { id: cid("curator@poppunkplaylist.co"), name: "Pop Punk Playlist Curator", email: "curator@poppunkplaylist.co", outlet: "Pop Punk Playlist", type: "curator", genre: "Pop Punk", region: "Global", beat: "Pop Punk Playlist", bio: "Curator of pop punk playlists blending punk energy with pop hooks.", website: "https://poppunkplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@partypop.co"), name: "Party Pop Curator", email: "curator@partypop.co", outlet: "Party Pop", type: "curator", genre: "Pop", region: "Global", beat: "Party Pop Playlist", bio: "Curator of party pop playlists for celebrations and events.", website: "https://partypop.co", verified: false, articleCount: 0 },
  { id: cid("curator@guiltypleasures.co"), name: "Guilty Pleasures Curator", email: "curator@guiltypleasures.co", outlet: "Guilty Pleasures", type: "curator", genre: "Pop", region: "Global", beat: "Guilty Pleasure Pop Playlist", bio: "Curator of guilty pleasure pop hits you secretly love.", website: "https://guiltypleasures.co", verified: false, articleCount: 0 },
  { id: cid("curator@powerpopplaylist.co"), name: "Power Pop Curator", email: "curator@powerpopplaylist.co", outlet: "Power Pop", type: "curator", genre: "Power Pop", region: "Global", beat: "Power Pop Playlist", bio: "Curator of power pop playlists with catchy hooks and harmonies.", website: "https://powerpopplaylist.co", verified: false, articleCount: 0 },
  { id: cid("curator@freshpop.co"), name: "Fresh Pop Curator", email: "curator@freshpop.co", outlet: "Fresh Pop", type: "curator", genre: "Pop", region: "Global", beat: "New Pop Releases Playlist", bio: "Curator of fresh pop releases and new artist discoveries.", website: "https://freshpop.co", verified: false, articleCount: 0 },

  // — Pop Radio (6) —
  { id: cid("music@z100.com"), name: "Z100 NYC", email: "music@z100.com", outlet: "Z100", type: "radio", genre: "Pop", region: "US - New York, NY", beat: "Top 40, Pop Radio", bio: "New York City's hit music station playing top 40 pop.", website: "https://z100.com", verified: false, articleCount: 0 },
  { id: cid("music@kiisfm.com"), name: "KIIS FM LA", email: "music@kiisfm.com", outlet: "KIIS FM", type: "radio", genre: "Pop", region: "US - Los Angeles, CA", beat: "Top 40, Pop Radio", bio: "Los Angeles pop radio station, home of Ryan Seacrest.", website: "https://kiisfm.com", verified: false, articleCount: 0 },
  { id: cid("music@kissfm.com"), name: "KISS FM UK", email: "music@kissfm.com", outlet: "KISS FM", type: "radio", genre: "Pop, Dance", region: "UK", beat: "Pop, Dance Radio", bio: "UK pop and dance radio station playing chart hits.", website: "https://kissfm.com", verified: false, articleCount: 0 },
  { id: cid("music@capitalfm.com"), name: "Capital FM", email: "music@capitalfm.com", outlet: "Capital FM", type: "radio", genre: "Pop", region: "UK", beat: "Pop Radio, Charts", bio: "UK's biggest pop radio station playing the latest hits.", website: "https://capitalfm.com", verified: false, articleCount: 0 },
  { id: cid("music@heart.co.uk"), name: "Heart FM", email: "music@heart.co.uk", outlet: "Heart FM", type: "radio", genre: "Pop", region: "UK", beat: "Pop Radio, Feel-Good Music", bio: "UK radio station playing feel-good pop music.", website: "https://heart.co.uk", verified: false, articleCount: 0 },
  { id: cid("music@ffh.de"), name: "Hit Radio FFH", email: "music@ffh.de", outlet: "Hit Radio FFH", type: "radio", genre: "Pop", region: "Germany", beat: "Pop Radio, German Hits", bio: "German pop radio station playing international and German hits.", website: "https://ffh.de", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // HIP HOP (11 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Hip Hop Blogs (4) —
  { id: cid("submissions@traplorerss.com"), name: "Trap Lore Ross", email: "submissions@traplorerss.com", outlet: "Trap Lore Ross", type: "blog", genre: "Hip Hop, Trap", region: "US", beat: "Trap Music, Hip Hop Stories", bio: "Blog and video platform covering trap music stories and culture.", website: "https://traplorerss.com", verified: false, articleCount: 0 },
  { id: cid("submissions@massappeal.com"), name: "Mass Appeal Blog", email: "submissions@massappeal.com", outlet: "Mass Appeal", type: "blog", genre: "Hip Hop", region: "US", beat: "Hip Hop Culture, Music", bio: "Hip hop culture blog and media company with artist features.", website: "https://massappeal.com", verified: false, articleCount: 0 },
  { id: cid("press@firstavenue.com"), name: "First Avenue Blog", email: "press@firstavenue.com", outlet: "First Avenue", type: "blog", genre: "Hip Hop", region: "US - Minneapolis", beat: "Hip Hop, Live Music", bio: "Iconic Minneapolis venue blog covering hip hop and live music.", website: "https://firstavenue.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thesmokingsection.com"), name: "The Smoking Section", email: "submissions@thesmokingsection.com", outlet: "The Smoking Section", type: "blog", genre: "Hip Hop", region: "US", beat: "Hip Hop News, Reviews", bio: "Hip hop blog covering news, reviews, and underground rap.", website: "https://thesmokingsection.com", verified: false, articleCount: 0 },

  // — Hip Hop Curators (5) —
  { id: cid("curator@mostnecessary.co"), name: "Most Necessary Curator", email: "curator@mostnecessary.co", outlet: "Most Necessary", type: "curator", genre: "Hip Hop", region: "Global", beat: "Hip Hop Essentials Playlist", bio: "Curator of essential hip hop playlists with the hardest tracks.", website: "https://mostnecessary.co", verified: false, articleCount: 0 },
  { id: cid("curator@signedxoxo.co"), name: "Signed XOXO Curator", email: "curator@signedxoxo.co", outlet: "Signed XOXO", type: "curator", genre: "Hip Hop, R&B", region: "Global", beat: "Hip Hop, R&B Playlist", bio: "Curator of hip hop and R&B playlists with a smooth vibe.", website: "https://signedxoxo.co", verified: false, articleCount: 0 },
  { id: cid("curator@goldschool.co"), name: "Gold School Curator", email: "curator@goldschool.co", outlet: "Gold School", type: "curator", genre: "Hip Hop", region: "Global", beat: "Classic Hip Hop Playlist", bio: "Curator of golden-era hip hop and classic rap playlists.", website: "https://goldschool.co", verified: false, articleCount: 0 },
  { id: cid("curator@beatsandbars.co"), name: "Beats & Bars Curator", email: "curator@beatsandbars.co", outlet: "Beats & Bars", type: "curator", genre: "Hip Hop", region: "Global", beat: "Lyrical Hip Hop Playlist", bio: "Curator of lyrical hip hop playlists focused on bars and beats.", website: "https://beatsandbars.co", verified: false, articleCount: 0 },
  { id: cid("curator@undergroundhiphop.co"), name: "Underground Hip Hop Curator", email: "curator@undergroundhiphop.co", outlet: "Underground Hip Hop", type: "curator", genre: "Hip Hop", region: "Global", beat: "Underground Rap Playlist", bio: "Curator of underground hip hop and independent rap playlists.", website: "https://undergroundhiphop.co", verified: false, articleCount: 0 },

  // — Hip Hop Radio (2) —
  { id: cid("music@hot97.com"), name: "Hot 97", email: "music@hot97.com", outlet: "Hot 97", type: "radio", genre: "Hip Hop", region: "US - New York, NY", beat: "Hip Hop Radio", bio: "New York City's iconic hip hop and R&B radio station.", website: "https://hot97.com", verified: false, articleCount: 0 },
  { id: cid("music@power1051.com"), name: "Power 105.1", email: "music@power1051.com", outlet: "Power 105.1", type: "radio", genre: "Hip Hop", region: "US - New York, NY", beat: "Hip Hop, R&B Radio", bio: "NYC hip hop and R&B radio station.", website: "https://power1051.com", verified: false, articleCount: 0 },

  // ══════════════════════════════════════════════════════════════════════════
  // METAL / ROCK (22 contacts)
  // ══════════════════════════════════════════════════════════════════════════

  // — Metal/Rock Blogs (10) —
  { id: cid("submissions@metalutopia.com"), name: "Metal Utopia", email: "submissions@metalutopia.com", outlet: "Metal Utopia", type: "blog", genre: "Metal", region: "Global", beat: "Metal Reviews, Interviews", bio: "Metal music blog with album reviews, interviews, and news.", website: "https://metalutopia.com", verified: false, articleCount: 0 },
  { id: cid("submissions@heavymusichq.com"), name: "Heavy Music HQ", email: "submissions@heavymusichq.com", outlet: "Heavy Music HQ", type: "blog", genre: "Metal, Rock", region: "US", beat: "Heavy Music Reviews", bio: "Blog covering heavy music including metal, hardcore, and rock.", website: "https://heavymusichq.com", verified: false, articleCount: 0 },
  { id: cid("submissions@metalnexus.com"), name: "Metal Nexus", email: "submissions@metalnexus.com", outlet: "Metal Nexus", type: "blog", genre: "Metal", region: "US", beat: "Metal News, Reviews", bio: "Metal music blog with news, reviews, and concert coverage.", website: "https://metalnexus.com", verified: false, articleCount: 0 },
  { id: cid("submissions@wonderboxmetal.com"), name: "Wonderbox Metal", email: "submissions@wonderboxmetal.com", outlet: "Wonderbox Metal", type: "blog", genre: "Metal", region: "UK", beat: "Metal Reviews, Premieres", bio: "UK metal blog featuring reviews, premieres, and interviews.", website: "https://wonderboxmetal.com", verified: false, articleCount: 0 },
  { id: cid("submissions@therazorsedge.com"), name: "The Razor's Edge", email: "submissions@therazorsedge.com", outlet: "The Razor's Edge", type: "blog", genre: "Metal, Rock", region: "US", beat: "Metal, Rock Reviews", bio: "Metal and rock blog with sharp reviews and artist features.", website: "https://therazorsedge.com", verified: false, articleCount: 0 },
  { id: cid("submissions@twoguysmetalreviews.com"), name: "Two Guys Metal Reviews", email: "submissions@twoguysmetalreviews.com", outlet: "Two Guys Metal Reviews", type: "blog", genre: "Metal", region: "US", beat: "Metal Album Reviews", bio: "Independent metal album review blog with honest perspectives.", website: "https://twoguysmetalreviews.com", verified: false, articleCount: 0 },
  { id: cid("submissions@metalwani.com"), name: "Metal Wani", email: "submissions@metalwani.com", outlet: "Metal Wani", type: "blog", genre: "Metal", region: "Global", beat: "Metal News, Reviews", bio: "Global metal music blog with news, reviews, and features.", website: "https://metalwani.com", verified: false, articleCount: 0 },
  { id: cid("submissions@sonicperspectives.com"), name: "Sonic Perspectives", email: "submissions@sonicperspectives.com", outlet: "Sonic Perspectives", type: "blog", genre: "Metal, Progressive Rock", region: "US", beat: "Progressive Metal, Rock Reviews", bio: "Blog covering progressive metal and rock with in-depth reviews.", website: "https://sonicperspectives.com", verified: false, articleCount: 0 },
  { id: cid("submissions@rocksins.com"), name: "Rock Sins", email: "submissions@rocksins.com", outlet: "Rock Sins", type: "blog", genre: "Rock", region: "UK", beat: "Rock Music Reviews, Festivals", bio: "UK rock music blog covering reviews, festivals, and live shows.", website: "https://rocksins.com", verified: false, articleCount: 0 },
  { id: cid("submissions@louderthanwar.com"), name: "Louder Than War Blog", email: "submissions@louderthanwar.com", outlet: "Louder Than War", type: "blog", genre: "Rock, Punk", region: "UK", beat: "Rock, Punk, Alternative Reviews", bio: "UK music blog covering rock, punk, and alternative music.", website: "https://louderthanwar.com", verified: false, articleCount: 0 },

  // — Metal/Rock Curators (7) —
  { id: cid("curator@rockthis.co"), name: "Rock This Curator", email: "curator@rockthis.co", outlet: "Rock This", type: "curator", genre: "Rock", region: "Global", beat: "Rock Playlist", bio: "Curator of rock playlists featuring classic and modern rock.", website: "https://rockthis.co", verified: false, articleCount: 0 },
  { id: cid("curator@newmetaltracks.co"), name: "New Metal Tracks Curator", email: "curator@newmetaltracks.co", outlet: "New Metal Tracks", type: "curator", genre: "Metal", region: "Global", beat: "New Metal Releases Playlist", bio: "Curator of new metal track playlists with the latest releases.", website: "https://newmetaltracks.co", verified: false, articleCount: 0 },
  { id: cid("curator@kickassmetal.co"), name: "Kickass Metal Curator", email: "curator@kickassmetal.co", outlet: "Kickass Metal", type: "curator", genre: "Metal", region: "Global", beat: "Heavy Metal Playlist", bio: "Curator of high-energy metal playlists that kick ass.", website: "https://kickassmetal.co", verified: false, articleCount: 0 },
  { id: cid("curator@rockworkout.co"), name: "Rock Workout Curator", email: "curator@rockworkout.co", outlet: "Rock Workout", type: "curator", genre: "Rock", region: "Global", beat: "Rock Workout Playlist", bio: "Curator of rock workout playlists for the gym.", website: "https://rockworkout.co", verified: false, articleCount: 0 },
  { id: cid("curator@classicrocklegends.co"), name: "Classic Rock Legends Curator", email: "curator@classicrocklegends.co", outlet: "Classic Rock Legends", type: "curator", genre: "Classic Rock", region: "Global", beat: "Classic Rock Playlist", bio: "Curator of classic rock playlists featuring legendary artists.", website: "https://classicrocklegends.co", verified: false, articleCount: 0 },
  { id: cid("curator@metalessentials.co"), name: "Metal Essentials Curator", email: "curator@metalessentials.co", outlet: "Metal Essentials", type: "curator", genre: "Metal", region: "Global", beat: "Essential Metal Playlist", bio: "Curator of essential metal playlists spanning subgenres.", website: "https://metalessentials.co", verified: false, articleCount: 0 },
  { id: cid("curator@hardrockanthems.co"), name: "Hard Rock Anthems Curator", email: "curator@hardrockanthems.co", outlet: "Hard Rock Anthems", type: "curator", genre: "Hard Rock", region: "Global", beat: "Hard Rock Anthems Playlist", bio: "Curator of hard rock anthem playlists with stadium-ready tracks.", website: "https://hardrockanthems.co", verified: false, articleCount: 0 },

  // — Metal/Rock Radio (5) —
  { id: cid("music@siriusxm.com/liquidmetal"), name: "SiriusXM Liquid Metal", email: "music@siriusxm.com/liquidmetal", outlet: "SiriusXM Liquid Metal", type: "radio", genre: "Metal", region: "US - National", beat: "Metal Radio, Satellite", bio: "SiriusXM's dedicated heavy metal radio channel.", website: "https://siriusxm.com", verified: false, articleCount: 0 },
  { id: cid("music@planetrock.com"), name: "Planet Rock", email: "music@planetrock.com", outlet: "Planet Rock", type: "radio", genre: "Rock", region: "UK", beat: "Rock Radio", bio: "UK digital radio station dedicated to rock music.", website: "https://planetrock.com", verified: false, articleCount: 0 },
  { id: cid("music@radiox.co.uk"), name: "Radio X", email: "music@radiox.co.uk", outlet: "Radio X", type: "radio", genre: "Rock, Alternative", region: "UK", beat: "Rock, Alternative Radio", bio: "UK radio station playing rock, alternative, and indie music.", website: "https://radiox.co.uk", verified: false, articleCount: 0 },
  { id: cid("music@kerrangradio.co.uk"), name: "Kerrang Radio", email: "music@kerrangradio.co.uk", outlet: "Kerrang Radio", type: "radio", genre: "Rock, Metal", region: "UK", beat: "Rock, Metal Radio", bio: "UK radio station from the Kerrang brand playing rock and metal.", website: "https://kerrangradio.co.uk", verified: false, articleCount: 0 },
  { id: cid("music@metalexpressradio.com"), name: "Metal Express Radio", email: "music@metalexpressradio.com", outlet: "Metal Express Radio", type: "radio", genre: "Metal", region: "Global", beat: "Online Metal Radio", bio: "Online radio station and review site dedicated to heavy metal.", website: "https://metalexpressradio.com", verified: false, articleCount: 0 },
];
