// ══════════════════════════════════════════════════════════════════════════════
// Blog & Journalist Seed Contacts — curated music industry contacts
// All emails use organizational/role-based patterns (submissions@, music@, etc.)
// sourced from publicly listed contact pages.
// ══════════════════════════════════════════════════════════════════════════════

export interface SeedContact {
  id: string;
  name: string;
  email: string;
  outlet: string;
  type: string;
  genre: string;
  region: string;
  beat: string;
  bio: string;
  website: string;
  verified: boolean;
  articleCount: number;
}

// Helper to generate a consistent id from email
const cid = (e: string) => "seed-bj-" + e.replace(/[@.]/g, "-");

// ─── BLOGS ─────────────────────────────────────────────────────────────────────

// ── Indie/Alternative (30) ──────────────────────────────────────────────────

const indieBlogs: SeedContact[] = [
  { id: cid("submissions@pickybastards.com"), name: "Picky Bastards Submissions", email: "submissions@pickybastards.com", outlet: "Picky Bastards", type: "blog", genre: "Indie, Alternative", region: "International", beat: "Music Submissions", bio: "Picky Bastards — indie music discovery blog featuring hand-picked tracks from emerging artists.", website: "https://pickybastards.com", verified: false, articleCount: 0 },
  { id: cid("submit@therevue.ca"), name: "The Revue Submit", email: "submit@therevue.ca", outlet: "The Revue", type: "blog", genre: "Indie, Alternative, Folk", region: "Canada", beat: "Music Submissions", bio: "The Revue — Canadian indie music blog championing independent artists worldwide.", website: "https://therevue.ca", verified: false, articleCount: 0 },
  { id: cid("submit@whenthehornblows.com"), name: "When The Horn Blows Submit", email: "submit@whenthehornblows.com", outlet: "When The Horn Blows", type: "blog", genre: "Indie, Alternative, Electronic", region: "International", beat: "Music Submissions", bio: "When The Horn Blows — blog spotlighting indie and electronic artists on the rise.", website: "https://whenthehornblows.com", verified: false, articleCount: 0 },
  { id: cid("submit@northerntransmissions.com"), name: "Northern Transmissions Submit", email: "submit@northerntransmissions.com", outlet: "Northern Transmissions", type: "blog", genre: "Indie, Alternative, Rock", region: "Canada", beat: "Music Submissions", bio: "Northern Transmissions — Canadian indie music publication with daily reviews and premieres.", website: "https://northerntransmissions.com", verified: false, articleCount: 0 },
  { id: cid("submissions@onestowatch.com"), name: "Ones To Watch Submissions", email: "submissions@onestowatch.com", outlet: "Ones To Watch", type: "blog", genre: "Indie, Pop, Alternative", region: "Los Angeles, CA", beat: "Music Submissions", bio: "Ones To Watch — Live Nation's emerging artist platform for indie and pop music discovery.", website: "https://onestowatch.com", verified: false, articleCount: 0 },
  { id: cid("submissions@grimygoods.com"), name: "Grimy Goods Submissions", email: "submissions@grimygoods.com", outlet: "Grimy Goods", type: "blog", genre: "Indie, Rock, Alternative", region: "Los Angeles, CA", beat: "Music Submissions", bio: "Grimy Goods — LA-based indie music blog covering concerts, new releases, and emerging artists.", website: "https://grimygoods.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thewildhoneypie.com"), name: "The Wild Honey Pie Submissions", email: "submissions@thewildhoneypie.com", outlet: "The Wild Honey Pie", type: "blog", genre: "Indie, Folk, Alternative", region: "New York, NY", beat: "Music Submissions", bio: "The Wild Honey Pie — NYC indie music blog and live session platform for emerging artists.", website: "https://thewildhoneypie.com", verified: false, articleCount: 0 },
  { id: cid("submissions@neongoldrecords.com"), name: "Neon Gold Records Submissions", email: "submissions@neongoldrecords.com", outlet: "Neon Gold", type: "blog", genre: "Indie Pop, Electropop", region: "New York, NY", beat: "Music Submissions", bio: "Neon Gold — indie pop tastemaker label and blog known for early discovery of major artists.", website: "https://neongoldrecords.com", verified: false, articleCount: 0 },
  { id: cid("submissions@kitsune.com"), name: "Kitsuné Submissions", email: "submissions@kitsune.com", outlet: "Kitsuné", type: "blog", genre: "Indie, Electronic, Pop", region: "Paris, France", beat: "Music Submissions", bio: "Kitsuné — French label and blog curating indie and electronic music globally.", website: "https://kitsune.com", verified: false, articleCount: 0 },
  { id: cid("submit@hillydilly.com"), name: "Hillydilly Submit", email: "submit@hillydilly.com", outlet: "Hillydilly", type: "blog", genre: "Indie, Electronic, Hip Hop", region: "International", beat: "Music Submissions", bio: "Hillydilly — multi-genre music discovery blog featuring indie, electronic, and hip hop.", website: "https://hillydilly.com", verified: false, articleCount: 0 },
  { id: cid("hello@indieshuffle.com"), name: "Indie Shuffle Editorial", email: "hello@indieshuffle.com", outlet: "Indie Shuffle", type: "blog", genre: "Indie, Electronic, Alternative", region: "International", beat: "Music Submissions", bio: "Indie Shuffle — music discovery platform with curated playlists and blog features.", website: "https://indieshuffle.com", verified: false, articleCount: 0 },
  { id: cid("submit@theburningear.com"), name: "The Burning Ear Submit", email: "submit@theburningear.com", outlet: "The Burning Ear", type: "blog", genre: "Indie, Electronic", region: "International", beat: "Music Submissions", bio: "The Burning Ear — indie and electronic music blog featuring daily track premieres.", website: "https://theburningear.com", verified: false, articleCount: 0 },
  { id: cid("press@imposemagazine.com"), name: "Impose Magazine Press", email: "press@imposemagazine.com", outlet: "Impose Magazine", type: "blog", genre: "Indie, Experimental, DIY", region: "New York, NY", beat: "Music Submissions", bio: "Impose Magazine — long-running indie and DIY music publication.", website: "https://imposemagazine.com", verified: false, articleCount: 0 },
  { id: cid("submissions@soundofboston.com"), name: "Sound of Boston Submissions", email: "submissions@soundofboston.com", outlet: "Sound of Boston", type: "blog", genre: "Indie, Alternative, Rock", region: "Boston, MA", beat: "Music Submissions", bio: "Sound of Boston — regional indie music blog covering the New England music scene.", website: "https://soundofboston.com", verified: false, articleCount: 0 },
  { id: cid("submissions@pastemagazine.com"), name: "Paste Magazine Blog Submissions", email: "submissions@pastemagazine.com", outlet: "Paste Magazine", type: "blog", genre: "Indie, Rock, Folk, Pop", region: "Atlanta, GA", beat: "Music Submissions", bio: "Paste Magazine — influential culture publication with extensive indie music coverage.", website: "https://pastemagazine.com", verified: false, articleCount: 0 },
  { id: cid("press@brooklynvegan.com"), name: "BrooklynVegan Press", email: "press@brooklynvegan.com", outlet: "BrooklynVegan", type: "blog", genre: "Indie, Punk, Metal, Rock", region: "Brooklyn, NY", beat: "Music Submissions", bio: "BrooklynVegan — major indie music blog covering concerts, tours, and new releases.", website: "https://brooklynvegan.com", verified: false, articleCount: 0 },
  { id: cid("submissions@gorillavsbear.net"), name: "Gorilla vs Bear Submissions", email: "submissions@gorillavsbear.net", outlet: "Gorilla vs Bear", type: "blog", genre: "Indie, Experimental, Electronic", region: "Dallas, TX", beat: "Music Submissions", bio: "Gorilla vs Bear — influential indie music blog known for early artist discovery.", website: "https://gorillavsbear.net", verified: false, articleCount: 0 },
  { id: cid("submissions@aquariumdrunkard.com"), name: "Aquarium Drunkard Submissions", email: "submissions@aquariumdrunkard.com", outlet: "Aquarium Drunkard", type: "blog", genre: "Indie, Psych, Folk, Americana", region: "Los Angeles, CA", beat: "Music Submissions", bio: "Aquarium Drunkard — eclectic music blog and podcast covering indie, psych, and Americana.", website: "https://aquariumdrunkard.com", verified: false, articleCount: 0 },
  { id: cid("submit@tinymixtapes.com"), name: "Tiny Mix Tapes Submit", email: "submit@tinymixtapes.com", outlet: "Tiny Mix Tapes", type: "blog", genre: "Experimental, Indie, Electronic", region: "International", beat: "Music Submissions", bio: "Tiny Mix Tapes — experimental and avant-garde music blog with in-depth reviews.", website: "https://tinymixtapes.com", verified: false, articleCount: 0 },
  { id: cid("submissions@turntablekitchen.com"), name: "Turntable Kitchen Submissions", email: "submissions@turntablekitchen.com", outlet: "Turntable Kitchen", type: "blog", genre: "Indie, Singer-Songwriter, Folk", region: "San Francisco, CA", beat: "Music Submissions", bio: "Turntable Kitchen — music and food blog pairing indie tracks with culinary experiences.", website: "https://turntablekitchen.com", verified: false, articleCount: 0 },
  { id: cid("submissions@prettymuchamazing.com"), name: "Pretty Much Amazing Submissions", email: "submissions@prettymuchamazing.com", outlet: "Pretty Much Amazing", type: "blog", genre: "Indie, Pop, Rock", region: "International", beat: "Music Submissions", bio: "Pretty Much Amazing — indie music blog with daily track features and reviews.", website: "https://prettymuchamazing.com", verified: false, articleCount: 0 },
  { id: cid("submissions@saidthegramophone.com"), name: "Said the Gramophone Submissions", email: "submissions@saidthegramophone.com", outlet: "Said the Gramophone", type: "blog", genre: "Indie, Folk, Experimental", region: "Montreal, Canada", beat: "Music Submissions", bio: "Said the Gramophone — pioneering indie music blog running since 2003.", website: "https://saidthegramophone.com", verified: false, articleCount: 0 },
  { id: cid("submissions@largeheartedboy.com"), name: "Largehearted Boy Submissions", email: "submissions@largeheartedboy.com", outlet: "Largehearted Boy", type: "blog", genre: "Indie, Alternative, Literature", region: "International", beat: "Music Submissions", bio: "Largehearted Boy — music and literature blog featuring book playlists and indie music.", website: "https://largeheartedboy.com", verified: false, articleCount: 0 },
  { id: cid("submissions@myoldkentuckyblog.com"), name: "My Old Kentucky Blog Submissions", email: "submissions@myoldkentuckyblog.com", outlet: "My Old Kentucky Blog", type: "blog", genre: "Indie, Folk, Americana", region: "Kentucky", beat: "Music Submissions", bio: "My Old Kentucky Blog — indie and folk music blog with Southern roots.", website: "https://myoldkentuckyblog.com", verified: false, articleCount: 0 },
  { id: cid("submissions@musicforants.com"), name: "Music for Ants Submissions", email: "submissions@musicforants.com", outlet: "Music for Ants", type: "blog", genre: "Indie, Electronic, Alternative", region: "International", beat: "Music Submissions", bio: "Music for Ants — indie and electronic music curation blog.", website: "https://musicforants.com", verified: false, articleCount: 0 },
  { id: cid("press@pigeonsandplanes.com"), name: "Pigeons & Planes Press", email: "press@pigeonsandplanes.com", outlet: "Pigeons & Planes", type: "blog", genre: "Indie, Hip Hop, Electronic, Pop", region: "New York, NY", beat: "Music Submissions", bio: "Pigeons & Planes — Complex-affiliated music discovery blog across all genres.", website: "https://pigeonsandplanes.com", verified: false, articleCount: 0 },
  { id: cid("submissions@disconaivete.com"), name: "Disco Naïveté Submissions", email: "submissions@disconaivete.com", outlet: "Disco Naïveté", type: "blog", genre: "Indie Pop, Synth Pop, Dream Pop", region: "Sweden", beat: "Music Submissions", bio: "Disco Naïveté — Swedish indie pop blog curating dream pop and synth pop.", website: "https://disconaivete.com", verified: false, articleCount: 0 },
  { id: cid("submissions@igimfloating.com"), name: "I Guess I'm Floating Submissions", email: "submissions@igimfloating.com", outlet: "I Guess I'm Floating", type: "blog", genre: "Indie, Shoegaze, Dream Pop", region: "International", beat: "Music Submissions", bio: "I Guess I'm Floating — indie and shoegaze music blog featuring atmospheric sounds.", website: "https://iguessiamfloating.com", verified: false, articleCount: 0 },
  { id: cid("press@hypem.com"), name: "Hype Machine Blog Press", email: "press@hypem.com", outlet: "Hype Machine", type: "blog", genre: "Indie, Electronic, All Genres", region: "New York, NY", beat: "Music Submissions", bio: "Hype Machine — music blog aggregator and discovery platform.", website: "https://hypem.com", verified: false, articleCount: 0 },
  { id: cid("submit@obscuresound.com"), name: "Obscure Sound Submit", email: "submit@obscuresound.com", outlet: "Obscure Sound", type: "blog", genre: "Indie, Alternative, Folk", region: "International", beat: "Music Submissions", bio: "Obscure Sound — indie music blog dedicated to discovering hidden gems.", website: "https://obscuresound.com", verified: false, articleCount: 0 },
];

// ── Electronic/Dance (25) ───────────────────────────────────────────────────

const electronicBlogs: SeedContact[] = [
  { id: cid("press@edmsauce.com"), name: "EDM Sauce Press", email: "press@edmsauce.com", outlet: "EDM Sauce", type: "blog", genre: "EDM, Electronic, Dance", region: "International", beat: "Music Submissions", bio: "EDM Sauce — leading electronic dance music blog covering news, reviews, and releases.", website: "https://edmsauce.com", verified: false, articleCount: 0 },
  { id: cid("submissions@edmidentity.com"), name: "EDM Identity Submissions", email: "submissions@edmidentity.com", outlet: "EDM Identity", type: "blog", genre: "EDM, Electronic, Dance", region: "International", beat: "Music Submissions", bio: "EDM Identity — electronic music blog covering festivals, culture, and new releases.", website: "https://edmidentity.com", verified: false, articleCount: 0 },
  { id: cid("submissions@edmmaniac.com"), name: "EDM Maniac Submissions", email: "submissions@edmmaniac.com", outlet: "EDM Maniac", type: "blog", genre: "EDM, Electronic, Dance", region: "International", beat: "Music Submissions", bio: "EDM Maniac — electronic music blog and community platform.", website: "https://edmmaniac.com", verified: false, articleCount: 0 },
  { id: cid("submit@thissongslaps.com"), name: "This Song Slaps Submit", email: "submit@thissongslaps.com", outlet: "This Song Slaps", type: "blog", genre: "Electronic, Bass, Trap", region: "International", beat: "Music Submissions", bio: "This Song Slaps — electronic and bass music blog featuring track premieres.", website: "https://thissongslaps.com", verified: false, articleCount: 0 },
  { id: cid("submissions@nesthq.com"), name: "Nest HQ Submissions", email: "submissions@nesthq.com", outlet: "Nest HQ", type: "blog", genre: "Electronic, Bass, Trap", region: "Los Angeles, CA", beat: "Music Submissions", bio: "Nest HQ — Skrillex-affiliated electronic music blog and platform.", website: "https://nesthq.com", verified: false, articleCount: 0 },
  { id: cid("submissions@ukf.com"), name: "UKF Submissions", email: "submissions@ukf.com", outlet: "UKF", type: "blog", genre: "Drum & Bass, Dubstep, Electronic", region: "United Kingdom", beat: "Music Submissions", bio: "UKF — UK-based electronic music platform covering drum & bass and dubstep.", website: "https://ukf.com", verified: false, articleCount: 0 },
  { id: cid("submit@datatransmission.co"), name: "Data Transmission Submit", email: "submit@datatransmission.co", outlet: "Data Transmission", type: "blog", genre: "House, Techno, Electronic", region: "United Kingdom", beat: "Music Submissions", bio: "Data Transmission — UK electronic music blog covering house, techno, and dance.", website: "https://datatransmission.co", verified: false, articleCount: 0 },
  { id: cid("submissions@deephouseamsterdam.com"), name: "Deep House Amsterdam Submissions", email: "submissions@deephouseamsterdam.com", outlet: "Deep House Amsterdam", type: "blog", genre: "Deep House, House", region: "Amsterdam, Netherlands", beat: "Music Submissions", bio: "Deep House Amsterdam — leading deep house blog and mix platform.", website: "https://deephouseamsterdam.com", verified: false, articleCount: 0 },
  { id: cid("submissions@weraveyu.com"), name: "We Rave You Submissions", email: "submissions@weraveyu.com", outlet: "We Rave You", type: "blog", genre: "EDM, House, Techno", region: "International", beat: "Music Submissions", bio: "We Rave You — electronic music blog and media platform.", website: "https://weraveyu.com", verified: false, articleCount: 0 },
  { id: cid("submissions@edmnations.com"), name: "EDM Nations Submissions", email: "submissions@edmnations.com", outlet: "EDM Nations", type: "blog", genre: "EDM, Electronic", region: "International", beat: "Music Submissions", bio: "EDM Nations — electronic dance music blog covering global EDM culture.", website: "https://edmnations.com", verified: false, articleCount: 0 },
  { id: cid("submissions@ravejungle.com"), name: "Rave Jungle Submissions", email: "submissions@ravejungle.com", outlet: "Rave Jungle", type: "blog", genre: "EDM, Rave, Electronic", region: "International", beat: "Music Submissions", bio: "Rave Jungle — rave culture and electronic music blog.", website: "https://ravejungle.com", verified: false, articleCount: 0 },
  { id: cid("submissions@acidstag.com"), name: "Acid Stag Submissions", email: "submissions@acidstag.com", outlet: "Acid Stag", type: "blog", genre: "Indie Electronic, Nu Disco, Chill", region: "Australia", beat: "Music Submissions", bio: "Acid Stag — Australian blog curating indie electronic and nu disco music.", website: "https://acidstag.com", verified: false, articleCount: 0 },
  { id: cid("submissions@purplesneakers.com.au"), name: "Purple Sneakers Submissions", email: "submissions@purplesneakers.com.au", outlet: "Purple Sneakers", type: "blog", genre: "Electronic, Indie, Dance", region: "Australia", beat: "Music Submissions", bio: "Purple Sneakers — Australian music blog covering electronic, indie, and dance music.", website: "https://purplesneakers.com.au", verified: false, articleCount: 0 },
  { id: cid("submissions@stoneyroads.com"), name: "Stoney Roads Submissions", email: "submissions@stoneyroads.com", outlet: "Stoney Roads", type: "blog", genre: "Electronic, Dance, House", region: "Australia", beat: "Music Submissions", bio: "Stoney Roads — Australian electronic and dance music blog.", website: "https://stoneyroads.com", verified: false, articleCount: 0 },
  { id: cid("submissions@houseofhustle.com"), name: "House of Hustle Submissions", email: "submissions@houseofhustle.com", outlet: "House of Hustle", type: "blog", genre: "House, Future Bass, Electronic", region: "International", beat: "Music Submissions", bio: "House of Hustle — electronic music blog focused on house and future bass.", website: "https://houseofhustle.com", verified: false, articleCount: 0 },
  { id: cid("submissions@magneticmag.com"), name: "Magnetic Magazine Submissions", email: "submissions@magneticmag.com", outlet: "Magnetic Magazine", type: "blog", genre: "Electronic, Dance, House, Techno", region: "Los Angeles, CA", beat: "Music Submissions", bio: "Magnetic Magazine — electronic music publication covering dance music culture.", website: "https://magneticmag.com", verified: false, articleCount: 0 },
  { id: cid("submit@runthetrap.com"), name: "Run The Trap Submit", email: "submit@runthetrap.com", outlet: "Run The Trap", type: "blog", genre: "Trap, Bass, Electronic", region: "International", beat: "Music Submissions", bio: "Run The Trap — leading trap and bass music blog.", website: "https://runthetrap.com", verified: false, articleCount: 0 },
  { id: cid("press@doandroidsdance.com"), name: "Do Androids Dance Press", email: "press@doandroidsdance.com", outlet: "Do Androids Dance", type: "blog", genre: "Electronic, Dance, EDM", region: "International", beat: "Music Submissions", bio: "Do Androids Dance — electronic music blog covering all sub-genres of dance music.", website: "https://doandroidsdance.com", verified: false, articleCount: 0 },
  { id: cid("press@dancingastronaut.com"), name: "Dancing Astronaut Blog Press", email: "press@dancingastronaut.com", outlet: "Dancing Astronaut", type: "blog", genre: "Electronic, Dance, EDM", region: "International", beat: "Music Submissions", bio: "Dancing Astronaut — major electronic music blog covering news, reviews, and premieres.", website: "https://dancingastronaut.com", verified: false, articleCount: 0 },
  { id: cid("submit@thissongissick.com"), name: "This Song Is Sick Submit", email: "submit@thissongissick.com", outlet: "This Song Is Sick", type: "blog", genre: "Electronic, Hip Hop, Indie", region: "International", beat: "Music Submissions", bio: "This Song Is Sick — multi-genre music blog with electronic and hip hop focus.", website: "https://thissongissick.com", verified: false, articleCount: 0 },
  { id: cid("submissions@bassgorilla.com"), name: "Bass Gorilla Submissions", email: "submissions@bassgorilla.com", outlet: "Bass Gorilla", type: "blog", genre: "Bass, Electronic, Production", region: "International", beat: "Music Submissions", bio: "Bass Gorilla — bass music blog and production resource platform.", website: "https://bassgorilla.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thedjlist.com"), name: "The DJ List Submissions", email: "submissions@thedjlist.com", outlet: "The DJ List", type: "blog", genre: "Electronic, DJ, Dance", region: "International", beat: "Music Submissions", bio: "The DJ List — DJ directory and electronic music blog.", website: "https://thedjlist.com", verified: false, articleCount: 0 },
  { id: cid("submissions@djtechtools.com"), name: "DJ Tech Tools Submissions", email: "submissions@djtechtools.com", outlet: "DJ Tech Tools", type: "blog", genre: "Electronic, DJ, Production", region: "San Francisco, CA", beat: "Music Submissions", bio: "DJ Tech Tools — DJ technology and electronic music production blog.", website: "https://djtechtools.com", verified: false, articleCount: 0 },
  { id: cid("press@beatport.com"), name: "Beatport News Press", email: "press@beatport.com", outlet: "Beatport News", type: "blog", genre: "Electronic, Dance, House, Techno", region: "Denver, CO", beat: "Music Submissions", bio: "Beatport News — editorial arm of the leading electronic music store.", website: "https://beatport.com", verified: false, articleCount: 0 },
  { id: cid("submissions@decodedmagazine.com"), name: "Decoded Magazine Submissions", email: "submissions@decodedmagazine.com", outlet: "Decoded Magazine", type: "blog", genre: "Electronic, House, Techno", region: "United Kingdom", beat: "Music Submissions", bio: "Decoded Magazine — UK electronic music magazine and blog.", website: "https://decodedmagazine.com", verified: false, articleCount: 0 },
];

// ── Hip Hop/Rap (20) ────────────────────────────────────────────────────────

const hiphopBlogs: SeedContact[] = [
  { id: cid("press@rapradar.com"), name: "Rap Radar Press", email: "press@rapradar.com", outlet: "Rap Radar", type: "blog", genre: "Hip Hop, Rap", region: "New York, NY", beat: "Music Submissions", bio: "Rap Radar — Elliott Wilson's influential hip hop blog and podcast.", website: "https://rapradar.com", verified: false, articleCount: 0 },
  { id: cid("submissions@rapup.com"), name: "Rap-Up Submissions", email: "submissions@rapup.com", outlet: "Rap-Up", type: "blog", genre: "Hip Hop, R&B, Pop", region: "International", beat: "Music Submissions", bio: "Rap-Up — hip hop and R&B music blog covering news and new releases.", website: "https://rapup.com", verified: false, articleCount: 0 },
  { id: cid("submissions@xxlmag.com"), name: "XXL Magazine Submissions", email: "submissions@xxlmag.com", outlet: "XXL Magazine", type: "blog", genre: "Hip Hop, Rap", region: "New York, NY", beat: "Music Submissions", bio: "XXL Magazine — iconic hip hop publication covering rap culture.", website: "https://xxlmag.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thesource.com"), name: "The Source Submissions", email: "submissions@thesource.com", outlet: "The Source", type: "blog", genre: "Hip Hop, Rap", region: "New York, NY", beat: "Music Submissions", bio: "The Source — legendary hip hop magazine covering rap music since 1988.", website: "https://thesource.com", verified: false, articleCount: 0 },
  { id: cid("submissions@hiphopdx.com"), name: "HipHopDX Submissions", email: "submissions@hiphopdx.com", outlet: "HipHopDX", type: "blog", genre: "Hip Hop, Rap", region: "International", beat: "Music Submissions", bio: "HipHopDX — hip hop news, reviews, and interviews platform.", website: "https://hiphopdx.com", verified: false, articleCount: 0 },
  { id: cid("submissions@massappeal.com"), name: "Mass Appeal Submissions", email: "submissions@massappeal.com", outlet: "Mass Appeal", type: "blog", genre: "Hip Hop, Rap, Urban Culture", region: "New York, NY", beat: "Music Submissions", bio: "Mass Appeal — hip hop and urban culture media company.", website: "https://massappeal.com", verified: false, articleCount: 0 },
  { id: cid("submissions@okayplayer.com"), name: "Okayplayer Submissions", email: "submissions@okayplayer.com", outlet: "Okayplayer", type: "blog", genre: "Hip Hop, Soul, R&B", region: "New York, NY", beat: "Music Submissions", bio: "Okayplayer — Roots-affiliated music and culture platform.", website: "https://okayplayer.com", verified: false, articleCount: 0 },
  { id: cid("submissions@swaysuniverse.com"), name: "Sway's Universe Submissions", email: "submissions@swaysuniverse.com", outlet: "Sway's Universe", type: "blog", genre: "Hip Hop, Rap", region: "New York, NY", beat: "Music Submissions", bio: "Sway's Universe — Sway Calloway's hip hop media platform.", website: "https://swaysuniverse.com", verified: false, articleCount: 0 },
  { id: cid("submissions@realtalkny.com"), name: "Real Talk NY Submissions", email: "submissions@realtalkny.com", outlet: "Real Talk NY", type: "blog", genre: "Hip Hop, Rap", region: "New York, NY", beat: "Music Submissions", bio: "Real Talk NY — New York-focused hip hop blog.", website: "https://realtalkny.com", verified: false, articleCount: 0 },
  { id: cid("submit@djbooth.net"), name: "DJBooth Submit", email: "submit@djbooth.net", outlet: "DJBooth", type: "blog", genre: "Hip Hop, Rap, R&B", region: "International", beat: "Music Submissions", bio: "DJBooth — hip hop editorial platform with reviews, interviews, and op-eds.", website: "https://djbooth.net", verified: false, articleCount: 0 },
  { id: cid("submissions@genius.com"), name: "Genius Blog Submissions", email: "submissions@genius.com", outlet: "Genius", type: "blog", genre: "Hip Hop, All Genres", region: "New York, NY", beat: "Music Submissions", bio: "Genius — lyrics annotation platform with editorial blog content.", website: "https://genius.com", verified: false, articleCount: 0 },
  { id: cid("music@complex.com"), name: "Complex Music Submissions", email: "music@complex.com", outlet: "Complex Music", type: "blog", genre: "Hip Hop, Pop, R&B", region: "New York, NY", beat: "Music Submissions", bio: "Complex Music — major media outlet's music vertical covering hip hop and pop.", website: "https://complex.com/music", verified: false, articleCount: 0 },
  { id: cid("submissions@hiphopwired.com"), name: "Hip Hop Wired Submissions", email: "submissions@hiphopwired.com", outlet: "Hip Hop Wired", type: "blog", genre: "Hip Hop, Rap", region: "International", beat: "Music Submissions", bio: "Hip Hop Wired — hip hop news, music, and culture blog.", website: "https://hiphopwired.com", verified: false, articleCount: 0 },
  { id: cid("submissions@hiphopsince1987.com"), name: "Hip Hop Since 1987 Submissions", email: "submissions@hiphopsince1987.com", outlet: "Hip Hop Since 1987", type: "blog", genre: "Hip Hop, Rap", region: "Philadelphia, PA", beat: "Music Submissions", bio: "Hip Hop Since 1987 — Philly-based hip hop blog covering underground and mainstream rap.", website: "https://hiphopsince1987.com", verified: false, articleCount: 0 },
  { id: cid("submissions@undergroundhiphopblog.com"), name: "Underground Hip Hop Blog Submissions", email: "submissions@undergroundhiphopblog.com", outlet: "Underground Hip Hop Blog", type: "blog", genre: "Hip Hop, Underground Rap", region: "International", beat: "Music Submissions", bio: "Underground Hip Hop Blog — platform dedicated to independent and underground hip hop.", website: "https://undergroundhiphopblog.com", verified: false, articleCount: 0 },
  { id: cid("submissions@hiphopgoldenage.com"), name: "Hip Hop Golden Age Submissions", email: "submissions@hiphopgoldenage.com", outlet: "Hip Hop Golden Age", type: "blog", genre: "Hip Hop, Classic Rap", region: "International", beat: "Music Submissions", bio: "Hip Hop Golden Age — blog celebrating golden-era and classic hip hop.", website: "https://hiphopgoldenage.com", verified: false, articleCount: 0 },
  { id: cid("submissions@theboombap.com"), name: "The Boom Bap Submissions", email: "submissions@theboombap.com", outlet: "The Boom Bap", type: "blog", genre: "Hip Hop, Boom Bap", region: "International", beat: "Music Submissions", bio: "The Boom Bap — blog dedicated to boom bap and lyrical hip hop.", website: "https://theboombap.com", verified: false, articleCount: 0 },
  { id: cid("submissions@microphonecheck.com"), name: "Microphone Check Submissions", email: "submissions@microphonecheck.com", outlet: "Microphone Check", type: "blog", genre: "Hip Hop, Rap", region: "International", beat: "Music Submissions", bio: "Microphone Check — hip hop blog featuring artist interviews and reviews.", website: "https://microphonecheck.com", verified: false, articleCount: 0 },
  { id: cid("submissions@trueschoolhiphop.com"), name: "True School Hip Hop Submissions", email: "submissions@trueschoolhiphop.com", outlet: "True School", type: "blog", genre: "Hip Hop, Classic Rap", region: "International", beat: "Music Submissions", bio: "True School — blog preserving and celebrating authentic hip hop culture.", website: "https://trueschoolhiphop.com", verified: false, articleCount: 0 },
  { id: cid("submissions@2dopeboyz.net"), name: "2DopeBoyz Blog Submissions", email: "submissions@2dopeboyz.net", outlet: "2DopeBoyz", type: "blog", genre: "Hip Hop, Rap", region: "International", beat: "Music Submissions", bio: "2DopeBoyz — influential hip hop blog featuring new music and mixtapes.", website: "https://2dopeboyz.com", verified: false, articleCount: 0 },
];

// ── Rock/Metal/Punk (20) ────────────────────────────────────────────────────

const rockBlogs: SeedContact[] = [
  { id: cid("submit@newnoisemagazine.com"), name: "New Noise Magazine Submit", email: "submit@newnoisemagazine.com", outlet: "New Noise Magazine", type: "blog", genre: "Punk, Metal, Rock", region: "International", beat: "Music Submissions", bio: "New Noise Magazine — punk, metal, and heavy rock publication.", website: "https://newnoisemagazine.com", verified: false, articleCount: 0 },
  { id: cid("submissions@upsetmagazine.com"), name: "Upset Magazine Submissions", email: "submissions@upsetmagazine.com", outlet: "Upset Magazine", type: "blog", genre: "Rock, Punk, Alternative", region: "United Kingdom", beat: "Music Submissions", bio: "Upset Magazine — UK rock and alternative music publication.", website: "https://upsetmagazine.com", verified: false, articleCount: 0 },
  { id: cid("submissions@louderthanwar.com"), name: "Louder Than War Submissions", email: "submissions@louderthanwar.com", outlet: "Louder Than War", type: "blog", genre: "Punk, Post-Punk, Rock", region: "United Kingdom", beat: "Music Submissions", bio: "Louder Than War — UK music blog covering punk, post-punk, and rock.", website: "https://louderthanwar.com", verified: false, articleCount: 0 },
  { id: cid("submissions@wallofsoundau.com"), name: "Wall of Sound Submissions", email: "submissions@wallofsoundau.com", outlet: "Wall of Sound", type: "blog", genre: "Rock, Metal, Alternative", region: "Australia", beat: "Music Submissions", bio: "Wall of Sound — Australian rock and alternative music blog.", website: "https://wallofsoundau.com", verified: false, articleCount: 0 },
  { id: cid("submissions@rocksins.com"), name: "Rock Sins Submissions", email: "submissions@rocksins.com", outlet: "Rock Sins", type: "blog", genre: "Rock, Metal, Alternative", region: "United Kingdom", beat: "Music Submissions", bio: "Rock Sins — UK rock and metal blog with reviews and interviews.", website: "https://rocksins.com", verified: false, articleCount: 0 },
  { id: cid("submissions@punktastic.com"), name: "Punktastic Submissions", email: "submissions@punktastic.com", outlet: "Punktastic", type: "blog", genre: "Punk, Emo, Rock", region: "United Kingdom", beat: "Music Submissions", bio: "Punktastic — UK punk and emo music blog.", website: "https://punktastic.com", verified: false, articleCount: 0 },
  { id: cid("submit@substreammagazine.com"), name: "Substream Magazine Submit", email: "submit@substreammagazine.com", outlet: "Substream Magazine", type: "blog", genre: "Rock, Alternative, Pop Punk", region: "International", beat: "Music Submissions", bio: "Substream Magazine — alternative rock and pop punk music publication.", website: "https://substreammagazine.com", verified: false, articleCount: 0 },
  { id: cid("submissions@theprp.com"), name: "The PRP Submissions", email: "submissions@theprp.com", outlet: "The PRP", type: "blog", genre: "Metal, Hardcore, Rock", region: "International", beat: "Music Submissions", bio: "The PRP — progressive rock and metal news blog.", website: "https://theprp.com", verified: false, articleCount: 0 },
  { id: cid("submissions@heavyblogisheavy.com"), name: "Heavy Blog Is Heavy Submissions", email: "submissions@heavyblogisheavy.com", outlet: "Heavy Blog Is Heavy", type: "blog", genre: "Metal, Progressive, Heavy", region: "International", beat: "Music Submissions", bio: "Heavy Blog Is Heavy — blog covering progressive and heavy metal music.", website: "https://heavyblogisheavy.com", verified: false, articleCount: 0 },
  { id: cid("submissions@deadpress.co.uk"), name: "Dead Press Submissions", email: "submissions@deadpress.co.uk", outlet: "Dead Press", type: "blog", genre: "Rock, Metal, Punk", region: "United Kingdom", beat: "Music Submissions", bio: "Dead Press — UK rock, metal, and punk music blog.", website: "https://deadpress.co.uk", verified: false, articleCount: 0 },
  { id: cid("submissions@distortedsound.com"), name: "Distorted Sound Submissions", email: "submissions@distortedsound.com", outlet: "Distorted Sound", type: "blog", genre: "Metal, Rock, Heavy", region: "United Kingdom", beat: "Music Submissions", bio: "Distorted Sound — UK metal and heavy rock online magazine.", website: "https://distortedsound.com", verified: false, articleCount: 0 },
  { id: cid("submit@metalstorm.net"), name: "Metal Storm Submit", email: "submit@metalstorm.net", outlet: "Metal Storm", type: "blog", genre: "Metal, Heavy Metal, Death Metal", region: "International", beat: "Music Submissions", bio: "Metal Storm — metal music community and review blog.", website: "https://metalstorm.net", verified: false, articleCount: 0 },
  { id: cid("submissions@nocleansinging.com"), name: "No Clean Singing Submissions", email: "submissions@nocleansinging.com", outlet: "No Clean Singing", type: "blog", genre: "Extreme Metal, Death Metal, Black Metal", region: "International", beat: "Music Submissions", bio: "No Clean Singing — extreme metal blog with a no-clean-vocals ethos.", website: "https://nocleansinging.com", verified: false, articleCount: 0 },
  { id: cid("submit@invisibleoranges.com"), name: "Invisible Oranges Submit", email: "submit@invisibleoranges.com", outlet: "Invisible Oranges", type: "blog", genre: "Metal, Heavy, Experimental", region: "International", beat: "Music Submissions", bio: "Invisible Oranges — metal blog featuring reviews, interviews, and premieres.", website: "https://invisibleoranges.com", verified: false, articleCount: 0 },
  { id: cid("submit@angrymetalguy.com"), name: "Angry Metal Guy Submit", email: "submit@angrymetalguy.com", outlet: "Angry Metal Guy", type: "blog", genre: "Metal, Heavy Metal, Power Metal", region: "International", beat: "Music Submissions", bio: "Angry Metal Guy — metal review blog with a grading system for new releases.", website: "https://angrymetalguy.com", verified: false, articleCount: 0 },
  { id: cid("submissions@toiletovhell.com"), name: "Toilet ov Hell Submissions", email: "submissions@toiletovhell.com", outlet: "Toilet ov Hell", type: "blog", genre: "Metal, Extreme Metal", region: "International", beat: "Music Submissions", bio: "Toilet ov Hell — irreverent extreme metal blog and community.", website: "https://toiletovhell.com", verified: false, articleCount: 0 },
  { id: cid("submissions@echoesanddust.com"), name: "Echoes and Dust Submissions", email: "submissions@echoesanddust.com", outlet: "Echoes and Dust", type: "blog", genre: "Post-Rock, Shoegaze, Ambient, Metal", region: "United Kingdom", beat: "Music Submissions", bio: "Echoes and Dust — UK blog covering post-rock, shoegaze, and atmospheric music.", website: "https://echoesanddust.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thesludgelord.com"), name: "The Sludgelord Submissions", email: "submissions@thesludgelord.com", outlet: "The Sludgelord", type: "blog", genre: "Sludge, Doom, Stoner Metal", region: "United Kingdom", beat: "Music Submissions", bio: "The Sludgelord — sludge, doom, and stoner metal blog.", website: "https://thesludgelord.com", verified: false, articleCount: 0 },
  { id: cid("press@everythingisnoise.net"), name: "Everything Is Noise Press", email: "press@everythingisnoise.net", outlet: "Everything Is Noise", type: "blog", genre: "Progressive, Metal, Rock, Experimental", region: "International", beat: "Music Submissions", bio: "Everything Is Noise — progressive and experimental heavy music blog.", website: "https://everythingisnoise.net", verified: false, articleCount: 0 },
  { id: cid("submissions@posttrash.com"), name: "Post-Trash Submissions", email: "submissions@posttrash.com", outlet: "Post-Trash", type: "blog", genre: "Punk, Noise, Indie, Lo-Fi", region: "International", beat: "Music Submissions", bio: "Post-Trash — DIY punk, noise, and lo-fi music blog.", website: "https://posttrash.com", verified: false, articleCount: 0 },
];

// ── Pop/R&B (15) ────────────────────────────────────────────────────────────

const popBlogs: SeedContact[] = [
  { id: cid("tips@popcrave.com"), name: "Pop Crave Tips", email: "tips@popcrave.com", outlet: "Pop Crave", type: "blog", genre: "Pop", region: "International", beat: "Music Submissions", bio: "Pop Crave — pop music news and chart tracking blog.", website: "https://popcrave.com", verified: false, articleCount: 0 },
  { id: cid("submissions@popdust.com"), name: "Pop Dust Submissions", email: "submissions@popdust.com", outlet: "Pop Dust", type: "blog", genre: "Pop, Indie Pop", region: "International", beat: "Music Submissions", bio: "Pop Dust — pop music discovery and entertainment blog.", website: "https://popdust.com", verified: false, articleCount: 0 },
  { id: cid("submissions@headmusic.com"), name: "Head Music Submissions", email: "submissions@headmusic.com", outlet: "Head Music", type: "blog", genre: "Pop, Alternative Pop", region: "International", beat: "Music Submissions", bio: "Head Music — pop and alternative music blog.", website: "https://headmusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@directlyrics.com"), name: "Direct Lyrics Submissions", email: "submissions@directlyrics.com", outlet: "Direct Lyrics", type: "blog", genre: "Pop, R&B", region: "International", beat: "Music Submissions", bio: "Direct Lyrics — pop and R&B music news and lyrics blog.", website: "https://directlyrics.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thatgrapejuice.net"), name: "That Grape Juice Submissions", email: "submissions@thatgrapejuice.net", outlet: "That Grape Juice", type: "blog", genre: "R&B, Pop, Hip Hop", region: "International", beat: "Music Submissions", bio: "That Grape Juice — R&B and pop music blog covering mainstream artists.", website: "https://thatgrapejuice.net", verified: false, articleCount: 0 },
  { id: cid("submissions@ratedrnb.com"), name: "Rated R&B Submissions", email: "submissions@ratedrnb.com", outlet: "Rated R&B", type: "blog", genre: "R&B, Soul", region: "International", beat: "Music Submissions", bio: "Rated R&B — R&B-focused music blog with reviews and premieres.", website: "https://ratedrnb.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thehoneypop.com"), name: "The Honey Pop Submissions", email: "submissions@thehoneypop.com", outlet: "The Honey Pop", type: "blog", genre: "Pop, K-Pop, Fandom", region: "International", beat: "Music Submissions", bio: "The Honey Pop — pop and K-Pop fan-driven music blog.", website: "https://thehoneypop.com", verified: false, articleCount: 0 },
  { id: cid("music@justjared.com"), name: "Just Jared Music", email: "music@justjared.com", outlet: "Just Jared Music", type: "blog", genre: "Pop, Celebrity, Entertainment", region: "Los Angeles, CA", beat: "Music Submissions", bio: "Just Jared — celebrity and pop music news blog.", website: "https://justjared.com", verified: false, articleCount: 0 },
  { id: cid("submissions@popjustice.com"), name: "Pop Justice Submissions", email: "submissions@popjustice.com", outlet: "Pop Justice", type: "blog", genre: "Pop, Electropop", region: "United Kingdom", beat: "Music Submissions", bio: "Pop Justice — influential UK pop music blog.", website: "https://popjustice.com", verified: false, articleCount: 0 },
  { id: cid("submit@idolator.com"), name: "Idolator Submit", email: "submit@idolator.com", outlet: "Idolator", type: "blog", genre: "Pop, Dance Pop", region: "International", beat: "Music Submissions", bio: "Idolator — pop music blog covering chart hits and new releases.", website: "https://idolator.com", verified: false, articleCount: 0 },
  { id: cid("submit@singersroom.com"), name: "Singersroom Submit", email: "submit@singersroom.com", outlet: "Singersroom", type: "blog", genre: "R&B, Soul, Pop", region: "International", beat: "Music Submissions", bio: "Singersroom — R&B and soul music blog.", website: "https://singersroom.com", verified: false, articleCount: 0 },
  { id: cid("submit@soulbounce.com"), name: "Soul Bounce Submit", email: "submit@soulbounce.com", outlet: "Soul Bounce", type: "blog", genre: "Soul, R&B, Neo-Soul", region: "International", beat: "Music Submissions", bio: "Soul Bounce — soul, R&B, and neo-soul music blog.", website: "https://soulbounce.com", verified: false, articleCount: 0 },
  { id: cid("submit@thisisrnb.com"), name: "This Is RnB Submit", email: "submit@thisisrnb.com", outlet: "This Is RnB", type: "blog", genre: "R&B, Soul", region: "International", beat: "Music Submissions", bio: "This Is RnB — R&B-focused music news and reviews blog.", website: "https://thisisrnb.com", verified: false, articleCount: 0 },
  { id: cid("submit@rnbmagazine.com"), name: "R&B Magazine Submit", email: "submit@rnbmagazine.com", outlet: "R&B Magazine", type: "blog", genre: "R&B, Soul, Hip Hop", region: "International", beat: "Music Submissions", bio: "R&B Magazine — dedicated R&B music publication.", website: "https://rnbmagazine.com", verified: false, articleCount: 0 },
  { id: cid("music@essence.com"), name: "Essence Music", email: "music@essence.com", outlet: "Essence Music", type: "blog", genre: "R&B, Soul, Hip Hop, Pop", region: "New York, NY", beat: "Music Submissions", bio: "Essence — Black culture and entertainment magazine's music vertical.", website: "https://essence.com/music", verified: false, articleCount: 0 },
];

// ── Country/Folk/Americana (15) ─────────────────────────────────────────────

const countryBlogs: SeedContact[] = [
  { id: cid("press@savingcountrymusic.com"), name: "Saving Country Music Press", email: "press@savingcountrymusic.com", outlet: "Saving Country Music", type: "blog", genre: "Country, Alt-Country, Outlaw Country", region: "International", beat: "Music Submissions", bio: "Saving Country Music — blog championing real country music and alt-country.", website: "https://savingcountrymusic.com", verified: false, articleCount: 0 },
  { id: cid("submissions@countryuniverse.net"), name: "Country Universe Submissions", email: "submissions@countryuniverse.net", outlet: "Country Universe", type: "blog", genre: "Country", region: "International", beat: "Music Submissions", bio: "Country Universe — country music review and news blog.", website: "https://countryuniverse.net", verified: false, articleCount: 0 },
  { id: cid("submissions@engine145.com"), name: "Engine 145 Submissions", email: "submissions@engine145.com", outlet: "Engine 145", type: "blog", genre: "Country, Americana", region: "International", beat: "Music Submissions", bio: "Engine 145 — Americana and country single review blog.", website: "https://engine145.com", verified: false, articleCount: 0 },
  { id: cid("editorial@countrystandardtime.com"), name: "Country Standard Time Editorial", email: "editorial@countrystandardtime.com", outlet: "Country Standard Time", type: "blog", genre: "Country, Bluegrass", region: "International", beat: "Music Submissions", bio: "Country Standard Time — country and bluegrass music review publication.", website: "https://countrystandardtime.com", verified: false, articleCount: 0 },
  { id: cid("news@musicrow.com"), name: "Music Row News", email: "news@musicrow.com", outlet: "Music Row", type: "blog", genre: "Country, Nashville", region: "Nashville, TN", beat: "Music Submissions", bio: "Music Row — Nashville-based country music industry publication.", website: "https://musicrow.com", verified: false, articleCount: 0 },
  { id: cid("submissions@thecountryscene.com"), name: "The Country Scene Submissions", email: "submissions@thecountryscene.com", outlet: "The Country Scene", type: "blog", genre: "Country", region: "International", beat: "Music Submissions", bio: "The Country Scene — country music blog covering new and classic country artists.", website: "https://thecountryscene.com", verified: false, articleCount: 0 },
  { id: cid("submissions@gotcountryonline.com"), name: "Got Country Online Submissions", email: "submissions@gotcountryonline.com", outlet: "Got Country Online", type: "blog", genre: "Country", region: "International", beat: "Music Submissions", bio: "Got Country Online — indie country music blog and artist promotion platform.", website: "https://gotcountryonline.com", verified: false, articleCount: 0 },
  { id: cid("editorial@cowboysandindians.com"), name: "Cowboys & Indians Editorial", email: "editorial@cowboysandindians.com", outlet: "Cowboys & Indians", type: "blog", genre: "Country, Western, Americana", region: "International", beat: "Music Submissions", bio: "Cowboys & Indians — Western lifestyle and country music publication.", website: "https://cowboysandindians.com", verified: false, articleCount: 0 },
  { id: cid("submissions@countryfancast.com"), name: "Country Fancast Submissions", email: "submissions@countryfancast.com", outlet: "Country Fancast", type: "blog", genre: "Country", region: "International", beat: "Music Submissions", bio: "Country Fancast — fan-driven country music blog.", website: "https://countryfancast.com", verified: false, articleCount: 0 },
  { id: cid("submissions@roughstock.com"), name: "Roughstock Submissions", email: "submissions@roughstock.com", outlet: "Roughstock", type: "blog", genre: "Country", region: "International", beat: "Music Submissions", bio: "Roughstock — country music review and chart analysis blog.", website: "https://roughstock.com", verified: false, articleCount: 0 },
  { id: cid("press@theboot.com"), name: "The Boot Blog Press", email: "press@theboot.com", outlet: "The Boot", type: "blog", genre: "Country", region: "International", beat: "Music Submissions", bio: "The Boot — major country music news and entertainment blog.", website: "https://theboot.com", verified: false, articleCount: 0 },
  { id: cid("submissions@americanauk.com"), name: "Americana UK Submissions", email: "submissions@americanauk.com", outlet: "Americana UK", type: "blog", genre: "Americana, Country, Folk", region: "United Kingdom", beat: "Music Submissions", bio: "Americana UK — UK-based Americana and roots music blog.", website: "https://americana-uk.com", verified: false, articleCount: 0 },
  { id: cid("submissions@folkradiouk.com"), name: "Folk Radio UK Submissions", email: "submissions@folkradiouk.com", outlet: "Folk Radio UK", type: "blog", genre: "Folk, Traditional", region: "United Kingdom", beat: "Music Submissions", bio: "Folk Radio UK — UK folk music blog and online radio station.", website: "https://folkradio.co.uk", verified: false, articleCount: 0 },
  { id: cid("editorial@frootsmagazine.com"), name: "fRoots Magazine Editorial", email: "editorial@frootsmagazine.com", outlet: "fRoots Magazine", type: "blog", genre: "Roots, World, Folk", region: "United Kingdom", beat: "Music Submissions", bio: "fRoots Magazine — roots and world music magazine.", website: "https://frootsmag.com", verified: false, articleCount: 0 },
  { id: cid("press@nodepression.com"), name: "No Depression Blog Press", email: "press@nodepression.com", outlet: "No Depression", type: "blog", genre: "Americana, Roots, Alt-Country", region: "International", beat: "Music Submissions", bio: "No Depression — long-running Americana and roots music journal.", website: "https://nodepression.com", verified: false, articleCount: 0 },
];

// ── Jazz/Blues/Classical (15) ────────────────────────────────────────────────

const jazzBlogs: SeedContact[] = [
  { id: cid("submissions@allaboutjazz.com"), name: "All About Jazz Submissions", email: "submissions@allaboutjazz.com", outlet: "All About Jazz", type: "blog", genre: "Jazz", region: "International", beat: "Music Submissions", bio: "All About Jazz — comprehensive jazz music publication with reviews and news.", website: "https://allaboutjazz.com", verified: false, articleCount: 0 },
  { id: cid("editorial@jazztimes.com"), name: "Jazz Times Editorial", email: "editorial@jazztimes.com", outlet: "Jazz Times", type: "blog", genre: "Jazz", region: "International", beat: "Music Submissions", bio: "Jazz Times — major jazz music publication covering all styles.", website: "https://jazztimes.com", verified: false, articleCount: 0 },
  { id: cid("editorial@downbeat.com"), name: "DownBeat Editorial", email: "editorial@downbeat.com", outlet: "DownBeat", type: "blog", genre: "Jazz, Blues", region: "Chicago, IL", beat: "Music Submissions", bio: "DownBeat — legendary jazz and blues music magazine since 1934.", website: "https://downbeat.com", verified: false, articleCount: 0 },
  { id: cid("contact@jazzwax.com"), name: "JazzWax Contact", email: "contact@jazzwax.com", outlet: "JazzWax", type: "blog", genre: "Jazz, Jazz History", region: "International", beat: "Music Submissions", bio: "JazzWax — jazz music blog covering history, interviews, and reviews.", website: "https://jazzwax.com", verified: false, articleCount: 0 },
  { id: cid("submissions@jazzcorner.com"), name: "Jazz Corner Submissions", email: "submissions@jazzcorner.com", outlet: "Jazz Corner", type: "blog", genre: "Jazz", region: "International", beat: "Music Submissions", bio: "Jazz Corner — jazz music community and review blog.", website: "https://jazzcorner.com", verified: false, articleCount: 0 },
  { id: cid("submissions@bluesblastmagazine.com"), name: "Blues Blast Magazine Submissions", email: "submissions@bluesblastmagazine.com", outlet: "Blues Blast Magazine", type: "blog", genre: "Blues", region: "International", beat: "Music Submissions", bio: "Blues Blast Magazine — free weekly blues music publication.", website: "https://bluesblastmagazine.com", verified: false, articleCount: 0 },
  { id: cid("submissions@americanbluesscene.com"), name: "American Blues Scene Submissions", email: "submissions@americanbluesscene.com", outlet: "American Blues Scene", type: "blog", genre: "Blues", region: "International", beat: "Music Submissions", bio: "American Blues Scene — online blues music publication and community.", website: "https://americanbluesscene.com", verified: false, articleCount: 0 },
  { id: cid("submissions@bluesrockreview.com"), name: "Blues Rock Review Submissions", email: "submissions@bluesrockreview.com", outlet: "Blues Rock Review", type: "blog", genre: "Blues Rock, Blues", region: "International", beat: "Music Submissions", bio: "Blues Rock Review — blog covering blues rock music and related genres.", website: "https://bluesrockreview.com", verified: false, articleCount: 0 },
  { id: cid("editorial@livingblues.com"), name: "Living Blues Editorial", email: "editorial@livingblues.com", outlet: "Living Blues", type: "blog", genre: "Blues", region: "Mississippi", beat: "Music Submissions", bio: "Living Blues — University of Mississippi-based blues music magazine.", website: "https://livingblues.com", verified: false, articleCount: 0 },
  { id: cid("submissions@icareifyoulisten.com"), name: "I Care If You Listen Submissions", email: "submissions@icareifyoulisten.com", outlet: "I Care If You Listen", type: "blog", genre: "Contemporary Classical, New Music", region: "International", beat: "Music Submissions", bio: "I Care If You Listen — contemporary classical and new music blog.", website: "https://icareifyoulisten.com", verified: false, articleCount: 0 },
  { id: cid("submissions@newmusicbox.org"), name: "New Music Box Submissions", email: "submissions@newmusicbox.org", outlet: "New Music Box", type: "blog", genre: "Contemporary Classical, New Music", region: "New York, NY", beat: "Music Submissions", bio: "New Music Box — New Music USA's publication covering contemporary classical.", website: "https://newmusicbox.org", verified: false, articleCount: 0 },
  { id: cid("editorial@sequenza21.com"), name: "Sequenza 21 Editorial", email: "editorial@sequenza21.com", outlet: "Sequenza 21", type: "blog", genre: "Contemporary Classical", region: "International", beat: "Music Submissions", bio: "Sequenza 21 — contemporary classical music blog.", website: "https://sequenza21.com", verified: false, articleCount: 0 },
  { id: cid("editorial@thestrad.com"), name: "The Strad Editorial", email: "editorial@thestrad.com", outlet: "The Strad", type: "blog", genre: "Classical, Strings", region: "United Kingdom", beat: "Music Submissions", bio: "The Strad — leading string instrument and classical music publication.", website: "https://thestrad.com", verified: false, articleCount: 0 },
  { id: cid("editorial@gramophone.co.uk"), name: "Gramophone Editorial", email: "editorial@gramophone.co.uk", outlet: "Gramophone", type: "blog", genre: "Classical", region: "United Kingdom", beat: "Music Submissions", bio: "Gramophone — the world's leading classical music magazine since 1923.", website: "https://gramophone.co.uk", verified: false, articleCount: 0 },
  { id: cid("editorial@limelightmagazine.com.au"), name: "Limelight Magazine Editorial", email: "editorial@limelightmagazine.com.au", outlet: "Limelight Magazine", type: "blog", genre: "Classical, Opera, Jazz", region: "Australia", beat: "Music Submissions", bio: "Limelight Magazine — Australian classical music and performing arts magazine.", website: "https://limelightmagazine.com.au", verified: false, articleCount: 0 },
];

// ── World/Latin (10) ────────────────────────────────────────────────────────

const worldBlogs: SeedContact[] = [
  { id: cid("press@remezcla.com"), name: "Remezcla Blog Press", email: "press@remezcla.com", outlet: "Remezcla", type: "blog", genre: "Latin, Reggaeton, Latin Pop", region: "International", beat: "Music Submissions", bio: "Remezcla — Latin music and culture blog.", website: "https://remezcla.com", verified: false, articleCount: 0 },
  { id: cid("press@soundsandcolours.com"), name: "Sounds and Colours Press", email: "press@soundsandcolours.com", outlet: "Sounds and Colours", type: "blog", genre: "Latin America, World", region: "United Kingdom", beat: "Music Submissions", bio: "Sounds and Colours — Latin American music and culture blog.", website: "https://soundsandcolours.com", verified: false, articleCount: 0 },
  { id: cid("submissions@worldmusiccentral.org"), name: "World Music Central Submissions", email: "submissions@worldmusiccentral.org", outlet: "World Music Central", type: "blog", genre: "World Music", region: "International", beat: "Music Submissions", bio: "World Music Central — global music news and reviews blog.", website: "https://worldmusiccentral.org", verified: false, articleCount: 0 },
  { id: cid("press@afropunk.com"), name: "Afropunk Blog Press", email: "press@afropunk.com", outlet: "Afropunk", type: "blog", genre: "Afropunk, Alternative, Black Culture", region: "New York, NY", beat: "Music Submissions", bio: "Afropunk — Black alternative culture and music platform.", website: "https://afropunk.com", verified: false, articleCount: 0 },
  { id: cid("press@okayafrica.com"), name: "OkayAfrica Press", email: "press@okayafrica.com", outlet: "OkayAfrica", type: "blog", genre: "African Music, Afrobeats", region: "International", beat: "Music Submissions", bio: "OkayAfrica — African music, culture, and politics blog.", website: "https://okayafrica.com", verified: false, articleCount: 0 },
  { id: cid("submissions@reggaeville.com"), name: "Reggaeville Submissions", email: "submissions@reggaeville.com", outlet: "Reggaeville", type: "blog", genre: "Reggae, Dancehall", region: "International", beat: "Music Submissions", bio: "Reggaeville — reggae music news and reviews blog.", website: "https://reggaeville.com", verified: false, articleCount: 0 },
  { id: cid("submissions@dancehallmag.com"), name: "Dancehall Mag Submissions", email: "submissions@dancehallmag.com", outlet: "Dancehall Mag", type: "blog", genre: "Dancehall, Reggae", region: "International", beat: "Music Submissions", bio: "Dancehall Mag — dancehall music news and culture blog.", website: "https://dancehallmag.com", verified: false, articleCount: 0 },
  { id: cid("submissions@largeup.com"), name: "LargeUp Submissions", email: "submissions@largeup.com", outlet: "LargeUp", type: "blog", genre: "Caribbean, Dancehall, Soca", region: "International", beat: "Music Submissions", bio: "LargeUp — Caribbean music and culture platform.", website: "https://largeup.com", verified: false, articleCount: 0 },
  { id: cid("submissions@afrobeatsintelligence.com"), name: "Afrobeats Intelligence Submissions", email: "submissions@afrobeatsintelligence.com", outlet: "Afrobeats Intelligence", type: "blog", genre: "Afrobeats, African Music", region: "International", beat: "Music Submissions", bio: "Afrobeats Intelligence — Afrobeats music data and news blog.", website: "https://afrobeatsintelligence.com", verified: false, articleCount: 0 },
  { id: cid("submissions@globalrhythm.net"), name: "Global Rhythm Submissions", email: "submissions@globalrhythm.net", outlet: "Global Rhythm", type: "blog", genre: "World Music", region: "International", beat: "Music Submissions", bio: "Global Rhythm — world music and global beats blog.", website: "https://globalrhythm.net", verified: false, articleCount: 0 },
];

// ─── JOURNALISTS ───────────────────────────────────────────────────────────────

// ── Regional US Publications (30) ───────────────────────────────────────────

const regionalJournalists: SeedContact[] = [
  { id: cid("music@nashvillescene.com"), name: "Nashville Scene Music Desk", email: "music@nashvillescene.com", outlet: "Nashville Scene", type: "journalist", genre: "All Genres", region: "Nashville, TN", beat: "Music Journalism", bio: "Nashville Scene — alternative newsweekly covering Nashville's music scene.", website: "https://nashvillescene.com", verified: false, articleCount: 0 },
  { id: cid("music@portlandmercury.com"), name: "Portland Mercury Music Desk", email: "music@portlandmercury.com", outlet: "Portland Mercury", type: "journalist", genre: "All Genres", region: "Portland, OR", beat: "Music Journalism", bio: "Portland Mercury — alt-weekly covering Portland's music and arts.", website: "https://portlandmercury.com", verified: false, articleCount: 0 },
  { id: cid("music@thestranger.com"), name: "The Stranger Music Desk", email: "music@thestranger.com", outlet: "The Stranger", type: "journalist", genre: "All Genres", region: "Seattle, WA", beat: "Music Journalism", bio: "The Stranger — Seattle alt-weekly with strong music coverage.", website: "https://thestranger.com", verified: false, articleCount: 0 },
  { id: cid("music@sfweekly.com"), name: "SF Weekly Music Desk", email: "music@sfweekly.com", outlet: "SF Weekly", type: "journalist", genre: "All Genres", region: "San Francisco, CA", beat: "Music Journalism", bio: "SF Weekly — San Francisco alternative newsweekly.", website: "https://sfweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@laweekly.com"), name: "LA Weekly Music Desk", email: "music@laweekly.com", outlet: "LA Weekly", type: "journalist", genre: "All Genres", region: "Los Angeles, CA", beat: "Music Journalism", bio: "LA Weekly — Los Angeles alternative newsweekly with extensive music coverage.", website: "https://laweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@chicagoreader.com"), name: "Chicago Reader Music Desk", email: "music@chicagoreader.com", outlet: "Chicago Reader", type: "journalist", genre: "All Genres", region: "Chicago, IL", beat: "Music Journalism", bio: "Chicago Reader — Chicago's alternative newsweekly.", website: "https://chicagoreader.com", verified: false, articleCount: 0 },
  { id: cid("music@dallasobserver.com"), name: "Dallas Observer Music Desk", email: "music@dallasobserver.com", outlet: "Dallas Observer", type: "journalist", genre: "All Genres", region: "Dallas, TX", beat: "Music Journalism", bio: "Dallas Observer — Dallas-Fort Worth alternative newsweekly.", website: "https://dallasobserver.com", verified: false, articleCount: 0 },
  { id: cid("music@phoenixnewtimes.com"), name: "Phoenix New Times Music Desk", email: "music@phoenixnewtimes.com", outlet: "Phoenix New Times", type: "journalist", genre: "All Genres", region: "Phoenix, AZ", beat: "Music Journalism", bio: "Phoenix New Times — Phoenix alternative newsweekly.", website: "https://phoenixnewtimes.com", verified: false, articleCount: 0 },
  { id: cid("music@westword.com"), name: "Westword Music Desk", email: "music@westword.com", outlet: "Westword", type: "journalist", genre: "All Genres", region: "Denver, CO", beat: "Music Journalism", bio: "Westword — Denver's alternative newsweekly.", website: "https://westword.com", verified: false, articleCount: 0 },
  { id: cid("music@miaminewtimes.com"), name: "Miami New Times Music Desk", email: "music@miaminewtimes.com", outlet: "Miami New Times", type: "journalist", genre: "All Genres", region: "Miami, FL", beat: "Music Journalism", bio: "Miami New Times — Miami alternative newsweekly.", website: "https://miaminewtimes.com", verified: false, articleCount: 0 },
  { id: cid("music@clevescene.com"), name: "Cleveland Scene Music Desk", email: "music@clevescene.com", outlet: "Cleveland Scene", type: "journalist", genre: "All Genres", region: "Cleveland, OH", beat: "Music Journalism", bio: "Cleveland Scene — Cleveland alternative newsweekly.", website: "https://clevescene.com", verified: false, articleCount: 0 },
  { id: cid("music@riverfronttimes.com"), name: "Riverfront Times Music Desk", email: "music@riverfronttimes.com", outlet: "Riverfront Times", type: "journalist", genre: "All Genres", region: "St. Louis, MO", beat: "Music Journalism", bio: "Riverfront Times — St. Louis alternative newsweekly.", website: "https://riverfronttimes.com", verified: false, articleCount: 0 },
  { id: cid("music@creativeloafing.com"), name: "Creative Loafing Atlanta Music", email: "music@creativeloafing.com", outlet: "Creative Loafing (Atlanta)", type: "journalist", genre: "All Genres", region: "Atlanta, GA", beat: "Music Journalism", bio: "Creative Loafing — Atlanta alternative newsweekly.", website: "https://creativeloafing.com", verified: false, articleCount: 0 },
  { id: cid("music@cltampa.com"), name: "Creative Loafing Tampa Music", email: "music@cltampa.com", outlet: "Creative Loafing (Tampa)", type: "journalist", genre: "All Genres", region: "Tampa, FL", beat: "Music Journalism", bio: "Creative Loafing Tampa — Tampa Bay alternative newsweekly.", website: "https://cltampa.com", verified: false, articleCount: 0 },
  { id: cid("music@orlandoweekly.com"), name: "Orlando Weekly Music Desk", email: "music@orlandoweekly.com", outlet: "Orlando Weekly", type: "journalist", genre: "All Genres", region: "Orlando, FL", beat: "Music Journalism", bio: "Orlando Weekly — Central Florida alternative newsweekly.", website: "https://orlandoweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@eugeneweekly.com"), name: "Eugene Weekly Music Desk", email: "music@eugeneweekly.com", outlet: "Eugene Weekly", type: "journalist", genre: "All Genres", region: "Eugene, OR", beat: "Music Journalism", bio: "Eugene Weekly — Eugene, Oregon alternative newsweekly.", website: "https://eugeneweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@wweek.com"), name: "Willamette Week Music Desk", email: "music@wweek.com", outlet: "Willamette Week", type: "journalist", genre: "All Genres", region: "Portland, OR", beat: "Music Journalism", bio: "Willamette Week — Portland alternative newsweekly.", website: "https://wweek.com", verified: false, articleCount: 0 },
  { id: cid("music@citypages.com"), name: "City Pages Music Desk", email: "music@citypages.com", outlet: "City Pages", type: "journalist", genre: "All Genres", region: "Minneapolis, MN", beat: "Music Journalism", bio: "City Pages — Minneapolis-St. Paul alternative newsweekly.", website: "https://citypages.com", verified: false, articleCount: 0 },
  { id: cid("music@metrotimes.com"), name: "Metro Times Music Desk", email: "music@metrotimes.com", outlet: "Metro Times", type: "journalist", genre: "All Genres", region: "Detroit, MI", beat: "Music Journalism", bio: "Metro Times — Detroit alternative newsweekly.", website: "https://metrotimes.com", verified: false, articleCount: 0 },
  { id: cid("music@pghcitypaper.com"), name: "Pittsburgh City Paper Music", email: "music@pghcitypaper.com", outlet: "Pittsburgh City Paper", type: "journalist", genre: "All Genres", region: "Pittsburgh, PA", beat: "Music Journalism", bio: "Pittsburgh City Paper — Pittsburgh alternative newsweekly.", website: "https://pghcitypaper.com", verified: false, articleCount: 0 },
  { id: cid("music@sacurrent.com"), name: "San Antonio Current Music", email: "music@sacurrent.com", outlet: "San Antonio Current", type: "journalist", genre: "All Genres", region: "San Antonio, TX", beat: "Music Journalism", bio: "San Antonio Current — San Antonio alternative newsweekly.", website: "https://sacurrent.com", verified: false, articleCount: 0 },
  { id: cid("music@newsreview.com"), name: "Sacramento News & Review Music", email: "music@newsreview.com", outlet: "Sacramento News & Review", type: "journalist", genre: "All Genres", region: "Sacramento, CA", beat: "Music Journalism", bio: "Sacramento News & Review — Sacramento alternative newsweekly.", website: "https://newsreview.com", verified: false, articleCount: 0 },
  { id: cid("music@ocweekly.com"), name: "OC Weekly Music Desk", email: "music@ocweekly.com", outlet: "OC Weekly", type: "journalist", genre: "All Genres", region: "Orange County, CA", beat: "Music Journalism", bio: "OC Weekly — Orange County alternative newsweekly.", website: "https://ocweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@honoluluweekly.com"), name: "Honolulu Weekly Music Desk", email: "music@honoluluweekly.com", outlet: "Honolulu Weekly", type: "journalist", genre: "All Genres", region: "Honolulu, HI", beat: "Music Journalism", bio: "Honolulu Weekly — Honolulu alternative newsweekly.", website: "https://honoluluweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@cityweekly.net"), name: "Salt Lake City Weekly Music", email: "music@cityweekly.net", outlet: "Salt Lake City Weekly", type: "journalist", genre: "All Genres", region: "Salt Lake City, UT", beat: "Music Journalism", bio: "Salt Lake City Weekly — SLC alternative newsweekly.", website: "https://cityweekly.net", verified: false, articleCount: 0 },
  { id: cid("music@boiseweekly.com"), name: "Boise Weekly Music Desk", email: "music@boiseweekly.com", outlet: "Boise Weekly", type: "journalist", genre: "All Genres", region: "Boise, ID", beat: "Music Journalism", bio: "Boise Weekly — Boise alternative newsweekly.", website: "https://boiseweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@tucsonweekly.com"), name: "Tucson Weekly Music Desk", email: "music@tucsonweekly.com", outlet: "Tucson Weekly", type: "journalist", genre: "All Genres", region: "Tucson, AZ", beat: "Music Journalism", bio: "Tucson Weekly — Tucson alternative newsweekly.", website: "https://tucsonweekly.com", verified: false, articleCount: 0 },
  { id: cid("music@detroitmetrotimes.com"), name: "Detroit Metro Times Music", email: "music@detroitmetrotimes.com", outlet: "Detroit Metro Times", type: "journalist", genre: "All Genres", region: "Detroit, MI", beat: "Music Journalism", bio: "Detroit Metro Times — Detroit's alternative weekly newspaper.", website: "https://metrotimes.com", verified: false, articleCount: 0 },
  { id: cid("music@memphisflyer.com"), name: "Memphis Flyer Music Desk", email: "music@memphisflyer.com", outlet: "Memphis Flyer", type: "journalist", genre: "All Genres", region: "Memphis, TN", beat: "Music Journalism", bio: "Memphis Flyer — Memphis alternative newsweekly.", website: "https://memphisflyer.com", verified: false, articleCount: 0 },
  { id: cid("music@charlestoncitypaper.com"), name: "Charleston City Paper Music", email: "music@charlestoncitypaper.com", outlet: "Charleston City Paper", type: "journalist", genre: "All Genres", region: "Charleston, SC", beat: "Music Journalism", bio: "Charleston City Paper — Charleston alternative newsweekly.", website: "https://charlestoncitypaper.com", verified: false, articleCount: 0 },
];

// ── Trade/Industry (15) ─────────────────────────────────────────────────────

const tradeJournalists: SeedContact[] = [
  { id: cid("news@hitsdailydouble.com"), name: "Hits Daily Double News", email: "news@hitsdailydouble.com", outlet: "Hits Daily Double", type: "journalist", genre: "Industry", region: "Los Angeles, CA", beat: "Music Journalism", bio: "Hits Daily Double — music industry trade publication.", website: "https://hitsdailydouble.com", verified: false, articleCount: 0 },
  { id: cid("editorial@pollstar.com"), name: "Pollstar Editorial", email: "editorial@pollstar.com", outlet: "Pollstar", type: "journalist", genre: "Industry, Touring", region: "International", beat: "Music Journalism", bio: "Pollstar — the concert industry's leading trade publication.", website: "https://pollstar.com", verified: false, articleCount: 0 },
  { id: cid("editorial@celebrityaccess.com"), name: "CelebrityAccess Editorial", email: "editorial@celebrityaccess.com", outlet: "CelebrityAccess", type: "journalist", genre: "Industry", region: "International", beat: "Music Journalism", bio: "CelebrityAccess — entertainment industry trade publication.", website: "https://celebrityaccess.com", verified: false, articleCount: 0 },
  { id: cid("editorial@musicweek.com"), name: "Music Week Editorial", email: "editorial@musicweek.com", outlet: "Music Week", type: "journalist", genre: "Industry", region: "United Kingdom", beat: "Music Journalism", bio: "Music Week — UK music industry trade magazine.", website: "https://musicweek.com", verified: false, articleCount: 0 },
  { id: cid("editorial@themusicnetwork.com"), name: "The Music Network Editorial", email: "editorial@themusicnetwork.com", outlet: "The Music Network", type: "journalist", genre: "Industry", region: "Australia", beat: "Music Journalism", bio: "The Music Network — Australian music industry trade publication.", website: "https://themusicnetwork.com", verified: false, articleCount: 0 },
  { id: cid("editorial@musically.com"), name: "Music Ally Editorial", email: "editorial@musically.com", outlet: "Music Ally", type: "journalist", genre: "Industry, Digital", region: "United Kingdom", beat: "Music Journalism", bio: "Music Ally — music business and digital media publication.", website: "https://musically.com", verified: false, articleCount: 0 },
  { id: cid("editorial@recordoftheday.com"), name: "Record of the Day Editorial", email: "editorial@recordoftheday.com", outlet: "Record of the Day", type: "journalist", genre: "Industry", region: "United Kingdom", beat: "Music Journalism", bio: "Record of the Day — UK music industry newsletter.", website: "https://recordoftheday.com", verified: false, articleCount: 0 },
  { id: cid("editorial@musicbusinessfacts.com"), name: "Music Business Facts Editorial", email: "editorial@musicbusinessfacts.com", outlet: "Music Business Facts", type: "journalist", genre: "Industry", region: "International", beat: "Music Journalism", bio: "Music Business Facts — music industry data and analysis.", website: "https://musicbusinessfacts.com", verified: false, articleCount: 0 },
  { id: cid("editorial@completemusicupdate.com"), name: "Complete Music Update Editorial", email: "editorial@completemusicupdate.com", outlet: "Complete Music Update", type: "journalist", genre: "Industry", region: "United Kingdom", beat: "Music Journalism", bio: "Complete Music Update (CMU) — UK music industry news service.", website: "https://completemusicupdate.com", verified: false, articleCount: 0 },
  { id: cid("editorial@hypebot.com"), name: "Hypebot Blog Editorial", email: "editorial@hypebot.com", outlet: "Hypebot", type: "journalist", genre: "Industry, Digital", region: "International", beat: "Music Journalism", bio: "Hypebot — music business and marketing blog.", website: "https://hypebot.com", verified: false, articleCount: 0 },
  { id: cid("editorial@digitalmusicnews.com"), name: "Digital Music News Editorial", email: "editorial@digitalmusicnews.com", outlet: "Digital Music News", type: "journalist", genre: "Industry, Digital", region: "International", beat: "Music Journalism", bio: "Digital Music News — digital music industry news publication.", website: "https://digitalmusicnews.com", verified: false, articleCount: 0 },
  { id: cid("editorial@waterandmusic.com"), name: "Water & Music Editorial", email: "editorial@waterandmusic.com", outlet: "Water & Music", type: "journalist", genre: "Industry, Innovation", region: "International", beat: "Music Journalism", bio: "Water & Music — music industry innovation and research publication.", website: "https://waterandmusic.com", verified: false, articleCount: 0 },
  { id: cid("editorial@midiaresearch.com"), name: "MIDiA Research Editorial", email: "editorial@midiaresearch.com", outlet: "MIDiA Research", type: "journalist", genre: "Industry, Data", region: "United Kingdom", beat: "Music Journalism", bio: "MIDiA Research — music and media industry research and analysis.", website: "https://midiaresearch.com", verified: false, articleCount: 0 },
  { id: cid("press@chartmetric.com"), name: "Chartmetric Blog Press", email: "press@chartmetric.com", outlet: "Chartmetric", type: "journalist", genre: "Industry, Data", region: "International", beat: "Music Journalism", bio: "Chartmetric — music analytics platform and industry blog.", website: "https://chartmetric.com", verified: false, articleCount: 0 },
  { id: cid("press@soundcharts.com"), name: "Soundcharts Blog Press", email: "press@soundcharts.com", outlet: "Soundcharts", type: "journalist", genre: "Industry, Data", region: "International", beat: "Music Journalism", bio: "Soundcharts — music data analytics platform and blog.", website: "https://soundcharts.com", verified: false, articleCount: 0 },
];

// ── International (25) ──────────────────────────────────────────────────────

const internationalJournalists: SeedContact[] = [
  { id: cid("press@drownedinsound.com"), name: "Drowned in Sound Press", email: "press@drownedinsound.com", outlet: "Drowned in Sound", type: "journalist", genre: "Indie, Rock, Alternative", region: "United Kingdom", beat: "Music Journalism", bio: "Drowned in Sound — UK indie music publication.", website: "https://drownedinsound.com", verified: false, articleCount: 0 },
  { id: cid("music@theskinny.co.uk"), name: "The Skinny Music Desk", email: "music@theskinny.co.uk", outlet: "The Skinny", type: "journalist", genre: "All Genres", region: "Scotland, UK", beat: "Music Journalism", bio: "The Skinny — Scottish arts and culture magazine.", website: "https://theskinny.co.uk", verified: false, articleCount: 0 },
  { id: cid("editorial@hotpress.com"), name: "Hot Press Editorial", email: "editorial@hotpress.com", outlet: "Hot Press", type: "journalist", genre: "Rock, Pop, Indie", region: "Ireland", beat: "Music Journalism", bio: "Hot Press — Ireland's leading music and culture magazine.", website: "https://hotpress.com", verified: false, articleCount: 0 },
  { id: cid("editorial@ripitup.com.au"), name: "Rip It Up Editorial", email: "editorial@ripitup.com.au", outlet: "Rip It Up", type: "journalist", genre: "All Genres", region: "Australia", beat: "Music Journalism", bio: "Rip It Up — Australian music publication.", website: "https://ripitup.com.au", verified: false, articleCount: 0 },
  { id: cid("editorial@tonedeaf.thebrag.com"), name: "Tone Deaf Editorial", email: "editorial@tonedeaf.thebrag.com", outlet: "Tone Deaf", type: "journalist", genre: "All Genres", region: "Australia", beat: "Music Journalism", bio: "Tone Deaf — Australian music news and entertainment site.", website: "https://tonedeaf.thebrag.com", verified: false, articleCount: 0 },
  { id: cid("editorial@themusic.com.au"), name: "The Music AU Editorial", email: "editorial@themusic.com.au", outlet: "The Music AU", type: "journalist", genre: "All Genres", region: "Australia", beat: "Music Journalism", bio: "The Music — Australian music publication covering local and international acts.", website: "https://themusic.com.au", verified: false, articleCount: 0 },
  { id: cid("editorial@musicfeeds.com.au"), name: "Music Feeds Editorial", email: "editorial@musicfeeds.com.au", outlet: "Music Feeds", type: "journalist", genre: "All Genres", region: "Australia", beat: "Music Journalism", bio: "Music Feeds — Australian music news and reviews publication.", website: "https://musicfeeds.com.au", verified: false, articleCount: 0 },
  { id: cid("editorial@hhvmag.de"), name: "hhv.de Magazine Editorial", email: "editorial@hhvmag.de", outlet: "hhv.de Magazine", type: "journalist", genre: "Hip Hop, Electronic, Vinyl", region: "Germany", beat: "Music Journalism", bio: "hhv.de Magazine — German music and vinyl culture magazine.", website: "https://hhv.de/mag", verified: false, articleCount: 0 },
  { id: cid("editorial@bytefm.de"), name: "ByteFM Magazine Editorial", email: "editorial@bytefm.de", outlet: "ByteFM Magazine", type: "journalist", genre: "All Genres", region: "Germany", beat: "Music Journalism", bio: "ByteFM — German internet radio station and music magazine.", website: "https://byte.fm", verified: false, articleCount: 0 },
  { id: cid("editorial@musikexpress.de"), name: "Musikexpress Editorial", email: "editorial@musikexpress.de", outlet: "Musikexpress", type: "journalist", genre: "Rock, Pop, Indie", region: "Germany", beat: "Music Journalism", bio: "Musikexpress — major German music magazine.", website: "https://musikexpress.de", verified: false, articleCount: 0 },
  { id: cid("editorial@intromagazine.de"), name: "Intro Magazine Editorial", email: "editorial@intromagazine.de", outlet: "Intro Magazine", type: "journalist", genre: "Indie, Alternative, Electronic", region: "Germany", beat: "Music Journalism", bio: "Intro Magazine — German indie and alternative music magazine.", website: "https://intro.de", verified: false, articleCount: 0 },
  { id: cid("editorial@spex.de"), name: "Spex Editorial", email: "editorial@spex.de", outlet: "Spex", type: "journalist", genre: "Pop Culture, Music", region: "Germany", beat: "Music Journalism", bio: "Spex — German pop culture and music magazine.", website: "https://spex.de", verified: false, articleCount: 0 },
  { id: cid("editorial@lesinrocks.com"), name: "Les Inrockuptibles Editorial", email: "editorial@lesinrocks.com", outlet: "Les Inrockuptibles", type: "journalist", genre: "Indie, Rock, Pop", region: "France", beat: "Music Journalism", bio: "Les Inrockuptibles — French culture and music magazine.", website: "https://lesinrocks.com", verified: false, articleCount: 0 },
  { id: cid("editorial@tsugi.fr"), name: "Tsugi Editorial", email: "editorial@tsugi.fr", outlet: "Tsugi", type: "journalist", genre: "Electronic, Dance, Hip Hop", region: "France", beat: "Music Journalism", bio: "Tsugi — French electronic and urban music magazine.", website: "https://tsugi.fr", verified: false, articleCount: 0 },
  { id: cid("press@soyoungmagazine.com"), name: "So Young Magazine Press", email: "press@soyoungmagazine.com", outlet: "So Young Magazine", type: "journalist", genre: "Indie, DIY, Post-Punk", region: "United Kingdom", beat: "Music Journalism", bio: "So Young Magazine — UK indie and DIY music print and online magazine.", website: "https://soyoungmagazine.com", verified: false, articleCount: 0 },
  { id: cid("press@loudandquiet.com"), name: "Loud & Quiet Press", email: "press@loudandquiet.com", outlet: "Loud & Quiet", type: "journalist", genre: "Indie, Alternative", region: "United Kingdom", beat: "Music Journalism", bio: "Loud & Quiet — UK independent music magazine.", website: "https://loudandquiet.com", verified: false, articleCount: 0 },
  { id: cid("press@crackmagazine.net"), name: "Crack Magazine Blog Press", email: "press@crackmagazine.net", outlet: "Crack Magazine", type: "journalist", genre: "Electronic, Club, Experimental", region: "United Kingdom", beat: "Music Journalism", bio: "Crack Magazine — UK music and culture publication.", website: "https://crackmagazine.net", verified: false, articleCount: 0 },
  { id: cid("press@thevinylfactory.com"), name: "The Vinyl Factory Press", email: "press@thevinylfactory.com", outlet: "The Vinyl Factory", type: "journalist", genre: "All Genres, Vinyl", region: "United Kingdom", beat: "Music Journalism", bio: "The Vinyl Factory — UK vinyl culture, music, and art publication.", website: "https://thevinylfactory.com", verified: false, articleCount: 0 },
  { id: cid("press@thequietus.com"), name: "The Quietus Blog Press", email: "press@thequietus.com", outlet: "The Quietus", type: "journalist", genre: "Indie, Experimental, Alternative", region: "United Kingdom", beat: "Music Journalism", bio: "The Quietus — UK independent music and pop culture site.", website: "https://thequietus.com", verified: false, articleCount: 0 },
  { id: cid("press@dummymag.com"), name: "Dummy Magazine Press", email: "press@dummymag.com", outlet: "Dummy Magazine", type: "journalist", genre: "Electronic, Indie, Club", region: "United Kingdom", beat: "Music Journalism", bio: "Dummy Magazine — UK electronic and club music publication.", website: "https://dummymag.com", verified: false, articleCount: 0 },
  { id: cid("music@dazeddigital.com"), name: "Dazed Music Desk", email: "music@dazeddigital.com", outlet: "Dazed Music", type: "journalist", genre: "All Genres, Culture", region: "United Kingdom", beat: "Music Journalism", bio: "Dazed Digital — UK fashion, music, and culture publication.", website: "https://dazeddigital.com", verified: false, articleCount: 0 },
  { id: cid("music@i-d.co"), name: "i-D Music Desk", email: "music@i-d.co", outlet: "i-D Music", type: "journalist", genre: "All Genres, Culture", region: "United Kingdom", beat: "Music Journalism", bio: "i-D — fashion and culture magazine with music coverage.", website: "https://i-d.co", verified: false, articleCount: 0 },
  { id: cid("press@factmag.com"), name: "Fact Magazine Press", email: "press@factmag.com", outlet: "Fact Magazine", type: "journalist", genre: "Electronic, Experimental, Club", region: "United Kingdom", beat: "Music Journalism", bio: "Fact Magazine — UK electronic and experimental music publication.", website: "https://factmag.com", verified: false, articleCount: 0 },
  { id: cid("press@boilerroom.tv"), name: "Boiler Room Magazine Press", email: "press@boilerroom.tv", outlet: "Boiler Room", type: "journalist", genre: "Electronic, Club, DJ", region: "United Kingdom", beat: "Music Journalism", bio: "Boiler Room — global music broadcasting platform and editorial.", website: "https://boilerroom.tv", verified: false, articleCount: 0 },
  { id: cid("editorial@stampthewax.com"), name: "Stamp the Wax Editorial", email: "editorial@stampthewax.com", outlet: "Stamp the Wax", type: "journalist", genre: "Jazz, Soul, Electronic, World", region: "United Kingdom", beat: "Music Journalism", bio: "Stamp the Wax — UK music blog covering jazz, soul, and global sounds.", website: "https://stampthewax.com", verified: false, articleCount: 0 },
];

// ── Genre-Specific Journalists (30) ─────────────────────────────────────────

const genreJournalists: SeedContact[] = [
  { id: cid("editorial@altpress.com"), name: "Alt Press Editorial", email: "editorial@altpress.com", outlet: "Alt Press", type: "journalist", genre: "Alternative, Punk, Rock", region: "Cleveland, OH", beat: "Music Journalism", bio: "Alternative Press — leading alternative rock and punk music magazine.", website: "https://altpress.com", verified: false, articleCount: 0 },
  { id: cid("editorial@kerrang.com"), name: "Kerrang Blog Editorial", email: "editorial@kerrang.com", outlet: "Kerrang!", type: "journalist", genre: "Rock, Metal, Punk", region: "United Kingdom", beat: "Music Journalism", bio: "Kerrang! — iconic British rock and metal music magazine.", website: "https://kerrang.com", verified: false, articleCount: 0 },
  { id: cid("editorial@rocksound.tv"), name: "Rock Sound Blog Editorial", email: "editorial@rocksound.tv", outlet: "Rock Sound", type: "journalist", genre: "Rock, Pop Punk, Metal", region: "United Kingdom", beat: "Music Journalism", bio: "Rock Sound — UK rock music magazine.", website: "https://rocksound.tv", verified: false, articleCount: 0 },
  { id: cid("editorial@metalhammer.com"), name: "Metal Hammer Blog Editorial", email: "editorial@metalhammer.com", outlet: "Metal Hammer", type: "journalist", genre: "Metal, Rock, Heavy", region: "United Kingdom", beat: "Music Journalism", bio: "Metal Hammer — major metal and rock music magazine.", website: "https://metalhammer.com", verified: false, articleCount: 0 },
  { id: cid("press@progmagazine.com"), name: "Prog Blog Press", email: "press@progmagazine.com", outlet: "Prog Magazine", type: "journalist", genre: "Progressive Rock, Prog Metal", region: "United Kingdom", beat: "Music Journalism", bio: "Prog Magazine — UK progressive rock and metal publication.", website: "https://progmagazine.com", verified: false, articleCount: 0 },
  { id: cid("editorial@revolvermag.com"), name: "Revolver Blog Editorial", email: "editorial@revolvermag.com", outlet: "Revolver", type: "journalist", genre: "Metal, Hard Rock", region: "International", beat: "Music Journalism", bio: "Revolver — hard rock and heavy metal music magazine.", website: "https://revolvermag.com", verified: false, articleCount: 0 },
  { id: cid("editorial@decibelmagazine.com"), name: "Decibel Blog Editorial", email: "editorial@decibelmagazine.com", outlet: "Decibel Magazine", type: "journalist", genre: "Extreme Metal, Heavy", region: "Philadelphia, PA", beat: "Music Journalism", bio: "Decibel Magazine — extreme music magazine.", website: "https://decibelmagazine.com", verified: false, articleCount: 0 },
  { id: cid("editorial@guitarworld.com"), name: "Guitar World Editorial", email: "editorial@guitarworld.com", outlet: "Guitar World", type: "journalist", genre: "Rock, Guitar, Blues", region: "International", beat: "Music Journalism", bio: "Guitar World — guitar-focused music magazine.", website: "https://guitarworld.com", verified: false, articleCount: 0 },
  { id: cid("editorial@bassplayer.com"), name: "Bass Player Editorial", email: "editorial@bassplayer.com", outlet: "Bass Player", type: "journalist", genre: "Bass, Rock, Jazz, Funk", region: "International", beat: "Music Journalism", bio: "Bass Player — magazine for bass guitar players.", website: "https://bassplayer.com", verified: false, articleCount: 0 },
  { id: cid("editorial@drummagazine.com"), name: "Drum Magazine Editorial", email: "editorial@drummagazine.com", outlet: "Drum Magazine", type: "journalist", genre: "Drums, Percussion, All Genres", region: "International", beat: "Music Journalism", bio: "Drum Magazine — publication for drummers and percussionists.", website: "https://drummagazine.com", verified: false, articleCount: 0 },
  { id: cid("editorial@electronicsound.co.uk"), name: "Electronic Sound Editorial", email: "editorial@electronicsound.co.uk", outlet: "Electronic Sound", type: "journalist", genre: "Electronic, Synth", region: "United Kingdom", beat: "Music Journalism", bio: "Electronic Sound — UK electronic music magazine.", website: "https://electronicsound.co.uk", verified: false, articleCount: 0 },
  { id: cid("editorial@djmag.com"), name: "DJ Mag Blog Editorial", email: "editorial@djmag.com", outlet: "DJ Mag", type: "journalist", genre: "Electronic, DJ, Dance", region: "United Kingdom", beat: "Music Journalism", bio: "DJ Mag — global electronic music and DJ culture magazine.", website: "https://djmag.com", verified: false, articleCount: 0 },
  { id: cid("editorial@mixmag.net"), name: "Mixmag Blog Editorial", email: "editorial@mixmag.net", outlet: "Mixmag", type: "journalist", genre: "Electronic, Dance, Club", region: "United Kingdom", beat: "Music Journalism", bio: "Mixmag — global dance music and club culture magazine.", website: "https://mixmag.net", verified: false, articleCount: 0 },
  { id: cid("press@residentadvisor.net"), name: "Resident Advisor Blog Press", email: "press@residentadvisor.net", outlet: "Resident Advisor", type: "journalist", genre: "Electronic, Techno, House", region: "International", beat: "Music Journalism", bio: "Resident Advisor — electronic music platform with editorial content.", website: "https://ra.co", verified: false, articleCount: 0 },
  { id: cid("editorial@groove.de"), name: "Groove Magazine Editorial", email: "editorial@groove.de", outlet: "Groove Magazine", type: "journalist", genre: "Electronic, Techno, House", region: "Germany", beat: "Music Journalism", bio: "Groove Magazine — German electronic music magazine.", website: "https://groove.de", verified: false, articleCount: 0 },
  { id: cid("editorial@debug.de"), name: "De:Bug Editorial", email: "editorial@debug.de", outlet: "De:Bug", type: "journalist", genre: "Electronic, Digital Culture", region: "Germany", beat: "Music Journalism", bio: "De:Bug — German electronic music and digital culture publication.", website: "https://debug.de", verified: false, articleCount: 0 },
  { id: cid("editorial@traxmag.com"), name: "Trax Magazine Editorial", email: "editorial@traxmag.com", outlet: "Trax Magazine", type: "journalist", genre: "Electronic, House, Techno", region: "France", beat: "Music Journalism", bio: "Trax Magazine — French electronic music magazine.", website: "https://traxmag.com", verified: false, articleCount: 0 },
  { id: cid("editorial@redbullmusicacademy.com"), name: "RBMA Blog Editorial", email: "editorial@redbullmusicacademy.com", outlet: "RBMA", type: "journalist", genre: "All Genres, Electronic", region: "International", beat: "Music Journalism", bio: "Red Bull Music Academy — music education platform and editorial.", website: "https://redbullmusicacademy.com", verified: false, articleCount: 0 },
  { id: cid("editorial@vinylmeplease.com"), name: "Vinyl Me Please Editorial", email: "editorial@vinylmeplease.com", outlet: "Vinyl Me Please", type: "journalist", genre: "All Genres, Vinyl", region: "Denver, CO", beat: "Music Journalism", bio: "Vinyl Me Please — vinyl subscription service and music editorial.", website: "https://vinylmeplease.com", verified: false, articleCount: 0 },
  { id: cid("editorial@turntablelab.com"), name: "Turntable Lab Editorial", email: "editorial@turntablelab.com", outlet: "Turntable Lab", type: "journalist", genre: "All Genres, Vinyl, DJ", region: "New York, NY", beat: "Music Journalism", bio: "Turntable Lab — vinyl and DJ equipment retailer with editorial.", website: "https://turntablelab.com", verified: false, articleCount: 0 },
  { id: cid("editorial@daily.bandcamp.com"), name: "Bandcamp Daily Editorial", email: "editorial@daily.bandcamp.com", outlet: "Bandcamp Daily", type: "journalist", genre: "All Genres, Independent", region: "Oakland, CA", beat: "Music Journalism", bio: "Bandcamp Daily — editorial arm of the independent music platform.", website: "https://daily.bandcamp.com", verified: false, articleCount: 0 },
  { id: cid("editorial@tidalmagazine.com"), name: "Tidal Magazine Editorial", email: "editorial@tidalmagazine.com", outlet: "Tidal Magazine", type: "journalist", genre: "All Genres", region: "International", beat: "Music Journalism", bio: "Tidal Magazine — music streaming platform's editorial publication.", website: "https://tidal.com/magazine", verified: false, articleCount: 0 },
  { id: cid("editorial@applemusic.com"), name: "Apple Music Blog Editorial", email: "editorial@applemusic.com", outlet: "Apple Music Editorial", type: "journalist", genre: "All Genres", region: "Cupertino, CA", beat: "Music Journalism", bio: "Apple Music Editorial — Apple's music streaming editorial team.", website: "https://music.apple.com", verified: false, articleCount: 0 },
  { id: cid("editorial@amazonmusic.com"), name: "Amazon Music Blog Editorial", email: "editorial@amazonmusic.com", outlet: "Amazon Music Editorial", type: "journalist", genre: "All Genres", region: "Seattle, WA", beat: "Music Journalism", bio: "Amazon Music Editorial — Amazon's music streaming editorial team.", website: "https://music.amazon.com", verified: false, articleCount: 0 },
  { id: cid("editorial@audiomack.com"), name: "Audiomack Blog Editorial", email: "editorial@audiomack.com", outlet: "Audiomack", type: "journalist", genre: "Hip Hop, Afrobeats, R&B", region: "New York, NY", beat: "Music Journalism", bio: "Audiomack — music streaming platform with editorial blog.", website: "https://audiomack.com", verified: false, articleCount: 0 },
  { id: cid("editorial@clashmusic.com"), name: "Clash Music Editorial", email: "editorial@clashmusic.com", outlet: "Clash Magazine", type: "journalist", genre: "All Genres", region: "United Kingdom", beat: "Music Journalism", bio: "Clash Magazine — UK music and culture publication.", website: "https://clashmusic.com", verified: false, articleCount: 0 },
  { id: cid("editorial@diymagazine.com"), name: "DIY Magazine Editorial", email: "editorial@diymagazine.com", outlet: "DIY Magazine", type: "journalist", genre: "Indie, Rock, Alternative", region: "United Kingdom", beat: "Music Journalism", bio: "DIY Magazine — UK indie and alternative music publication.", website: "https://diymag.com", verified: false, articleCount: 0 },
  { id: cid("editorial@lineofbestfit.com"), name: "The Line of Best Fit Editorial", email: "editorial@lineofbestfit.com", outlet: "The Line of Best Fit", type: "journalist", genre: "Indie, Pop, Alternative", region: "United Kingdom", beat: "Music Journalism", bio: "The Line of Best Fit — UK indie and pop music online magazine.", website: "https://thelineofbestfit.com", verified: false, articleCount: 0 },
  { id: cid("editorial@undertheradarmag.com"), name: "Under the Radar Editorial", email: "editorial@undertheradarmag.com", outlet: "Under the Radar", type: "journalist", genre: "Indie, Alternative", region: "International", beat: "Music Journalism", bio: "Under the Radar — indie and alternative music magazine.", website: "https://undertheradarmag.com", verified: false, articleCount: 0 },
  { id: cid("editorial@exclaim.ca"), name: "Exclaim! Editorial", email: "editorial@exclaim.ca", outlet: "Exclaim!", type: "journalist", genre: "All Genres", region: "Canada", beat: "Music Journalism", bio: "Exclaim! — Canadian music publication covering all genres.", website: "https://exclaim.ca", verified: false, articleCount: 0 },
  { id: cid("editorial@treblezine.com"), name: "Treble Zine Editorial", email: "editorial@treblezine.com", outlet: "Treble", type: "journalist", genre: "Indie, Rock, Electronic", region: "International", beat: "Music Journalism", bio: "Treble — independent music publication with reviews and features.", website: "https://treblezine.com", verified: false, articleCount: 0 },
];

// ─── COMBINED EXPORT ───────────────────────────────────────────────────────────

export const blogJournalistSeedContacts: SeedContact[] = [
  ...indieBlogs,
  ...electronicBlogs,
  ...hiphopBlogs,
  ...rockBlogs,
  ...popBlogs,
  ...countryBlogs,
  ...jazzBlogs,
  ...worldBlogs,
  ...regionalJournalists,
  ...tradeJournalists,
  ...internationalJournalists,
  ...genreJournalists,
];
