// ══════════════════════════════════════════════════════════════════════════════
// Radio Station Seed Contacts — 120+ college, community, and online stations
// All emails use organizational/role-based patterns (submissions@, music@, etc.)
// sourced from publicly listed contact pages.
// ══════════════════════════════════════════════════════════════════════════════

export interface SeedContact {
  id: string;
  name: string;
  email: string;
  outlet: string;
  type: string;
  genre: string;
  region: string;
  beat: string;
  bio: string;
  website: string;
  verified: boolean;
  articleCount: number;
}

const cid = (e: string) => "seed-r-" + e.replace(/[@.]/g, "-");

// ─── US COLLEGE RADIO ──────────────────────────────────────────────────────────

const usCollegeRadio: SeedContact[] = [
  {
    id: cid("music@kexp.org"),
    name: "KEXP Music Department",
    email: "music@kexp.org",
    outlet: "KEXP 90.3 FM",
    type: "radio",
    genre: "Indie / Alternative / World",
    region: "US",
    beat: "Radio Station",
    bio: "Seattle-based freeform radio station known for championing independent and emerging artists across genres.",
    website: "https://kexp.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wfmu.org"),
    name: "WFMU Music Director",
    email: "music@wfmu.org",
    outlet: "WFMU",
    type: "radio",
    genre: "Freeform / Eclectic",
    region: "US",
    beat: "Radio Station",
    bio: "Freeform, listener-supported radio station based in Jersey City, one of the longest-running freeform stations in the US.",
    website: "https://wfmu.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@kcrw.com"),
    name: "KCRW Music Department",
    email: "music@kcrw.com",
    outlet: "KCRW 89.9 FM",
    type: "radio",
    genre: "Indie / Electronic / World",
    region: "US",
    beat: "Radio Station",
    bio: "Santa Monica-based public radio station with influential music programming and tastemaking DJs.",
    website: "https://kcrw.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kutx.org"),
    name: "KUTX Music Director",
    email: "md@kutx.org",
    outlet: "KUTX 98.9 FM",
    type: "radio",
    genre: "Indie / Americana / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "Austin-based public radio station from the University of Texas, known for Austin music scene coverage.",
    website: "https://kutx.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@xpn.org"),
    name: "WXPN Music Department",
    email: "music@xpn.org",
    outlet: "WXPN 88.5 FM",
    type: "radio",
    genre: "Indie / Folk / Singer-Songwriter",
    region: "US",
    beat: "Radio Station",
    bio: "University of Pennsylvania radio station and home of World Cafe, a nationally syndicated music program.",
    website: "https://xpn.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wers.org"),
    name: "WERS Music Director",
    email: "md@wers.org",
    outlet: "WERS 88.9 FM",
    type: "radio",
    genre: "Indie / Alternative / Pop",
    region: "US",
    beat: "Radio Station",
    bio: "Emerson College radio station in Boston, one of the oldest and most powerful college radio stations in the US.",
    website: "https://wers.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wfuv.org"),
    name: "WFUV Music Department",
    email: "music@wfuv.org",
    outlet: "WFUV 90.7 FM",
    type: "radio",
    genre: "Indie / Folk / Americana",
    region: "US",
    beat: "Radio Station",
    bio: "Fordham University public media station in New York City, known for adult alternative and Americana programming.",
    website: "https://wfuv.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kcsb.org"),
    name: "KCSB Music Director",
    email: "md@kcsb.org",
    outlet: "KCSB 91.9 FM",
    type: "radio",
    genre: "Freeform / Indie / Experimental",
    region: "US",
    beat: "Radio Station",
    bio: "UC Santa Barbara freeform college radio station with diverse programming and strong local music support.",
    website: "https://kcsb.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kalx.berkeley.edu"),
    name: "KALX Music Director",
    email: "md@kalx.berkeley.edu",
    outlet: "KALX 90.7 FM",
    type: "radio",
    genre: "Freeform / Indie / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "UC Berkeley freeform radio station, a staple of Bay Area independent music culture since 1962.",
    website: "https://kalx.berkeley.edu",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wxyc.org"),
    name: "WXYC Music Director",
    email: "md@wxyc.org",
    outlet: "WXYC 89.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Experimental",
    region: "US",
    beat: "Radio Station",
    bio: "UNC Chapel Hill freeform station, the first radio station in the world to stream on the internet.",
    website: "https://wxyc.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wprb.com"),
    name: "WPRB Music Director",
    email: "music@wprb.com",
    outlet: "WPRB 103.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Jazz",
    region: "US",
    beat: "Radio Station",
    bio: "Princeton University freeform radio station broadcasting eclectic programming since 1940.",
    website: "https://wprb.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kvrx.org"),
    name: "KVRX Music Director",
    email: "md@kvrx.org",
    outlet: "KVRX 91.7 FM",
    type: "radio",
    genre: "Indie / Punk / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "University of Texas student-run radio station with a focus on independent and local Austin music.",
    website: "https://kvrx.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wmbr.org"),
    name: "WMBR Music Director",
    email: "md@wmbr.org",
    outlet: "WMBR 88.1 FM",
    type: "radio",
    genre: "Freeform / Indie / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "MIT student-run radio station in Cambridge, MA, known for eclectic and experimental programming.",
    website: "https://wmbr.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@whrb.org"),
    name: "WHRB Music Director",
    email: "md@whrb.org",
    outlet: "WHRB 95.3 FM",
    type: "radio",
    genre: "Classical / Jazz / Indie",
    region: "US",
    beat: "Radio Station",
    bio: "Harvard Radio Broadcasting, known for classical music orgies, jazz, and eclectic rock programming.",
    website: "https://whrb.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@ktru.org"),
    name: "KTRU Music Director",
    email: "md@ktru.org",
    outlet: "KTRU Rice Radio",
    type: "radio",
    genre: "Freeform / Indie / World",
    region: "US",
    beat: "Radio Station",
    bio: "Rice University freeform student radio station in Houston with diverse genre programming.",
    website: "https://ktru.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wrvu.org"),
    name: "WRVU Music Director",
    email: "md@wrvu.org",
    outlet: "WRVU Nashville",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "Vanderbilt University student radio station, an alternative voice in Nashville's music landscape.",
    website: "https://wrvu.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wkcr.org"),
    name: "WKCR Music Director",
    email: "md@wkcr.org",
    outlet: "WKCR 89.9 FM",
    type: "radio",
    genre: "Jazz / Classical / World",
    region: "US",
    beat: "Radio Station",
    bio: "Columbia University radio station in New York, renowned for jazz programming and marathon broadcasts.",
    website: "https://wkcr.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wnyu.org"),
    name: "WNYU Music Department",
    email: "music@wnyu.org",
    outlet: "WNYU 89.1 FM",
    type: "radio",
    genre: "Indie / Hip-Hop / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "New York University student radio with diverse programming spanning indie rock, hip-hop, and electronic music.",
    website: "https://wnyu.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wcbn.org"),
    name: "WCBN Music Director",
    email: "md@wcbn.org",
    outlet: "WCBN 88.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Jazz",
    region: "US",
    beat: "Radio Station",
    bio: "University of Michigan freeform radio station with a strong tradition of diverse music programming.",
    website: "https://wcbn.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wluw.org"),
    name: "WLUW Music Director",
    email: "md@wluw.org",
    outlet: "WLUW 88.7 FM",
    type: "radio",
    genre: "Indie / Alternative / Folk",
    region: "US",
    beat: "Radio Station",
    bio: "Loyola University Chicago radio station championing independent music and Chicago's local scene.",
    website: "https://wluw.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wpts.pitt.edu"),
    name: "WPTS Music Director",
    email: "md@wpts.pitt.edu",
    outlet: "WPTS 92.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "University of Pittsburgh student-run radio station with indie and alternative programming.",
    website: "https://wpts.pitt.edu",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wrct.org"),
    name: "WRCT Music Director",
    email: "md@wrct.org",
    outlet: "WRCT 88.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "Carnegie Mellon University freeform radio station with eclectic programming from Pittsburgh.",
    website: "https://wrct.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wsou.net"),
    name: "WSOU Music Director",
    email: "md@wsou.net",
    outlet: "WSOU 89.5 FM",
    type: "radio",
    genre: "Metal / Hard Rock / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "Seton Hall University station known as Pirate Radio, one of the few college stations dedicated to heavy music.",
    website: "https://wsou.net",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wuog.org"),
    name: "WUOG Music Director",
    email: "md@wuog.org",
    outlet: "WUOG 90.5 FM",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "University of Georgia student radio station in Athens, heart of a legendary indie music scene.",
    website: "https://wuog.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wvau.org"),
    name: "WVAU Music Director",
    email: "music@wvau.org",
    outlet: "WVAU",
    type: "radio",
    genre: "Indie / Pop / Alternative",
    region: "US",
    beat: "Radio Station",
    bio: "American University student-run radio station in Washington, D.C.",
    website: "https://wvau.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wsbf.net"),
    name: "WSBF Music Director",
    email: "md@wsbf.net",
    outlet: "WSBF 88.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "Clemson University student-run radio station with independent and alternative music programming.",
    website: "https://wsbf.net",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wxtj.com"),
    name: "WXTJ Music Director",
    email: "md@wxtj.com",
    outlet: "WXTJ 100.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "University of Virginia student-run radio station in Charlottesville.",
    website: "https://wxtj.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kucr.org"),
    name: "KUCR Music Director",
    email: "md@kucr.org",
    outlet: "KUCR 88.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Latin",
    region: "US",
    beat: "Radio Station",
    bio: "UC Riverside student and community radio station with diverse freeform programming.",
    website: "https://kucr.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kuci.org"),
    name: "KUCI Music Director",
    email: "md@kuci.org",
    outlet: "KUCI 88.9 FM",
    type: "radio",
    genre: "Freeform / Indie / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "UC Irvine freeform radio station with eclectic independent music programming.",
    website: "https://kuci.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kspc.org"),
    name: "KSPC Music Director",
    email: "md@kspc.org",
    outlet: "KSPC 88.7 FM",
    type: "radio",
    genre: "Indie / Freeform / World",
    region: "US",
    beat: "Radio Station",
    bio: "Pomona College and Claremont Colleges community radio station in Southern California.",
    website: "https://kspc.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kfjc.org"),
    name: "KFJC Music Director",
    email: "md@kfjc.org",
    outlet: "KFJC 89.7 FM",
    type: "radio",
    genre: "Freeform / Experimental / Noise",
    region: "US",
    beat: "Radio Station",
    bio: "Foothill College freeform station known for adventurous, experimental programming in the Bay Area.",
    website: "https://kfjc.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kzsc.org"),
    name: "KZSC Music Director",
    email: "md@kzsc.org",
    outlet: "KZSC 88.1 FM",
    type: "radio",
    genre: "Freeform / Indie / World",
    region: "US",
    beat: "Radio Station",
    bio: "UC Santa Cruz community radio station with freeform programming and strong local music ties.",
    website: "https://kzsc.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kdvs.org"),
    name: "KDVS Music Director",
    email: "md@kdvs.org",
    outlet: "KDVS 90.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Experimental",
    region: "US",
    beat: "Radio Station",
    bio: "UC Davis freeform radio station, one of the most influential college stations on the West Coast.",
    website: "https://kdvs.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kwva.org"),
    name: "KWVA Music Director",
    email: "md@kwva.org",
    outlet: "KWVA 88.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "University of Oregon student-run radio station in Eugene with indie and alternative focus.",
    website: "https://kwva.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@orangemedianetwork.com"),
    name: "KBVR Music Director",
    email: "md@orangemedianetwork.com",
    outlet: "KBVR 88.7 FM",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "Oregon State University student media radio station in Corvallis.",
    website: "https://orangemedianetwork.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kugs.org"),
    name: "KUGS Music Director",
    email: "md@kugs.org",
    outlet: "KUGS 89.3 FM",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "Western Washington University student-run radio station in Bellingham.",
    website: "https://kugs.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@kups.net"),
    name: "KUPS Music Director",
    email: "music@kups.net",
    outlet: "KUPS 90.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "University of Puget Sound student-run radio station in Tacoma, Washington.",
    website: "https://kups.net",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@kaosradio.org"),
    name: "KAOS Music Director",
    email: "music@kaosradio.org",
    outlet: "KAOS 89.3 FM",
    type: "radio",
    genre: "Freeform / Community / World",
    region: "US",
    beat: "Radio Station",
    bio: "Evergreen State College community radio station in Olympia, WA with freeform programming.",
    website: "https://kaosradio.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kcpr.org"),
    name: "KCPR Music Director",
    email: "md@kcpr.org",
    outlet: "KCPR 91.3 FM",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "Cal Poly San Luis Obispo student-run radio station on California's Central Coast.",
    website: "https://kcpr.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@kcsn.org"),
    name: "KCSN Music Department",
    email: "music@kcsn.org",
    outlet: "KCSN 88.5 FM",
    type: "radio",
    genre: "Indie / Americana / Folk",
    region: "US",
    beat: "Radio Station",
    bio: "Cal State Northridge public radio station with triple-A and Americana format programming.",
    website: "https://kcsn.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kxlu.com"),
    name: "KXLU Music Director",
    email: "md@kxlu.com",
    outlet: "KXLU 88.9 FM",
    type: "radio",
    genre: "Indie / Punk / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "Loyola Marymount University freeform radio station in Los Angeles.",
    website: "https://kxlu.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kxsc.org"),
    name: "KXSC Music Director",
    email: "md@kxsc.org",
    outlet: "KXSC Radio",
    type: "radio",
    genre: "Indie / Electronic / Experimental",
    region: "US",
    beat: "Radio Station",
    bio: "USC student-run radio station in Los Angeles with eclectic independent programming.",
    website: "https://kxsc.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wras.org"),
    name: "WRAS Music Director",
    email: "md@wras.org",
    outlet: "WRAS 88.5 FM",
    type: "radio",
    genre: "Indie / Alternative / Hip-Hop",
    region: "US",
    beat: "Radio Station",
    bio: "Georgia State University student-run station, known as Album 88 in Atlanta.",
    website: "https://wras.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wrek.org"),
    name: "WREK Music Director",
    email: "md@wrek.org",
    outlet: "WREK 91.1 FM",
    type: "radio",
    genre: "Freeform / Indie / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "Georgia Tech student-run radio station in Atlanta with eclectic freeform programming.",
    website: "https://wrek.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wutkradio.com"),
    name: "WUTK Music Director",
    email: "md@wutkradio.com",
    outlet: "WUTK 90.3 FM",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "University of Tennessee student-run radio station in Knoxville.",
    website: "https://wutkradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wmfo.org"),
    name: "WMFO Music Director",
    email: "md@wmfo.org",
    outlet: "WMFO 91.5 FM",
    type: "radio",
    genre: "Freeform / Indie / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "Tufts University freeform community radio station in Medford, Massachusetts.",
    website: "https://wmfo.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wzbc.org"),
    name: "WZBC Music Director",
    email: "md@wzbc.org",
    outlet: "WZBC 90.3 FM",
    type: "radio",
    genre: "Indie / Punk / Noise",
    region: "US",
    beat: "Radio Station",
    bio: "Boston College freeform radio station known for underground and independent music.",
    website: "https://wzbc.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wrbbradio.com"),
    name: "WRBB Music Director",
    email: "md@wrbbradio.com",
    outlet: "WRBB 104.9 FM",
    type: "radio",
    genre: "Indie / Hip-Hop / R&B",
    region: "US",
    beat: "Radio Station",
    bio: "Northeastern University student-run radio station in Boston.",
    website: "https://wrbbradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wesufm.org"),
    name: "WESU Music Director",
    email: "music@wesufm.org",
    outlet: "WESU 88.1 FM",
    type: "radio",
    genre: "Freeform / Indie / Community",
    region: "US",
    beat: "Radio Station",
    bio: "Wesleyan University community radio station in Middletown, Connecticut.",
    website: "https://wesufm.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@whus.org"),
    name: "WHUS Music Director",
    email: "md@whus.org",
    outlet: "WHUS 91.7 FM",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "University of Connecticut student-run radio station in Storrs.",
    website: "https://whus.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wpkn.org"),
    name: "WPKN Music Director",
    email: "music@wpkn.org",
    outlet: "WPKN 89.5 FM",
    type: "radio",
    genre: "Freeform / Folk / World",
    region: "US",
    beat: "Radio Station",
    bio: "University of Bridgeport community radio station with freeform programming in Connecticut.",
    website: "https://wpkn.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wruv.org"),
    name: "WRUV Music Director",
    email: "md@wruv.org",
    outlet: "WRUV 90.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "University of Vermont student-run radio station in Burlington.",
    website: "https://wruv.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wrpi.org"),
    name: "WRPI Music Director",
    email: "md@wrpi.org",
    outlet: "WRPI 91.5 FM",
    type: "radio",
    genre: "Freeform / Indie / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "Rensselaer Polytechnic Institute student radio station in Troy, New York.",
    website: "https://wrpi.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wvkr.org"),
    name: "WVKR Music Director",
    email: "md@wvkr.org",
    outlet: "WVKR 91.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Jazz",
    region: "US",
    beat: "Radio Station",
    bio: "Vassar College freeform radio station in Poughkeepsie, New York.",
    website: "https://wvkr.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@witr.rit.edu"),
    name: "WITR Music Director",
    email: "md@witr.rit.edu",
    outlet: "WITR 89.7 FM",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "Rochester Institute of Technology student-run radio station in Rochester, New York.",
    website: "https://witr.rit.edu",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wknc.org"),
    name: "WKNC Music Director",
    email: "md@wknc.org",
    outlet: "WKNC 88.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Electronic",
    region: "US",
    beat: "Radio Station",
    bio: "NC State University student-run radio station in Raleigh, North Carolina.",
    website: "https://wknc.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wudr.udayton.edu"),
    name: "WUDR Music Director",
    email: "md@wudr.udayton.edu",
    outlet: "WUDR Flyer Radio",
    type: "radio",
    genre: "Indie / Alternative / Pop",
    region: "US",
    beat: "Radio Station",
    bio: "University of Dayton student-run radio station in Ohio.",
    website: "https://wudr.udayton.edu",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wruw.org"),
    name: "WRUW Music Director",
    email: "md@wruw.org",
    outlet: "WRUW 91.1 FM",
    type: "radio",
    genre: "Freeform / Indie / World",
    region: "US",
    beat: "Radio Station",
    bio: "Case Western Reserve University freeform radio station in Cleveland, Ohio.",
    website: "https://wruw.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wcsb.org"),
    name: "WCSB Music Director",
    email: "md@wcsb.org",
    outlet: "WCSB 89.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "Cleveland State University community radio station with diverse freeform programming.",
    website: "https://wcsb.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wmsr.org"),
    name: "WMSR Music Director",
    email: "md@wmsr.org",
    outlet: "WMSR Radio",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "Miami University student-run radio station in Oxford, Ohio.",
    website: "https://wmsr.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@waif883.org"),
    name: "WAIF Music Director",
    email: "music@waif883.org",
    outlet: "WAIF 88.3 FM",
    type: "radio",
    genre: "Freeform / Community / World",
    region: "US",
    beat: "Radio Station",
    bio: "Volunteer-run community radio station in Cincinnati, Ohio.",
    website: "https://waif883.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@gwradio.com"),
    name: "WRGW Music Director",
    email: "music@gwradio.com",
    outlet: "WRGW Radio",
    type: "radio",
    genre: "Indie / Pop / Alternative",
    region: "US",
    beat: "Radio Station",
    bio: "George Washington University student-run radio station in Washington, D.C.",
    website: "https://gwradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wvud.org"),
    name: "WVUD Music Director",
    email: "md@wvud.org",
    outlet: "WVUD 91.3 FM",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "University of Delaware student-run radio station in Newark, Delaware.",
    website: "https://wvud.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wxjm.org"),
    name: "WXJM Music Director",
    email: "md@wxjm.org",
    outlet: "WXJM 88.7 FM",
    type: "radio",
    genre: "Indie / Alternative / Punk",
    region: "US",
    beat: "Radio Station",
    bio: "James Madison University student-run radio station in Harrisonburg, Virginia.",
    website: "https://wxjm.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kcou.fm"),
    name: "KCOU Music Director",
    email: "md@kcou.fm",
    outlet: "KCOU 88.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "US",
    beat: "Radio Station",
    bio: "University of Missouri student-run radio station in Columbia, Missouri.",
    website: "https://kcou.fm",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@wdce.org"),
    name: "WDCE Music Director",
    email: "md@wdce.org",
    outlet: "WDCE Radio",
    type: "radio",
    genre: "Indie / Alternative / Freeform",
    region: "US",
    beat: "Radio Station",
    bio: "University of Richmond student-run radio station in Virginia.",
    website: "https://wdce.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("submissions@chirpradio.org"),
    name: "CHIRP Radio Music Director",
    email: "submissions@chirpradio.org",
    outlet: "CHIRP Radio",
    type: "radio",
    genre: "Indie / Alternative / Pop",
    region: "US",
    beat: "Radio Station",
    bio: "Chicago Independent Radio Project, a volunteer-run community station supporting independent music.",
    website: "https://chirpradio.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@kdhx.org"),
    name: "KDHX Music Director",
    email: "music@kdhx.org",
    outlet: "KDHX 88.1 FM",
    type: "radio",
    genre: "Roots / Blues / Americana",
    region: "US",
    beat: "Radio Station",
    bio: "Community radio station in St. Louis known for roots, blues, and Americana programming.",
    website: "https://kdhx.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@wyep.org"),
    name: "WYEP Music Director",
    email: "music@wyep.org",
    outlet: "WYEP 91.3 FM",
    type: "radio",
    genre: "Indie / Folk / Americana",
    region: "US",
    beat: "Radio Station",
    bio: "Community-supported public radio station in Pittsburgh with adult alternative and Americana programming.",
    website: "https://wyep.org",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("md@kanw.com"),
    name: "KANW Music Director",
    email: "md@kanw.com",
    outlet: "KANW 89.1 FM",
    type: "radio",
    genre: "Indie / Roots / Latin",
    region: "US",
    beat: "Radio Station",
    bio: "Albuquerque public radio station with diverse programming including indie, roots, and New Mexican music.",
    website: "https://kanw.com",
    verified: false,
    articleCount: 0,
  },
];

// ─── CANADIAN COLLEGE RADIO ────────────────────────────────────────────────────

const canadianRadio: SeedContact[] = [
  {
    id: cid("music@citr.ca"),
    name: "CiTR Music Director",
    email: "music@citr.ca",
    outlet: "CiTR 101.9 FM",
    type: "radio",
    genre: "Indie / Alternative / Electronic",
    region: "CA",
    beat: "Radio Station",
    bio: "University of British Columbia student radio station in Vancouver with a strong indie music focus.",
    website: "https://citr.ca",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@cjsw.com"),
    name: "CJSW Music Director",
    email: "music@cjsw.com",
    outlet: "CJSW 90.9 FM",
    type: "radio",
    genre: "Indie / Freeform / World",
    region: "CA",
    beat: "Radio Station",
    bio: "University of Calgary campus and community radio station with diverse volunteer-driven programming.",
    website: "https://cjsw.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@cjam.ca"),
    name: "CJAM Music Director",
    email: "music@cjam.ca",
    outlet: "CJAM 99.1 FM",
    type: "radio",
    genre: "Freeform / Indie / Community",
    region: "CA",
    beat: "Radio Station",
    bio: "University of Windsor campus and community radio station in Ontario.",
    website: "https://cjam.ca",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@cfrc.ca"),
    name: "CFRC Music Director",
    email: "music@cfrc.ca",
    outlet: "CFRC 101.9 FM",
    type: "radio",
    genre: "Indie / Freeform / Folk",
    region: "CA",
    beat: "Radio Station",
    bio: "Queen's University campus and community radio station in Kingston, Ontario, one of Canada's oldest.",
    website: "https://cfrc.ca",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@chuo.fm"),
    name: "CHUO Music Director",
    email: "music@chuo.fm",
    outlet: "CHUO 89.1 FM",
    type: "radio",
    genre: "Indie / World / Community",
    region: "CA",
    beat: "Radio Station",
    bio: "University of Ottawa campus and community radio station with bilingual programming.",
    website: "https://chuo.fm",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@ckut.ca"),
    name: "CKUT Music Director",
    email: "music@ckut.ca",
    outlet: "CKUT 90.3 FM",
    type: "radio",
    genre: "Freeform / Indie / Experimental",
    region: "CA",
    beat: "Radio Station",
    bio: "McGill University community radio station in Montreal with eclectic programming.",
    website: "https://ckut.ca",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@cjlo.com"),
    name: "CJLO Music Director",
    email: "music@cjlo.com",
    outlet: "CJLO 1690 AM",
    type: "radio",
    genre: "Indie / Hip-Hop / Electronic",
    region: "CA",
    beat: "Radio Station",
    bio: "Concordia University student radio station in Montreal.",
    website: "https://cjlo.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@chsr.com"),
    name: "CHSR Music Director",
    email: "music@chsr.com",
    outlet: "CHSR 97.9 FM",
    type: "radio",
    genre: "Indie / Alternative / Community",
    region: "CA",
    beat: "Radio Station",
    bio: "University of New Brunswick campus and community radio station in Fredericton.",
    website: "https://chsr.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@cfuv.ca"),
    name: "CFUV Music Director",
    email: "music@cfuv.ca",
    outlet: "CFUV 101.9 FM",
    type: "radio",
    genre: "Indie / Freeform / World",
    region: "CA",
    beat: "Radio Station",
    bio: "University of Victoria campus and community radio station in British Columbia.",
    website: "https://cfuv.ca",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@cjsf.ca"),
    name: "CJSF Music Director",
    email: "music@cjsf.ca",
    outlet: "CJSF 90.1 FM",
    type: "radio",
    genre: "Indie / Freeform / Community",
    region: "CA",
    beat: "Radio Station",
    bio: "Simon Fraser University campus and community radio station in Burnaby, BC.",
    website: "https://cjsf.ca",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@cism893.ca"),
    name: "CISM Music Director",
    email: "music@cism893.ca",
    outlet: "CISM 89.3 FM",
    type: "radio",
    genre: "Indie / Francophone / Electronic",
    region: "CA",
    beat: "Radio Station",
    bio: "Universite de Montreal campus radio station with French-language and indie music programming.",
    website: "https://cism893.ca",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@ckcufm.com"),
    name: "CKCU Music Director",
    email: "music@ckcufm.com",
    outlet: "CKCU 93.1 FM",
    type: "radio",
    genre: "Folk / World / Indie",
    region: "CA",
    beat: "Radio Station",
    bio: "Carleton University campus and community radio station in Ottawa, Ontario.",
    website: "https://ckcufm.com",
    verified: false,
    articleCount: 0,
  },
];

// ─── UK / EUROPEAN RADIO ───────────────────────────────────────────────────────

const ukEuropeanRadio: SeedContact[] = [
  {
    id: cid("music@bbc.co.uk"),
    name: "BBC Radio 6 Music Submissions",
    email: "music@bbc.co.uk",
    outlet: "BBC Radio 6 Music",
    type: "radio",
    genre: "Indie / Alternative / Electronic",
    region: "UK",
    beat: "Radio Station",
    bio: "BBC digital radio station dedicated to alternative music, widely regarded as the UK's premier taste-making station.",
    website: "https://bbc.co.uk/6music",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("submissions@amazingradio.com"),
    name: "Amazing Radio Music Team",
    email: "submissions@amazingradio.com",
    outlet: "Amazing Radio",
    type: "radio",
    genre: "Indie / Pop / Alternative",
    region: "UK",
    beat: "Radio Station",
    bio: "UK-based radio station and platform dedicated to championing new and independent music from around the world.",
    website: "https://amazingradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@resonancefm.com"),
    name: "Resonance FM Programming",
    email: "info@resonancefm.com",
    outlet: "Resonance FM 104.4",
    type: "radio",
    genre: "Experimental / Art / Sound Art",
    region: "UK",
    beat: "Radio Station",
    bio: "London-based arts radio station known for experimental and avant-garde programming.",
    website: "https://resonancefm.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@sohoradiolondon.com"),
    name: "Soho Radio Programming",
    email: "info@sohoradiolondon.com",
    outlet: "Soho Radio",
    type: "radio",
    genre: "Eclectic / Soul / Electronic",
    region: "UK",
    beat: "Radio Station",
    bio: "Independent radio station broadcasting from the heart of London's Soho district.",
    website: "https://sohoradiolondon.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@reprezent.org.uk"),
    name: "Reprezent Radio Programming",
    email: "info@reprezent.org.uk",
    outlet: "Reprezent Radio",
    type: "radio",
    genre: "Grime / Hip-Hop / R&B",
    region: "UK",
    beat: "Radio Station",
    bio: "Youth-led radio station in South London focusing on grime, hip-hop, and urban music.",
    website: "https://reprezent.org.uk",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("submissions@foundation.fm"),
    name: "Foundation FM Programming",
    email: "submissions@foundation.fm",
    outlet: "Foundation FM",
    type: "radio",
    genre: "Electronic / Soul / Jazz",
    region: "UK",
    beat: "Radio Station",
    bio: "London-based online radio station platforming underrepresented voices in music and culture.",
    website: "https://foundation.fm",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@threadsradio.com"),
    name: "Threads Radio Programming",
    email: "info@threadsradio.com",
    outlet: "Threads Radio",
    type: "radio",
    genre: "Electronic / Experimental / Ambient",
    region: "UK",
    beat: "Radio Station",
    bio: "Community-driven online radio station based in London with a focus on electronic and experimental music.",
    website: "https://threadsradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@rinse.fm"),
    name: "Rinse FM Music Team",
    email: "music@rinse.fm",
    outlet: "Rinse FM",
    type: "radio",
    genre: "Electronic / Grime / Bass",
    region: "UK",
    beat: "Radio Station",
    bio: "Iconic London radio station that helped break grime, dubstep, and UK bass music globally.",
    website: "https://rinse.fm",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("submissions@nts.live"),
    name: "NTS Radio Submissions",
    email: "submissions@nts.live",
    outlet: "NTS Radio",
    type: "radio",
    genre: "Eclectic / Electronic / World",
    region: "UK",
    beat: "Radio Station",
    bio: "Global online radio station based in London with studios in LA, Shanghai, and Manchester.",
    website: "https://nts.live",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@cashmereradio.com"),
    name: "Cashmere Radio Programming",
    email: "info@cashmereradio.com",
    outlet: "Cashmere Radio",
    type: "radio",
    genre: "Experimental / Sound Art / Electronic",
    region: "DE",
    beat: "Radio Station",
    bio: "Community radio project in Berlin focused on experimental music, sound art, and cultural programming.",
    website: "https://cashmereradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("contact@radioalhara.net"),
    name: "Radio Alhara Programming",
    email: "contact@radioalhara.net",
    outlet: "Radio Alhara",
    type: "radio",
    genre: "World / Electronic / Experimental",
    region: "Global",
    beat: "Radio Station",
    bio: "Community radio station founded in Bethlehem, Palestine, broadcasting music and culture globally.",
    website: "https://radioalhara.net",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@refugeworldwide.com"),
    name: "Refuge Worldwide Programming",
    email: "info@refugeworldwide.com",
    outlet: "Refuge Worldwide",
    type: "radio",
    genre: "Electronic / World / Club",
    region: "DE",
    beat: "Radio Station",
    bio: "Community radio station in Berlin raising awareness for the refugee cause through music and culture.",
    website: "https://refugeworldwide.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@bytefm.de"),
    name: "ByteFM Music Team",
    email: "music@bytefm.de",
    outlet: "ByteFM",
    type: "radio",
    genre: "Indie / Alternative / Pop",
    region: "DE",
    beat: "Radio Station",
    bio: "German web radio station focused on independent and alternative music with curated programming.",
    website: "https://bytefm.de",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@fluxfm.de"),
    name: "FluxFM Music Team",
    email: "music@fluxfm.de",
    outlet: "FluxFM",
    type: "radio",
    genre: "Indie / Electronic / Alternative",
    region: "DE",
    beat: "Radio Station",
    bio: "Berlin-based radio station with a focus on indie, electronic, and alternative music.",
    website: "https://fluxfm.de",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("contact@nova.fr"),
    name: "Radio Nova Music Team",
    email: "contact@nova.fr",
    outlet: "Radio Nova",
    type: "radio",
    genre: "World / Electronic / Soul",
    region: "FR",
    beat: "Radio Station",
    bio: "Parisian radio station known for eclectic programming spanning world music, soul, hip-hop, and electronic.",
    website: "https://nova.fr",
    verified: false,
    articleCount: 0,
  },
];

// ─── AUSTRALIAN RADIO ──────────────────────────────────────────────────────────

const australianRadio: SeedContact[] = [
  {
    id: cid("music@fbiradio.com"),
    name: "FBi Radio Music Director",
    email: "music@fbiradio.com",
    outlet: "FBi Radio 94.5 FM",
    type: "radio",
    genre: "Indie / Electronic / Hip-Hop",
    region: "AU",
    beat: "Radio Station",
    bio: "Sydney community radio station dedicated to new Australian music and culture.",
    website: "https://fbiradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@pbsfm.org.au"),
    name: "PBS FM Music Director",
    email: "music@pbsfm.org.au",
    outlet: "PBS 106.7 FM",
    type: "radio",
    genre: "Indie / Roots / World",
    region: "AU",
    beat: "Radio Station",
    bio: "Melbourne community radio station known for independent music programming and listener support.",
    website: "https://pbsfm.org.au",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@rrr.org.au"),
    name: "3RRR Music Director",
    email: "music@rrr.org.au",
    outlet: "3RRR 102.7 FM",
    type: "radio",
    genre: "Indie / Alternative / Punk",
    region: "AU",
    beat: "Radio Station",
    bio: "Melbourne community radio station and one of Australia's most influential independent music broadcasters.",
    website: "https://rrr.org.au",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@4zzz.org.au"),
    name: "4ZZZ Music Director",
    email: "music@4zzz.org.au",
    outlet: "4ZZZ 102.1 FM",
    type: "radio",
    genre: "Indie / Alternative / Punk",
    region: "AU",
    beat: "Radio Station",
    bio: "Brisbane community radio station with a strong focus on local and independent Australian music.",
    website: "https://4zzz.org.au",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@rtrfm.com.au"),
    name: "RTR FM Music Director",
    email: "music@rtrfm.com.au",
    outlet: "RTR FM 92.1",
    type: "radio",
    genre: "Indie / Alternative / Electronic",
    region: "AU",
    beat: "Radio Station",
    bio: "Perth community radio station supporting Western Australian independent music and artists.",
    website: "https://rtrfm.com.au",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@2ser.com"),
    name: "2SER Music Director",
    email: "music@2ser.com",
    outlet: "2SER 107.3 FM",
    type: "radio",
    genre: "Indie / World / Community",
    region: "AU",
    beat: "Radio Station",
    bio: "Sydney community radio station operated by Macquarie University and UTS with diverse programming.",
    website: "https://2ser.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@syn.org.au"),
    name: "SYN Media Music Director",
    email: "music@syn.org.au",
    outlet: "SYN 90.7 FM",
    type: "radio",
    genre: "Indie / Pop / Hip-Hop",
    region: "AU",
    beat: "Radio Station",
    bio: "Melbourne youth media organization providing radio programming by and for young Australians.",
    website: "https://syn.org.au",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@edgeradio.org.au"),
    name: "Edge Radio Music Director",
    email: "music@edgeradio.org.au",
    outlet: "Edge Radio 99.3 FM",
    type: "radio",
    genre: "Indie / Alternative / Rock",
    region: "AU",
    beat: "Radio Station",
    bio: "University of Tasmania community radio station in Hobart supporting independent music.",
    website: "https://edgeradio.org.au",
    verified: false,
    articleCount: 0,
  },
];

// ─── ONLINE / INDEPENDENT RADIO ────────────────────────────────────────────────

const onlineRadio: SeedContact[] = [
  {
    id: cid("submissions@thelotradio.com"),
    name: "The Lot Radio Programming",
    email: "submissions@thelotradio.com",
    outlet: "The Lot Radio",
    type: "radio",
    genre: "Eclectic / Electronic / World",
    region: "US",
    beat: "Radio Station",
    bio: "Independent online radio station broadcasting live from a shipping container in Brooklyn, New York.",
    website: "https://thelotradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@worldwidefm.net"),
    name: "Worldwide FM Programming",
    email: "info@worldwidefm.net",
    outlet: "Worldwide FM",
    type: "radio",
    genre: "World / Jazz / Electronic",
    region: "Global",
    beat: "Radio Station",
    bio: "Global online radio station founded by Gilles Peterson championing world music and jazz.",
    website: "https://worldwidefm.net",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@netilradio.com"),
    name: "Netil Radio Programming",
    email: "info@netilradio.com",
    outlet: "Netil Radio",
    type: "radio",
    genre: "Electronic / House / Eclectic",
    region: "UK",
    beat: "Radio Station",
    bio: "Rooftop community radio station in Hackney, London with eclectic electronic programming.",
    website: "https://netilradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@balamii.com"),
    name: "Balamii Radio Programming",
    email: "info@balamii.com",
    outlet: "Balamii",
    type: "radio",
    genre: "Electronic / Club / World",
    region: "UK",
    beat: "Radio Station",
    bio: "Online radio station based in Peckham, London, featuring electronic and club music programming.",
    website: "https://balamii.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@n10.as"),
    name: "n10.as Radio Programming",
    email: "info@n10.as",
    outlet: "n10.as",
    type: "radio",
    genre: "Electronic / Ambient / Experimental",
    region: "Global",
    beat: "Radio Station",
    bio: "Online radio platform focused on electronic, ambient, and experimental music from around the world.",
    website: "https://n10.as",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("submissions@noodsradio.com"),
    name: "Noods Radio Programming",
    email: "submissions@noodsradio.com",
    outlet: "Noods Radio",
    type: "radio",
    genre: "Electronic / Club / Experimental",
    region: "UK",
    beat: "Radio Station",
    bio: "Bristol-based online radio station with a focus on club music, experimental sounds, and local culture.",
    website: "https://noodsradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@orionradio.co"),
    name: "Orion Radio Programming",
    email: "info@orionradio.co",
    outlet: "Orion Radio",
    type: "radio",
    genre: "Electronic / Indie / Experimental",
    region: "Global",
    beat: "Radio Station",
    bio: "Independent online radio station with eclectic programming spanning electronic and indie music.",
    website: "https://orionradio.co",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("submissions@dublab.com"),
    name: "dublab Music Submissions",
    email: "submissions@dublab.com",
    outlet: "dublab",
    type: "radio",
    genre: "Electronic / Experimental / World",
    region: "US",
    beat: "Radio Station",
    bio: "Los Angeles-based nonprofit internet radio station dedicated to the progression of music, arts, and culture.",
    website: "https://dublab.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("music@bff.fm"),
    name: "BFF.fm Music Director",
    email: "music@bff.fm",
    outlet: "BFF.fm",
    type: "radio",
    genre: "Indie / Pop / Eclectic",
    region: "US",
    beat: "Radio Station",
    bio: "San Francisco community internet radio station with diverse independent music programming.",
    website: "https://bff.fm",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@ehfm.live"),
    name: "EHFM Programming",
    email: "info@ehfm.live",
    outlet: "EHFM",
    type: "radio",
    genre: "Electronic / Indie / Eclectic",
    region: "UK",
    beat: "Radio Station",
    bio: "Edinburgh-based community internet radio station with diverse music and cultural programming.",
    website: "https://ehfm.live",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("contact@somafm.com"),
    name: "SomaFM Programming",
    email: "contact@somafm.com",
    outlet: "SomaFM",
    type: "radio",
    genre: "Electronic / Ambient / Indie",
    region: "US",
    beat: "Radio Station",
    bio: "San Francisco listener-supported internet radio with over 30 channels of commercial-free music.",
    website: "https://somafm.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@kioskradio.com"),
    name: "Kiosk Radio Programming",
    email: "info@kioskradio.com",
    outlet: "Kiosk Radio",
    type: "radio",
    genre: "Electronic / Club / World",
    region: "Global",
    beat: "Radio Station",
    bio: "Brussels-based community radio station broadcasting from a kiosk in the city center.",
    website: "https://kioskradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("info@operatorradio.com"),
    name: "Operator Radio Programming",
    email: "info@operatorradio.com",
    outlet: "Operator Radio",
    type: "radio",
    genre: "Electronic / Club / Techno",
    region: "Global",
    beat: "Radio Station",
    bio: "Rotterdam-based online radio station focused on electronic and club music culture.",
    website: "https://operatorradio.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("contact@lfrequence.com"),
    name: "Lyl Radio Programming",
    email: "contact@lfrequence.com",
    outlet: "Lyl Radio",
    type: "radio",
    genre: "Electronic / Experimental / World",
    region: "FR",
    beat: "Radio Station",
    bio: "Lyon-based online community radio station with eclectic music and cultural programming.",
    website: "https://lfrequence.com",
    verified: false,
    articleCount: 0,
  },
  {
    id: cid("contact@radioflouka.com"),
    name: "Radio Flouka Programming",
    email: "contact@radioflouka.com",
    outlet: "Radio Flouka",
    type: "radio",
    genre: "Electronic / World / North African",
    region: "Global",
    beat: "Radio Station",
    bio: "Tunis-based online radio station celebrating North African and Mediterranean music and culture.",
    website: "https://radioflouka.com",
    verified: false,
    articleCount: 0,
  },
];

// ─── EXPORT ────────────────────────────────────────────────────────────────────

export const radioSeedContacts: SeedContact[] = [
  ...usCollegeRadio,
  ...canadianRadio,
  ...ukEuropeanRadio,
  ...australianRadio,
  ...onlineRadio,
];
